@extends('layouts.app')
@section('title','Complete profile')
@section('content')
<div class="profile-shell"><div class="profile-card"><h1>Complete your profile</h1><p>Your verified {{ $user->email_verified_at?'email address':'mobile number' }} cannot be changed here.</p>@if($errors->any())<div class="alert alert-error">{{ $errors->first() }}</div>@endif
<form method="POST" action="{{ route('onboarding.profile.store') }}">@csrf
@if($user->account_type==='photographer')<div class="two"><div class="form-group"><label>First name</label><input name="first_name" value="{{ old('first_name') }}" required></div><div class="form-group"><label>Last name</label><input name="last_name" value="{{ old('last_name') }}" required></div></div><div class="form-group"><label>Company or studio name</label><input name="company_name" value="{{ old('company_name') }}" required></div><div class="form-group"><label>Company email address</label><input type="email" name="email" value="{{ old('email',$user->email) }}" @readonly($user->email_verified_at) required></div>
@else<div class="form-group"><label>Full name</label><input name="name" value="{{ old('name') }}" required autofocus></div><div class="form-group"><label>Email address @unless($user->email_verified_at)<span>(optional)</span>@endunless</label><input type="email" name="email" value="{{ old('email',$user->email) }}" @readonly($user->email_verified_at)></div>@endif
<div class="form-group"><label>Verified {{ $user->email_verified_at?'email':'mobile' }}</label><input value="{{ $user->email_verified_at?$user->email:$user->mobile_e164 }}" readonly disabled></div><button class="btn btn-primary btn-lg full">Finish setup</button></form></div></div>
@endsection
@push('styles')<style>.profile-shell{min-height:calc(100vh - 60px);display:grid;place-items:center;padding:24px;background:#f8fafc}.profile-card{width:min(100%,560px);padding:32px;background:#fff;border-radius:20px;box-shadow:var(--shadow-lg)}.profile-card>p{color:var(--muted);margin:5px 0 22px}.two{display:grid;grid-template-columns:1fr 1fr;gap:12px}.full{width:100%;justify-content:center}@media(max-width:480px){.two{grid-template-columns:1fr}}</style>@endpush
