@extends('layouts.app')
@section('title','Take a Selfie')
@section('content')
<div class="selfie-shell"><div class="selfie-card"><h1>Take a Selfie</h1><p>Take a clear selfie so we can check your photographer profile photo quality. This is not an identity or liveness verification.</p>@if($errors->any())<div class="alert alert-error">{{ $errors->first() }}</div>@endif
<div class="camera"><video id="video" autoplay muted playsinline></video><img id="preview" alt="Captured selfie"><div class="guide"></div></div><div id="camera-error" class="alert alert-error" hidden>Camera access is unavailable. Allow camera permission in your browser settings, then reload this page.</div>
<form method="POST" action="{{ route('onboarding.selfie.store') }}" enctype="multipart/form-data" id="form">@csrf<input type="file" name="selfie" id="selfie" accept="image/jpeg,image/png,image/webp" capture="user" hidden><button type="button" class="btn btn-primary btn-lg full" id="capture">Capture selfie</button><button type="button" class="btn btn-outline btn-lg full" id="retake" hidden>Retake</button><button class="btn btn-primary btn-lg full" id="continue" hidden>Use this selfie</button><label class="fallback" for="selfie">Camera unavailable? Choose a freshly captured image</label></form></div></div>
@endsection
@push('styles')<style>.selfie-shell{min-height:calc(100vh - 60px);display:grid;place-items:center;padding:20px;background:#0f172a}.selfie-card{width:min(100%,480px);padding:24px;background:#fff;border-radius:20px}.selfie-card>p{color:var(--muted);margin:6px 0 18px}.camera{position:relative;aspect-ratio:3/4;background:#111827;border-radius:16px;overflow:hidden;margin-bottom:16px}.camera video,.camera img{width:100%;height:100%;object-fit:cover;transform:scaleX(-1)}.camera img{display:none}.guide{position:absolute;inset:12% 16%;border:3px solid rgba(255,255,255,.8);border-radius:50%}.full{width:100%;justify-content:center;margin-top:9px}.fallback{display:block;text-align:center;color:var(--p);margin-top:14px;cursor:pointer}</style>@endpush
@push('scripts')<script>const video=document.getElementById('video'),preview=document.getElementById('preview'),input=document.getElementById('selfie'),capture=document.getElementById('capture'),retake=document.getElementById('retake'),cont=document.getElementById('continue');let stream;navigator.mediaDevices?.getUserMedia({video:{facingMode:'user',width:{ideal:1080},height:{ideal:1440}},audio:false}).then(s=>{stream=s;video.srcObject=s}).catch(()=>document.getElementById('camera-error').hidden=false);capture.onclick=()=>{if(!video.videoWidth)return;const c=document.createElement('canvas');c.width=video.videoWidth;c.height=video.videoHeight;c.getContext('2d').drawImage(video,0,0);c.toBlob(b=>{const f=new File([b],'selfie.jpg',{type:'image/jpeg'}),dt=new DataTransfer();dt.items.add(f);input.files=dt.files;preview.src=URL.createObjectURL(b);preview.style.display='block';video.style.display='none';capture.hidden=true;retake.hidden=false;cont.hidden=false},'image/jpeg',.9)};retake.onclick=()=>{preview.style.display='none';video.style.display='block';capture.hidden=false;retake.hidden=true;cont.hidden=true;input.value=''};input.onchange=()=>{if(input.files[0]){preview.src=URL.createObjectURL(input.files[0]);preview.style.display='block';video.style.display='none';capture.hidden=true;retake.hidden=false;cont.hidden=false}}</script>@endpush
