<?php
namespace App\Console\Commands;
use App\Models\Photo;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Storage;
class PlanLegacyMediaMigration extends Command {
 protected $signature='media:migration-plan {--batch=100 : Proposed resumable batch size} {--json : Output complete JSON report}';
 protected $description='Read-only inventory and migration mapping for legacy public photo media';
 public function handle(): int { $disk=Storage::disk('public');$referenced=[];$missing=[];$mapping=[];$bytes=0;Photo::query()->select(['id','group_id','path','thumbnail_path','file_size'])->orderBy('id')->chunkById(500,function($photos)use($disk,&$referenced,&$missing,&$mapping,&$bytes){foreach($photos as $photo){foreach(array_unique(array_filter([$photo->path,$photo->thumbnail_path])) as $source){$source=ltrim(str_replace('\\','/',$source),'/');$referenced[$source]=true;if(!$disk->exists($source)){$missing[]=['photo_id'=>$photo->id,'source'=>$source];continue;}$size=$disk->size($source);$bytes+=$size;$extension=strtolower(pathinfo($source,PATHINFO_EXTENSION));$token=hash_hmac('sha256',$photo->id.'|'.$source,(string)config('app.key'));$destination=config('media.prefixes.originals').'/groups/'.$photo->group_id.'/'.$token.($extension?'.'.$extension:'');$mapping[]=['photo_id'=>$photo->id,'source'=>$source,'destination'=>$destination,'size'=>$size];}}});$files=collect($disk->allFiles())->reject(fn($path)=>str_starts_with($path,'tests/'))->values();$orphans=$files->reject(fn($path)=>isset($referenced[$path]))->values();$report=['dry_run'=>true,'generated_at'=>now()->toIso8601String(),'photo_records'=>Photo::count(),'referenced_unique_files'=>count($referenced),'existing_referenced_files'=>count($mapping),'missing_references'=>$missing,'orphan_files'=>$orphans->all(),'source_bytes'=>$bytes,'batch_size'=>max(1,(int)$this->option('batch')),'estimated_batches'=>(int)ceil(max(1,count($mapping))/max(1,(int)$this->option('batch'))),'mapping'=>$mapping,'database_changes_on_copy'=>['photos.path'=>'unchanged during copy','photos.thumbnail_path'=>'unchanged during copy','media_assets'=>'insert only after verification','media_variants'=>'insert only after verification','media_migration_items'=>'per-item copy and verification state']];if($this->option('json')){$this->line(json_encode($report,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES));}else{$this->table(['Metric','Value'],[['Dry run','yes'],['Photo records',$report['photo_records']],['Referenced unique files',$report['referenced_unique_files']],['Existing mappings',$report['existing_referenced_files']],['Missing references',count($missing)],['Orphan files',$orphans->count()],['Source bytes',$bytes],['Batch size',$report['batch_size']],['Estimated batches',$report['estimated_batches']]]);$this->info('No files or database records were changed. Use --json for mappings and discrepancies.');}return self::SUCCESS; }
}
