<?php
namespace App\Services\Transactions;
use App\Models\{FinancialTransaction,RazorpayOrder,Subscription,User,WalletLedgerEntry,WalletTopUp};use Illuminate\Support\Str;
class TransactionProjector{
 public function sync(User$o):void{$o->subscriptions()->get()->each(fn($x)=>$this->subscription($x));RazorpayOrder::where('user_id',$o->id)->where('status','!=','paid')->get()->each(fn($x)=>$this->order($x));WalletTopUp::where('studio_owner_id',$o->id)->get()->each(fn($x)=>$this->topUp($x));WalletLedgerEntry::where('studio_owner_id',$o->id)->where('entry_type','!=','top_up_credit')->get()->each(fn($x)=>$this->ledger($x));}
 private function put(string$type,string$id,array$d):void{$row=FinancialTransaction::where(['source_type'=>$type,'source_id'=>$id])->first();if(!$row){FinancialTransaction::create(['uuid'=>(string)Str::uuid(),'source_type'=>$type,'source_id'=>$id]+$d);return;}if(!in_array($row->status,['paid','completed','refunded','reversed'],true))$row->update($d);}
 public function subscription(Subscription$s):void{$this->put(Subscription::class,(string)$s->id,['studio_owner_id'=>$s->user_id,'category'=>'main','transaction_type'=>'plan_purchase','description'=>ucfirst($s->plan).' Plan Purchase','currency'=>$s->currency?:'INR','total_amount_minor'=>(int)round(((string)$s->amount)*100),'status'=>$s->status==='active'?'paid':$s->status,'payment_provider'=>'razorpay','provider_reference'=>$s->payment_id,'payment_method_summary'=>'Online Payment','safe_details'=>['plan'=>$s->plan,'billing_interval'=>$s->billing_cycle,'starts_at'=>$s->starts_at,'expires_at'=>$s->expires_at],'occurred_at'=>$s->created_at]);}
 public function order(RazorpayOrder$r):void{$this->put(RazorpayOrder::class,(string)$r->id,['studio_owner_id'=>$r->user_id,'category'=>'main','transaction_type'=>'payment_attempt','description'=>ucfirst($r->plan).' Plan Payment','currency'=>$r->currency,'total_amount_minor'=>$r->amount,'status'=>$r->status==='created'?'pending':$r->status,'payment_provider'=>'razorpay','provider_reference'=>$r->provider_order_id,'payment_method_summary'=>'Online Payment','safe_details'=>['plan'=>$r->plan,'billing_interval'=>$r->billing_cycle],'occurred_at'=>$r->created_at]);}
 public function topUp(WalletTopUp$t):void{$this->put(WalletTopUp::class,(string)$t->id,['studio_owner_id'=>$t->studio_owner_id,'category'=>'wallet','transaction_type'=>'wallet_top_up','description'=>'Wallet Top-up','currency'=>$t->currency,'subtotal_amount_minor'=>$t->base_amount_minor,'tax_amount_minor'=>$t->tax_amount_minor,'total_amount_minor'=>$t->total_amount_minor,'credit_units'=>$t->credit_units,'direction'=>'credit','status'=>$t->status,'payment_provider'=>$t->payment_provider,'provider_reference'=>$t->provider_payment_id?:$t->provider_order_id,'payment_method_summary'=>'Online Payment','occurred_at'=>$t->paid_at?:$t->created_at]);}
 public function ledger(WalletLedgerEntry$e):void{$debit=$e->direction==='debit';$this->put(WalletLedgerEntry::class,(string)$e->id,['studio_owner_id'=>$e->studio_owner_id,'category'=>'wallet','transaction_type'=>$debit?'wallet_debit':'wallet_credit','description'=>$e->description?:($debit?'Credits Used':'Credits Added'),'currency'=>$e->currency,'total_amount_minor'=>$e->money_amount_minor,'credit_units'=>$e->credit_units,'direction'=>$e->direction,'status'=>'completed','provider_reference'=>$e->reference_id,'payment_method_summary'=>'Wallet Credits','safe_details'=>['balance_after_units'=>$e->balance_after_units],'occurred_at'=>$e->occurred_at]);}
}
