<script setup>
import {Head,router,usePage} from '@inertiajs/vue3'
import {computed,nextTick,onBeforeUnmount,onMounted,ref,watch} from 'vue'
const props=defineProps({event:Object,photo:Object,viewer:Object}),preferences=usePage().props.preferences||{}
const scale=ref(1),baseFitScale=ref(1),fitWidth=ref(0),fitHeight=ref(0),x=ref(0),y=ref(0),playing=ref(false),loop=ref(localStorage.getItem('lenspic:slideshow-loop')===null?Boolean(preferences.slideshow_loop):localStorage.getItem('lenspic:slideshow-loop')==='1'),controls=ref(true),infoOpen=ref(false),shareOpen=ref(false),deleteOpen=ref(false),busy=ref(false),sharing=ref(false),downloading=ref(false),message=ref(''),stage=ref(null),imageStage=ref(null),image=ref(null),imageReady=ref(false),interacting=ref(false),dragging=ref(false),animating=ref(false),tabVisible=ref(!document.hidden)
const shareData=ref(props.event.share)
let timer=null,hideTimer,gesture=null,lastTap=0,navigating=false,imageSafetyTimer=null,gestureAnimationTimer=null,fitObserver=null,closing=false,previousBodyOverflow='',fullscreenActive=false,suppressClick=false
const transform=computed(()=>`translate3d(${x.value}px,${y.value}px,0) scale(${scale.value})`)
const imageTransition=computed(()=>animating.value?'transform 180ms cubic-bezier(.22,.61,.36,1)':'none')
const imageCursor=computed(()=>dragging.value?'grabbing':scale.value>1?'move':'grab')
const size=computed(()=>props.photo.file_size?`${(props.photo.file_size/1048576).toFixed(1)} MB`:null)
function activity(){controls.value=true;clearTimeout(hideTimer);if(!infoOpen.value&&!shareOpen.value&&!deleteOpen.value)hideTimer=setTimeout(()=>controls.value=false,2800)}
const suspended=computed(()=>!tabVisible.value||!imageReady.value||interacting.value||infoOpen.value||shareOpen.value||deleteOpen.value)
function clearSlideshowTimer(){if(timer!==null){clearTimeout(timer);timer=null}}
function withIntent(url){if(!url)return null;const target=new URL(url,location.origin);if(playing.value)target.searchParams.set('slideshow','1');else target.searchParams.delete('slideshow');return target.href}
function navigate(url){if(navigating||closing)return;const target=withIntent(url);if(!target)return;navigating=true;clearSlideshowTimer();router.visit(target,{replace:true,preserveScroll:true,onError:()=>{navigating=false;playing.value=false;clearSlideshowTimer()}})}
function cancelGesture(){if(gesture?.target?.hasPointerCapture?.(gesture.pointerId))try{gesture.target.releasePointerCapture(gesture.pointerId)}catch{}gesture=null;dragging.value=false;interacting.value=false;animating.value=false;clearTimeout(gestureAnimationTimer);gestureAnimationTimer=null;document.documentElement.style.removeProperty('cursor')}
function cleanup(){playing.value=false;clearSlideshowTimer();clearTimeout(imageSafetyTimer);clearTimeout(hideTimer);cancelGesture();fitObserver?.disconnect();fitObserver=null;x.value=0;y.value=0;document.body.style.overflow=previousBodyOverflow;window.removeEventListener('keydown',keydown);window.removeEventListener('resize',measureFit);document.removeEventListener('visibilitychange',visibilityChanged);document.removeEventListener('fullscreenchange',fullscreenChanged)}
async function close(){if(closing)return;closing=true;cleanup();try{if(document.fullscreenElement)await document.exitFullscreen()}catch{}finally{let saved=null;try{saved=JSON.parse(sessionStorage.getItem(`lenspic:gallery:${props.event.id}`)||'null')}catch{}if(saved?.photoId&&history.length>1)history.back();else router.visit(props.event.gallery_url,{replace:true,preserveScroll:true,onError:()=>closing=false})}}
function zoom(delta){interacting.value=true;scale.value=Math.min(5,Math.max(1,scale.value+delta));if(scale.value===1){x.value=0;y.value=0}else nextTick(constrainPan);activity();setTimeout(()=>interacting.value=false,350)}
function reset(){cancelGesture();scale.value=1;x.value=0;y.value=0}
function scheduleSlideshow(){clearSlideshowTimer();if(!playing.value||suspended.value)return;const target=props.viewer.next_url||(loop.value?props.viewer.first_url:null);if(!target){playing.value=false;message.value='Slideshow finished';return}timer=setTimeout(()=>{timer=null;navigate(target)},Math.max(2,Math.min(20,Number(preferences.slideshow_interval||5)))*1000)}
function toggleSlideshow(){playing.value=!playing.value;scheduleSlideshow()}
function measureFit(resetPosition=false){if(!imageStage.value||!image.value?.naturalWidth||!image.value?.naturalHeight)return;const availableWidth=imageStage.value.clientWidth,availableHeight=imageStage.value.clientHeight,widthScale=availableWidth/image.value.naturalWidth,heightScale=availableHeight/image.value.naturalHeight,nextFit=Math.min(widthScale,heightScale);baseFitScale.value=nextFit;fitWidth.value=Math.max(1,Math.round(image.value.naturalWidth*nextFit));fitHeight.value=Math.max(1,Math.round(image.value.naturalHeight*nextFit));if(resetPosition||scale.value===1){x.value=0;y.value=0}else nextTick(constrainPan)}
function imageLoaded(){clearTimeout(imageSafetyTimer);measureFit(true);imageReady.value=true;scheduleSlideshow()}
function imageFailed(){clearTimeout(imageSafetyTimer);imageReady.value=true;scheduleSlideshow()}
async function favourite(){if(busy.value)return;const was=props.photo.liked,count=props.photo.likes_count;props.photo.liked=!was;props.photo.likes_count=Math.max(0,count+(props.photo.liked?1:-1));busy.value=true;try{const response=await fetch(`/groups/${props.event.id}/photos/${props.photo.id}/favourite`,{method:props.photo.liked?'POST':'DELETE',headers:{Accept:'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content}});if(!response.ok)throw new Error();const data=await response.json();props.photo.liked=data.is_favourite;props.photo.likes_count=data.favourites_count;message.value=data.message}catch{props.photo.liked=was;props.photo.likes_count=count;message.value='Could not update favourites.'}finally{busy.value=false;setTimeout(()=>message.value='',2200)}}
function groupShareText(){const share=shareData.value,lines=[`View “${props.event.name}” on LensPic.`,'',`Open Group:\n${share.url}`];if(share.access_code)lines.push('',`Access code: ${share.access_code}`);if(share.expires_at)lines.push(`Expires: ${new Date(share.expires_at).toLocaleString()}`);return lines.join('\n')}
function shareFailureMessage(error){if(error?.status===401||error?.status===403)return'You do not have permission to share this Group.';if(error?.status===404)return'The Group no longer exists.';if(error?.status===409)return'Group sharing is currently disabled.';if(error?.status===419)return'Your session expired. Refresh the page and try again.';return'The invitation link could not be created. Please try again.'}
async function authorizedGroupShare(){if(shareData.value?.url)return shareData.value;if(!shareData.value?.endpoint){const error=new Error('Sharing is unavailable.');error.status=403;throw error}const response=await fetch(shareData.value.endpoint,{method:'POST',credentials:'same-origin',headers:{Accept:'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content}});if(!response.ok){const error=new Error('Share request failed');error.status=response.status;throw error}shareData.value=await response.json();return shareData.value}
async function shareCurrentGroup(){if(sharing.value||!props.event.can_share_group)return;sharing.value=true;activity();try{const authorized=await authorizedGroupShare(),data={title:props.event.name,text:`View ${props.event.name} on LensPic`,url:authorized.url};if(!navigator.share){shareOpen.value=true;return}try{await navigator.share(data);message.value='Group shared.'}catch(error){if(error?.name!=='AbortError')message.value='The Group could not be shared.'}}catch(error){message.value=shareFailureMessage(error)}finally{sharing.value=false;setTimeout(()=>message.value='',2600)}}
async function copyLink(){try{await navigator.clipboard.writeText(shareData.value.url);message.value='Group link copied.';shareOpen.value=false}catch{message.value='Select and copy the Group link below.'}finally{setTimeout(()=>message.value='',2600)}}
function shareWhatsApp(){const anchor=document.createElement('a');anchor.href=`https://wa.me/?text=${encodeURIComponent(groupShareText())}`;anchor.target='_blank';anchor.rel='noopener noreferrer';anchor.click()}
function downloadCurrentPhoto(){if(downloading.value||!props.photo.download_url)return;const downloadUrl=props.photo.download_url,filename=(props.photo.original_filename||`lenspic-photo-${props.photo.id}.jpg`).replace(/[\\/]/g,'-'),anchor=document.createElement('a');downloading.value=true;anchor.href=downloadUrl;anchor.download=filename;anchor.hidden=true;document.body.appendChild(anchor);anchor.click();anchor.remove();message.value='Download started';setTimeout(()=>{downloading.value=false;message.value=''},1200)}
async function remove(){busy.value=true;try{const response=await fetch(`/groups/${props.event.id}/photos/${props.photo.id}`,{method:'DELETE',headers:{Accept:'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content}});if(!response.ok)throw new Error();router.visit(props.viewer.next_url||props.viewer.previous_url||props.event.gallery_url)}catch{message.value='Could not delete this photo.';deleteOpen.value=false}finally{busy.value=false}}
async function fullscreen(){try{document.fullscreenElement?await document.exitFullscreen():await stage.value?.requestFullscreen()}catch{message.value='Fullscreen is unavailable.'}}
function keydown(e){if(e.key==='Tab'){const nodes=[...stage.value.querySelectorAll('button:not([disabled]),a[href],input:not([disabled]),[tabindex]:not([tabindex="-1"])')].filter(node=>node.offsetParent!==null);if(nodes.length){const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}return}if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;activity();if(e.key==='Escape'){e.preventDefault();close()}else if(e.key==='ArrowLeft')navigate(props.viewer.previous_url);else if(e.key==='ArrowRight')navigate(props.viewer.next_url);else if(['+','='].includes(e.key))zoom(.25);else if(e.key==='-')zoom(-.25);else if(e.key==='0')reset();else if(e.key===' '){e.preventDefault();toggleSlideshow()}else if(e.key.toLowerCase()==='f'&&props.event.favourites_enabled)favourite();else if(e.key.toLowerCase()==='d'&&props.photo.download_url){e.preventDefault();downloadCurrentPhoto()}}
function wheel(e){e.preventDefault();zoom(e.deltaY<0?.2:-.2)}
function panBounds(){if(!imageStage.value||!fitWidth.value||!fitHeight.value)return{x:0,y:0};const viewerWidth=imageStage.value.clientWidth,viewerHeight=imageStage.value.clientHeight,scaledWidth=fitWidth.value*scale.value,scaledHeight=fitHeight.value*scale.value;return{x:scale.value>1?Math.abs(viewerWidth-scaledWidth)/2:0,y:Math.abs(viewerHeight-scaledHeight)/2}}
function clamp(value,min,max){return Math.min(max,Math.max(min,value))}
function constrainPan(){const bounds=panBounds();x.value=scale.value>1?clamp(x.value,-bounds.x,bounds.x):0;y.value=clamp(y.value,-bounds.y,bounds.y)}
function resist(value,bound){if(value>bound)return bound+(value-bound)*.2;if(value< -bound)return-bound+(value+bound)*.2;return value}
function pointerDown(e){if(e.button!==undefined&&e.button!==0)return;if(navigating||animating.value||!imageReady.value)return;interacting.value=true;dragging.value=false;clearSlideshowTimer();gesture={pointerId:e.pointerId,target:e.currentTarget,startX:e.clientX,startY:e.clientY,lastX:e.clientX,lastTime:performance.now(),velocityX:0,originX:x.value,originY:y.value,direction:null,moved:false};e.currentTarget.setPointerCapture?.(e.pointerId)}
function pointerMove(e){if(!gesture||gesture.pointerId!==e.pointerId)return;const dx=e.clientX-gesture.startX,dy=e.clientY-gesture.startY,distance=Math.hypot(dx,dy);gesture.moved=distance>4;if(!gesture.direction&&distance>=6)gesture.direction=Math.abs(dx)>Math.abs(dy)*1.15?'horizontal':Math.abs(dy)>Math.abs(dx)*1.15?'vertical':null;if(!gesture.direction)return;dragging.value=true;document.documentElement.style.cursor='grabbing';const now=performance.now(),elapsed=Math.max(1,now-gesture.lastTime);gesture.velocityX=(e.clientX-gesture.lastX)/elapsed;gesture.lastX=e.clientX;gesture.lastTime=now;e.preventDefault();const bounds=panBounds();if(gesture.direction==='vertical'){y.value=resist(gesture.originY+dy,bounds.y);return}if(scale.value>1){x.value=resist(gesture.originX+dx,bounds.x)}else{const available=dx>0?Boolean(props.viewer.previous_url):Boolean(props.viewer.next_url);x.value=available?dx:dx*.22}}
function settle(targetX,targetY,callback){animating.value=true;x.value=targetX;y.value=targetY;gestureAnimationTimer=setTimeout(()=>{gestureAnimationTimer=null;animating.value=false;callback?.()},window.matchMedia('(prefers-reduced-motion: reduce)').matches?0:180)}
function pointerUp(e){if(!gesture||gesture.pointerId!==e.pointerId)return;const state=gesture,dx=e.clientX-state.startX;gesture=null;if(state.target?.hasPointerCapture?.(state.pointerId))try{state.target.releasePointerCapture(state.pointerId)}catch{}dragging.value=false;document.documentElement.style.removeProperty('cursor');suppressClick=state.moved;const bounds=panBounds(),validY=clamp(y.value,-bounds.y,bounds.y);if(state.direction==='vertical'){if(validY!==y.value)settle(x.value,validY,()=>{interacting.value=false;scheduleSlideshow()});else{interacting.value=false;scheduleSlideshow()}return}if(scale.value>1){const validX=clamp(x.value,-bounds.x,bounds.x);if(validX!==x.value)settle(validX,validY,()=>{interacting.value=false;scheduleSlideshow()});else{interacting.value=false;scheduleSlideshow()}return}const width=stage.value?.clientWidth||window.innerWidth,threshold=width*.22,fast=Math.abs(state.velocityX)>=.55&&Math.abs(dx)>=24,target=dx>0?props.viewer.previous_url:props.viewer.next_url,shouldNavigate=state.direction==='horizontal'&&Boolean(target)&&(Math.abs(dx)>=threshold||fast);if(shouldNavigate){settle(dx>0?width:-width,y.value,()=>{x.value=0;y.value=0;interacting.value=false;navigate(target)})}else{settle(0,validY,()=>{interacting.value=false;scheduleSlideshow()})}}
function pointerCancel(e){if(!gesture||gesture.pointerId!==e.pointerId)return;gesture=null;dragging.value=false;document.documentElement.style.removeProperty('cursor');const bounds=panBounds();settle(scale.value>1?clamp(x.value,-bounds.x,bounds.x):0,clamp(y.value,-bounds.y,bounds.y),()=>{interacting.value=false;scheduleSlideshow()})}
function tap(){if(suppressClick){suppressClick=false;return}const now=Date.now();if(now-lastTap<300)scale.value>1?reset():zoom(1);else controls.value=!controls.value;lastTap=now}
function visibilityChanged(){tabVisible.value=!document.hidden;scheduleSlideshow()}
function fullscreenChanged(){fullscreenActive=Boolean(document.fullscreenElement);nextTick(()=>measureFit(scale.value===1))}
watch([playing,suspended,loop],()=>{localStorage.setItem('lenspic:slideshow-loop',loop.value?'1':'0');scheduleSlideshow()})
watch(()=>props.photo.id,()=>{clearSlideshowTimer();imageReady.value=false;fitWidth.value=0;fitHeight.value=0;reset();navigating=false;nextTick(()=>image.value?.focus())})
onMounted(()=>{playing.value=new URLSearchParams(location.search).get('slideshow')==='1';previousBodyOverflow=document.body.style.overflow;document.body.style.overflow='hidden';window.addEventListener('keydown',keydown);window.addEventListener('resize',measureFit);document.addEventListener('visibilitychange',visibilityChanged);document.addEventListener('fullscreenchange',fullscreenChanged);if(window.ResizeObserver){fitObserver=new ResizeObserver(()=>measureFit(scale.value===1));if(imageStage.value)fitObserver.observe(imageStage.value)}activity();nextTick(()=>image.value?.focus());imageSafetyTimer=setTimeout(imageFailed,10000)})
onBeforeUnmount(cleanup)
</script>
<template><div ref="stage" class="fixed inset-0 z-[100] select-none overflow-hidden bg-black text-white" role="dialog" aria-modal="true" aria-label="Photo viewer" @mousemove="activity">
<Head :title="photo.original_filename"/><p class="sr-only" aria-live="polite">Photo {{viewer.position}} of {{viewer.total}}</p>
<header class="viewer-top-left" aria-label="Viewer navigation"><button type="button" class="viewer-control" aria-label="Back to gallery" title="Back to gallery" @pointerdown.stop @click.stop.prevent="close"><span aria-hidden="true">←</span></button><div class="viewer-counter"><p class="font-semibold">{{viewer.position}} / {{viewer.total}}</p><p class="max-w-[34vw] truncate text-xs text-white/65">{{event.name}}</p></div></header>
<main ref="imageStage" class="viewer-image-stage" @wheel="wheel" @pointerdown="pointerDown" @pointermove="pointerMove" @pointerup="pointerUp" @pointercancel="pointerCancel" @lostpointercapture="pointerCancel"><img ref="image" :src="photo.url" :alt="photo.caption||photo.original_filename" draggable="false" tabindex="0" class="touch-none object-contain will-change-transform" :style="{width:fitWidth?`${fitWidth}px`:'auto',height:fitHeight?`${fitHeight}px`:'auto',maxWidth:'100%',maxHeight:'100%',transform,transition:imageTransition,cursor:imageCursor,visibility:imageReady?'visible':'hidden'}" @dragstart.prevent @load="imageLoaded" @error="imageFailed" @dblclick="scale>1?reset():zoom(1)" @click.stop="tap"></main>
<div v-if="viewer.previous_url" class="viewer-nav-zone viewer-nav-zone--previous"><button type="button" class="viewer-nav" aria-label="Previous photo" title="Previous photo" @pointerdown.stop @click.stop.prevent="navigate(viewer.previous_url)"><span aria-hidden="true">‹</span></button></div><div v-if="viewer.next_url" class="viewer-nav-zone viewer-nav-zone--next"><button type="button" class="viewer-nav" aria-label="Next photo" title="Next photo" @pointerdown.stop @click.stop.prevent="navigate(viewer.next_url)"><span aria-hidden="true">›</span></button></div>
<aside :class="['viewer-tools viewer-tools--top hidden transition-opacity sm:flex',controls?'opacity-100':'pointer-events-none opacity-0']" aria-label="View controls"><button type="button" class="viewer-control" :aria-label="playing?'Pause slideshow':'Start slideshow'" :aria-pressed="playing" :title="playing?'Pause slideshow':'Start slideshow'" @pointerdown.stop @click.stop="toggleSlideshow">{{playing?'Ⅱ':'▶'}}</button><button type="button" class="viewer-control" aria-label="Zoom in" title="Zoom in" @pointerdown.stop @click.stop="zoom(.25)">＋</button><button type="button" class="viewer-control" aria-label="Zoom out" title="Zoom out" @pointerdown.stop @click.stop="zoom(-.25)">−</button><button type="button" class="viewer-control text-xs" aria-label="Reset view" title="Reset view" @pointerdown.stop @click.stop="reset">1:1</button><button type="button" class="viewer-control" aria-label="Enter fullscreen" title="Enter fullscreen" @pointerdown.stop @click.stop="fullscreen">⛶</button></aside>
<aside :class="['viewer-tools viewer-tools--bottom hidden transition-opacity sm:flex',controls?'opacity-100':'pointer-events-none opacity-0']" aria-label="Photo actions"><button v-if="photo.download_url" type="button" class="viewer-control" aria-label="Download photo" title="Download photo" :disabled="downloading" @pointerdown.stop @click.stop.prevent="downloadCurrentPhoto"><svg aria-hidden="true" viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><path d="m7 10 5 5 5-5"/><path d="M12 15V3"/></svg></button><button v-if="event.can_share_group" type="button" class="viewer-control" aria-label="Share Group" title="Share Group" :disabled="sharing" @pointerdown.stop @click.stop="shareCurrentGroup"><span v-if="sharing">…</span><svg v-else aria-hidden="true" viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><path d="m8.6 10.5 6.8-4"/><path d="m8.6 13.5 6.8 4"/></svg></button><button v-if="event.favourites_enabled" type="button" :class="['viewer-control',photo.liked?'text-rose-400':'']" :aria-label="photo.liked?'Remove from favourites':'Add to favourites'" :title="photo.liked?'Remove from favourites':'Add to favourites'" :aria-pressed="photo.liked" @pointerdown.stop @click.stop="favourite">{{photo.liked?'♥':'♡'}}</button><button type="button" class="viewer-control" aria-label="Photo settings" title="Photo settings" @pointerdown.stop @click.stop="infoOpen=!infoOpen"><svg aria-hidden="true" viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.38a2 2 0 0 0-.73-2.73l-.15-.09a2 2 0 0 1-1-1.74v-.51a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z"/><circle cx="12" cy="12" r="3"/></svg></button><button v-if="photo.can_delete" type="button" class="viewer-control text-rose-300" aria-label="Delete photo" title="Delete photo" @pointerdown.stop @click.stop="deleteOpen=true"><svg aria-hidden="true" viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 6h18"/><path d="M8 6V4h8v2"/><path d="M19 6l-1 14H6L5 6"/><path d="M10 11v5"/><path d="M14 11v5"/></svg></button></aside>
<footer :class="['absolute inset-x-0 bottom-0 z-30 bg-gradient-to-t from-black/85 to-transparent px-3 pb-[max(12px,env(safe-area-inset-bottom))] pt-10 transition-opacity',controls?'opacity-100':'pointer-events-none opacity-0']"><p class="truncate text-center text-sm">{{photo.original_filename}}</p><div class="mt-2 flex justify-center gap-1 sm:hidden"><button type="button" class="viewer-button" :aria-pressed="playing" aria-label="Toggle slideshow" @click="toggleSlideshow">{{playing?'Ⅱ':'▶'}}</button><button type="button" class="viewer-button" aria-label="Zoom in" @click="zoom(.5)">＋</button><button v-if="photo.download_url" type="button" class="viewer-button" aria-label="Download photo" title="Download photo" :disabled="downloading" @pointerdown.stop @click.stop.prevent="downloadCurrentPhoto"><svg aria-hidden="true" viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><path d="m7 10 5 5 5-5"/><path d="M12 15V3"/></svg></button><button v-if="event.can_share_group" type="button" class="viewer-button" aria-label="Share Group" title="Share Group" :disabled="sharing" @pointerdown.stop @click.stop="shareCurrentGroup"><span v-if="sharing">…</span><svg v-else aria-hidden="true" viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><path d="m8.6 10.5 6.8-4"/><path d="m8.6 13.5 6.8 4"/></svg></button><button v-if="event.favourites_enabled" type="button" class="viewer-button" :aria-pressed="photo.liked" aria-label="Toggle favourite" @click="favourite">{{photo.liked?'♥':'♡'}}</button><button type="button" class="viewer-button" aria-label="Photo settings" title="Photo settings" @pointerdown.stop @click.stop="infoOpen=!infoOpen"><svg aria-hidden="true" viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.83 2.83-.06-.06A1.7 1.7 0 0 0 15 19.4a1.7 1.7 0 0 0-1 .6 1.7 1.7 0 0 0-.4 1.1V21h-4v-.09A1.7 1.7 0 0 0 8.6 19.4a1.7 1.7 0 0 0-1.88.34l-.06.06-2.83-2.83.06-.06A1.7 1.7 0 0 0 4.6 15a1.7 1.7 0 0 0-1.6-1H3v-4h.09A1.7 1.7 0 0 0 4.6 9a1.7 1.7 0 0 0-.34-1.88l-.06-.06 2.83-2.83.06.06A1.7 1.7 0 0 0 9 4.6a1.7 1.7 0 0 0 1-.6 1.7 1.7 0 0 0 .4-1.1V3h4v.09A1.7 1.7 0 0 0 15.4 4.6a1.7 1.7 0 0 0 1.88-.34l.06-.06 2.83 2.83-.06.06A1.7 1.7 0 0 0 19.4 9a1.7 1.7 0 0 0 1.6 1h.09v4H21a1.7 1.7 0 0 0-1.6 1z"/></svg></button></div></footer>
<section v-if="infoOpen" class="absolute bottom-20 right-3 z-40 w-[min(22rem,calc(100vw-24px))] bg-zinc-900/95 p-5 shadow-2xl" aria-label="Photo information"><button class="float-right p-2" aria-label="Close information" @click="infoOpen=false">×</button><h2 class="font-semibold">Photo details</h2><dl class="mt-4 grid grid-cols-[auto_1fr] gap-x-4 gap-y-2 text-sm"><dt class="text-white/55">Filename</dt><dd class="truncate">{{photo.original_filename}}</dd><template v-if="photo.width"><dt class="text-white/55">Dimensions</dt><dd>{{photo.width}} × {{photo.height}}</dd></template><template v-if="size"><dt class="text-white/55">Size</dt><dd>{{size}}</dd></template><dt class="text-white/55">Uploaded by</dt><dd>{{photo.uploader||'LensPic participant'}}</dd><template v-if="photo.folder"><dt class="text-white/55">Folder</dt><dd>{{photo.folder}}</dd></template></dl><label class="mt-4 flex min-h-11 items-center gap-3 border-t border-white/10 pt-4 text-sm"><input v-model="loop" type="checkbox" class="h-5 w-5"> Loop slideshow</label><p v-if="photo.caption" class="mt-4 border-t border-white/10 pt-4 text-sm text-white/75">{{photo.caption}}</p></section>
<section v-if="shareOpen" class="viewer-panel" role="dialog" aria-label="Share Group"><h2 class="font-semibold">Share Group</h2><p class="mt-2 text-sm text-white/60">Treat this private Group link as an access credential. Share only with intended recipients. Manage expiry and revocation in Group invitation settings.</p><button type="button" class="mt-4 w-full bg-emerald-600 px-4 py-3 font-semibold text-white" @click="shareWhatsApp">Share on WhatsApp</button><button type="button" class="mt-2 w-full bg-white px-4 py-3 font-semibold text-black" @click="copyLink">Copy Group link</button><input :value="shareData.url" readonly class="mt-3 w-full select-all bg-black/30 px-3 py-2 text-xs text-white" aria-label="Group share URL"><button type="button" class="mt-2 w-full px-4 py-3" @click="shareOpen=false">Cancel</button></section>
<section v-if="deleteOpen" class="viewer-panel" role="alertdialog" aria-label="Delete photo confirmation"><h2 class="font-semibold">Delete this photo?</h2><p class="mt-2 text-sm text-white/60">This removes it from the gallery and all collections.</p><button class="mt-4 w-full bg-rose-600 px-4 py-3 font-semibold" :disabled="busy" @click="remove">{{busy?'Deleting…':'Delete photo'}}</button><button class="mt-2 w-full px-4 py-3" @click="deleteOpen=false">Cancel</button></section><p v-if="message" class="absolute bottom-24 left-1/2 z-50 -translate-x-1/2 bg-white px-4 py-3 text-sm font-semibold text-black" role="status">{{message}}</p>
</div></template>
<style scoped>
.viewer-image-stage{position:absolute;inset:0;z-index:10;display:grid;place-items:center;overflow:hidden;overscroll-behavior:none}
.viewer-top-left{position:absolute;left:max(10px,env(safe-area-inset-left));top:max(10px,env(safe-area-inset-top));z-index:40;display:flex;align-items:center;gap:8px;padding:4px;border-radius:12px;background:linear-gradient(90deg,rgb(0 0 0/.7),rgb(0 0 0/.18));pointer-events:auto}
.viewer-counter{padding-right:12px;font-size:14px;text-shadow:0 1px 4px #000}
.viewer-button,.viewer-control{display:grid;height:44px;width:44px;flex:0 0 44px;place-items:center;border-radius:10px;background:rgb(24 24 27/.62);color:white;font-size:20px;font-weight:700;text-shadow:0 1px 4px #000;backdrop-filter:blur(6px)}
.viewer-button:focus-visible,.viewer-control:focus-visible,.viewer-nav:focus-visible{outline:2px solid white;outline-offset:3px}
.viewer-button:hover,.viewer-control:hover{background:rgb(39 39 42/.9)}
.viewer-tools{position:absolute;right:max(10px,env(safe-area-inset-right));z-index:40;flex-direction:column;gap:5px;padding:4px;border-radius:12px;background:linear-gradient(270deg,rgb(0 0 0/.58),rgb(0 0 0/.12));pointer-events:auto}
.viewer-tools--top{top:calc(max(10px,env(safe-area-inset-top)) + 62px)}
.viewer-tools--bottom{bottom:calc(max(10px,env(safe-area-inset-bottom)) + 64px)}
.viewer-nav-zone{position:absolute;z-index:30;top:50%;transform:translateY(-50%);pointer-events:none}
.viewer-nav-zone--previous{left:max(10px,env(safe-area-inset-left))}.viewer-nav-zone--next{right:max(10px,env(safe-area-inset-right))}
.viewer-nav{display:grid;height:52px;width:52px;pointer-events:auto;place-items:center;border:1px solid rgb(255 255 255/.2);border-radius:10px;background:rgb(0 0 0/.38);color:white;font-size:42px;line-height:1;text-shadow:0 1px 5px #000;transition:background-color .15s,transform .15s}
.viewer-nav:hover{background:rgb(39 39 42/.78);transform:scale(1.04)}.viewer-nav:active{transform:scale(.96)}
.viewer-panel{position:absolute;left:50%;top:50%;z-index:50;width:min(22rem,calc(100vw - 24px));transform:translate(-50%,-50%);background:#18181b;padding:20px;box-shadow:0 20px 60px #000}
@media(prefers-reduced-motion:reduce){*{transition:none!important}}
@media(max-width:639px){.viewer-nav{height:48px;width:48px;font-size:38px}.viewer-nav-zone--previous{left:max(8px,env(safe-area-inset-left))}.viewer-nav-zone--next{right:max(8px,env(safe-area-inset-right))}}
</style>
