<?php
namespace Tests\Feature;
use App\Models\{Group,StudioTeamMembership,User};use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Support\Facades\Hash;use Illuminate\Support\Str;use Inertia\Testing\AssertableInertia as Assert;use Tests\TestCase;
class AnalyticsAccessModelTest extends TestCase{use RefreshDatabase;
 private function user(string$email,string$type='photographer',string$plan='essential'):User{return User::create(['name'=>Str::before($email,'@'),'email'=>$email,'password'=>Hash::make('password'),'status'=>'active','account_type'=>$type,'plan'=>$plan]);}
 public function test_photographer_plan_matrix_and_upgrade_response_are_server_enforced():void{foreach(['basic','standard']as$plan){$u=$this->user($plan.'@analytics.test','photographer',$plan);$this->actingAs($u)->getJson(route('analytics'))->assertStatus(402)->assertJsonPath('code','upgrade_required');}foreach(['essential','premium']as$plan){$u=$this->user($plan.'@analytics.test','photographer',$plan);$this->actingAs($u)->get(route('analytics'))->assertOk()->assertInertia(fn(Assert$p)=>$p->component('Analytics'));}}
 public function test_team_member_requires_explicit_permission_and_only_sees_assigned_groups():void{$owner=$this->user('owner@analytics.test');$assigned=Group::create(['name'=>'Assigned','creator_id'=>$owner->id]);Group::create(['name'=>'Hidden','creator_id'=>$owner->id]);$member=$this->user('team@analytics.test','user','free');$m=StudioTeamMembership::create(['uuid'=>(string)Str::uuid(),'studio_owner_id'=>$owner->id,'user_id'=>$member->id,'role'=>'editor','status'=>'active','permissions'=>['view_groups'],'assigned_group_ids'=>[$assigned->id]]);$this->actingAs($member)->get(route('analytics'))->assertForbidden();$m->update(['permissions'=>['view_groups','analytics.view_assigned']]);$this->get(route('analytics'))->assertOk()->assertInertia(fn(Assert$p)=>$p->has('groups',1)->where('groups.0.id',$assigned->id));$this->get(route('analytics.export'))->assertForbidden();}
 public function test_group_member_and_cross_account_filter_are_denied():void{$owner=$this->user('scope-owner@analytics.test');$own=Group::create(['name'=>'Own','creator_id'=>$owner->id]);$other=$this->user('other-owner@analytics.test');$foreign=Group::create(['name'=>'Foreign','creator_id'=>$other->id]);$participant=$this->user('participant@analytics.test','user','free');$own->members()->attach($participant->id,['role'=>'member','membership_status'=>'active','access_type'=>'full_access']);$this->actingAs($participant)->get(route('analytics'))->assertForbidden();$this->actingAs($owner)->getJson(route('analytics',['group_id'=>$foreign->id]))->assertUnprocessable();}
 public function test_export_is_scoped_audited_and_sanitizes_spreadsheet_formulas():void{$owner=$this->user('export@analytics.test');Group::create(['name'=>'=IMPORTXML("bad")','creator_id'=>$owner->id]);$response=$this->actingAs($owner)->get(route('analytics.export'))->assertOk();$this->assertStringContainsString("'=IMPORTXML",$response->streamedContent());$this->assertDatabaseHas('audit_logs',['actor_id'=>$owner->id,'action'=>'analytics.exported']);}
}
