<?php
namespace Tests\Feature;
use App\Models\{BiometricConsent,FaceMatchResult,FaceSearchSubject,Group,GroupAccessInvite,MediaAsset,MediaVariant,Photo,User};use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Support\Facades\{Hash,Storage};use Illuminate\Support\Str;use Inertia\Testing\AssertableInertia as Assert;use Tests\TestCase;
class ConnectedParticipantUiTest extends TestCase
{
    use RefreshDatabase;
    protected function setUp():void{parent::setUp();config(['media.disk'=>'private_local','face.provider'=>'fake','face.consent_version'=>'ui-v1']);Storage::fake('private_local');}
    private function user(string$e):User{return User::create(['name'=>'Participant','email'=>$e,'password'=>Hash::make('x'),'status'=>'active','onboarding_step'=>'completed','onboarding_completed_at'=>now()]);}
    private function event(User$o):Group{$g=Group::create(['name'=>'Private Wedding','creator_id'=>$o->id,'is_active'=>true,'face_recognition_enabled'=>true,'downloads_enabled'=>true]);$g->members()->attach($o->id,['role'=>'admin','membership_status'=>'active','access_type'=>'full_access']);return$g;}
    public function test_invitation_page_creates_event_bound_session_without_leaking_token_prop():void{$o=$this->user('owner-ui@test.local');$g=$this->event($o);$i=GroupAccessInvite::makeFor($g,GroupAccessInvite::PARTIAL,$o->id);$this->get(route('invitations.show',$i->invitation_token))->assertOk()->assertSessionHas('pending_invitation_group',$g->id)->assertInertia(fn(Assert$p)=>$p->component('Invitations/Show')->where('status','valid')->where('event.name',$g->name)->missing('token')->missing('event.invitation_token'));}
    public function test_invitation_states_are_distinct_and_unusable_invite_cannot_be_accepted():void{$o=$this->user('owner-state@test.local');$u=$this->user('participant-state@test.local');$g=$this->event($o);$i=GroupAccessInvite::makeFor($g,GroupAccessInvite::PARTIAL,$o->id);$i->update(['expires_at'=>now()->subMinute()]);$this->actingAs($u)->get(route('invitations.show',$i->invitation_token))->assertInertia(fn(Assert$p)=>$p->where('status','expired'));$this->post(route('invitations.accept',$i->invitation_token))->assertRedirect();$this->assertFalse($g->isMember($u));$this->postJson(route('biometric.consent',$g),['accepted'=>true,'privacy_notice_version'=>'ui-v1'])->assertForbidden();$i->update(['expires_at'=>null,'is_active'=>false,'revoked_at'=>now()]);$this->get(route('invitations.show',$i->invitation_token))->assertInertia(fn(Assert$p)=>$p->where('status','revoked'));}
    public function test_acceptance_is_bound_to_the_invited_event_and_expired_session_is_visible():void{$o=$this->user('owner-bound@test.local');$u=$this->user('participant-bound@test.local');$a=$this->event($o);$b=$this->event($o);$ia=GroupAccessInvite::makeFor($a,GroupAccessInvite::PARTIAL,$o->id);$ib=GroupAccessInvite::makeFor($b,GroupAccessInvite::PARTIAL,$o->id);$this->actingAs($u)->get(route('invitations.show',$ia->invitation_token));$response=$this->post(route('invitations.accept',$ib->invitation_token))->assertRedirect();$this->assertFalse($b->isMember($u));$this->get($response->headers->get('Location'))->assertInertia(fn(Assert$p)=>$p->where('status','session_expired')->where('event',null));}
    public function test_biometric_page_uses_current_purpose_and_version_and_requires_membership():void{$o=$this->user('owner-bio-ui@test.local');$u=$this->user('participant-bio-ui@test.local');$g=$this->event($o);$this->actingAs($u)->get(route('biometric.page',$g))->assertForbidden();$g->members()->attach($u->id,['role'=>'member','membership_status'=>'active','access_type'=>'partial_access']);$this->get(route('biometric.page',$g))->assertInertia(fn(Assert$p)=>$p->component('Biometric/ConsentSelfie')->where('consentVersion','ui-v1')->where('minorEnabled',false)->where('event.id',$g->id));$this->postJson(route('biometric.consent',$g),['accepted'=>true,'privacy_notice_version'=>'stale'])->assertUnprocessable();}
    public function test_my_photos_page_uses_authorized_media_routes_without_private_fields():void{$o=$this->user('owner-results@test.local');$u=$this->user('participant-results@test.local');$g=$this->event($o);$g->members()->attach($u->id,['role'=>'member','membership_status'=>'active','access_type'=>'full_access']);$c=BiometricConsent::create(['uuid'=>(string)Str::uuid(),'group_id'=>$g->id,'user_id'=>$u->id,'purpose'=>'event_photo_matching','privacy_notice_version'=>'ui-v1','state'=>'granted','granted_at'=>now()]);$s=FaceSearchSubject::create(['uuid'=>(string)Str::uuid(),'biometric_consent_id'=>$c->id,'group_id'=>$g->id,'user_id'=>$u->id,'storage_disk'=>'private_local','object_key'=>'deleted/'.$c->uuid,'checksum_sha256'=>str_repeat('a',64),'state'=>'completed','deletion_state'=>'completed','expires_at'=>now()->addHour()]);$p=Photo::create(['group_id'=>$g->id,'uploader_id'=>$o->id,'filename'=>'safe.jpg','original_filename'=>'safe.jpg','path'=>'legacy/safe.jpg','thumbnail_path'=>'legacy/thumb.jpg','file_size'=>4,'mime_type'=>'image/jpeg']);$a=MediaAsset::create(['uuid'=>(string)Str::uuid(),'photo_id'=>$p->id,'group_id'=>$g->id,'owner_id'=>$o->id,'uploader_id'=>$o->id,'storage_disk'=>'private_local','original_object_key'=>'media/private-secret.jpg','original_filename'=>'safe.jpg','mime_type'=>'image/jpeg','size_bytes'=>4,'checksum_sha256'=>str_repeat('b',64),'state'=>'completed']);MediaVariant::create(['media_asset_id'=>$a->id,'variant_type'=>'thumbnail','storage_disk'=>'private_local','object_key'=>'media/thumb.jpg','mime_type'=>'image/jpeg','size_bytes'=>4,'checksum_sha256'=>str_repeat('c',64),'state'=>'ready']);FaceMatchResult::create(['face_search_subject_id'=>$s->id,'media_asset_id'=>$a->id,'similarity'=>98,'review_state'=>'accepted']);$this->actingAs($u)->get(route('biometric.results-page',$s))->assertInertia(fn(Assert$x)=>$x->component('MyPhotos')->has('photos',1)->where('photos.0.photo_id',$p->id)->missing('photos.0.object_key')->missing('photos.0.provider_face_ref'));}
    public function test_connected_photo_operations_and_review_pages_enforce_event_authorization():void{$o=$this->user('owner-ops@test.local');$u=$this->user('member-ops@test.local');$other=$this->user('other-ops@test.local');$g=$this->event($o);$g->members()->attach($u->id,['role'=>'member','membership_status'=>'active','access_type'=>'full_access']);$p=Photo::create(['group_id'=>$g->id,'uploader_id'=>$o->id,'filename'=>'v.jpg','original_filename'=>'viewer.jpg','path'=>'legacy/v.jpg','file_size'=>4,'mime_type'=>'image/jpeg']);$this->actingAs($u)->get(route('photos.show',[$g,$p]))->assertInertia(fn(Assert$x)=>$x->component('Photos/Show')->where('event.id',$g->id)->where('photo.id',$p->id));$this->get(route('groups.operations',$g))->assertForbidden();$this->get(route('groups.face-reviews',$g))->assertForbidden();$this->actingAs($o)->get(route('groups.operations',$g))->assertInertia(fn(Assert$x)=>$x->component('Events/Operations')->where('event.id',$g->id));$this->get(route('groups.face-reviews',$g))->assertInertia(fn(Assert$x)=>$x->component('Events/Reviews')->where('event.id',$g->id));$this->actingAs($other)->get(route('photos.show',[$g,$p]))->assertForbidden();}
    public function test_event_edit_and_members_pages_are_manager_only():void{$o=$this->user('owner-manage@test.local');$u=$this->user('member-manage@test.local');$g=$this->event($o);$g->members()->attach($u->id,['role'=>'member','membership_status'=>'active','access_type'=>'full_access']);$this->actingAs($u)->get(route('groups.edit',$g))->assertForbidden();$this->get(route('groups.members',$g))->assertForbidden();$this->actingAs($o)->get(route('groups.edit',$g))->assertInertia(fn(Assert$x)=>$x->component('Events/Edit')->where('event.id',$g->id));$this->get(route('groups.members',$g))->assertInertia(fn(Assert$x)=>$x->component('Events/Members')->where('event.id',$g->id));}
}
