<?php
namespace Tests\Feature;
use App\Models\{SubscriptionEntitlementSnapshot,SubscriptionFeature,SubscriptionPlan,SubscriptionPlanAudit,SubscriptionPlanPrice,User};
use App\Services\Billing\{AccountEntitlements,PlanCatalog};
use Database\Seeders\SubscriptionCatalogSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Support\Facades\{Hash,Http};use Tests\TestCase;
class DatabaseSubscriptionManagementTest extends TestCase
{
 use RefreshDatabase;
 private function user(string$email,string$role='user'):User{return User::create(['name'=>'Test','email'=>$email,'password'=>Hash::make('x'),'status'=>'active','account_type'=>'photographer','role'=>$role,'plan'=>'basic']);}
 private function payload(SubscriptionPlan$p,array$changes=[]):array{$q=$p->currentPrice('quarterly');$y=$p->currentPrice('yearly');$features=SubscriptionFeature::where('category','!=','limits')->get()->mapWithKeys(function($f)use($p){$x=$p->features()->whereKey($f->id)->first()?->pivot;return[$f->id=>['included'=>(int)($x?->is_included??false),'is_addon'=>(int)($x?->is_addon??false),'addon_price'=>$x?->addon_price_paise?number_format($x->addon_price_paise/100,2,'.',''):'','display_label'=>$x?->display_label?:$f->name,'display_order'=>$x?->display_order??$f->display_order]];})->all();return array_replace_recursive(['name'=>$p->name,'short_description'=>$p->short_description,'rank'=>$p->rank,'display_order'=>$p->display_order,'is_active'=>1,'is_public'=>1,'is_recommended'=>0,'badge_text'=>'','badge_style'=>'','photo_storage_limit'=>$p->photo_storage_limit,'photo_reuse_limit'=>$p->photo_reuse_limit,'video_storage_mb'=>$p->video_storage_mb,'team_seat_limit'=>$p->team_seat_limit,'group_limit'=>$p->group_limit,'guest_limit'=>$p->guest_limit,'prices'=>['quarterly'=>number_format($q->base_amount_paise/100,2,'.',''),'yearly'=>number_format($y->base_amount_paise/100,2,'.','')],'comparison_prices'=>['quarterly'=>'','yearly'=>''],'razorpay_plan_ids'=>['quarterly'=>'','yearly'=>''],'gst_basis_points'=>1800,'features'=>$features],$changes);}
 public function test_seeded_database_catalog_is_idempotent_and_uses_integer_paise():void{$this->assertSame(4,SubscriptionPlan::where('is_public',true)->count());$this->assertSame(8,SubscriptionPlanPrice::count());$this->seed(SubscriptionCatalogSeeder::class);$this->assertSame(4,SubscriptionPlan::where('is_public',true)->count());$this->assertSame(8,SubscriptionPlanPrice::count());$this->assertSame(349000,SubscriptionPlan::where('code','basic')->first()->currentPrice('yearly')->base_amount_paise);}
 public function test_only_super_admin_can_manage_plans():void{$plan=SubscriptionPlan::where('code','basic')->first();$this->actingAs($this->user('normal@test.local'))->get(route('super-admin.plans.index'))->assertForbidden();$this->actingAs($this->user('admin@test.local','super_admin'))->get(route('super-admin.plans.index'))->assertOk();$this->get(route('super-admin.plans.edit',$plan))->assertOk();}
 public function test_price_change_is_versioned_audited_and_used_by_pages_and_checkout():void{$admin=$this->user('super@test.local','super_admin');$plan=SubscriptionPlan::where('code','basic')->first();$old=$plan->currentPrice('quarterly');$this->actingAs($admin)->put(route('super-admin.plans.update',$plan),$this->payload($plan,['prices'=>['quarterly'=>'1099.00']]))->assertSessionHasNoErrors();$this->assertFalse($old->fresh()->is_active);$this->assertSame(109900,$plan->fresh()->currentPrice('quarterly')->base_amount_paise);$this->assertDatabaseHas('subscription_plan_audits',['subscription_plan_id'=>$plan->id,'actor_id'=>$admin->id,'action'=>'plan_published']);$this->get(route('pricing'))->assertOk()->assertSee('1,099.00');Http::fake(['api.razorpay.com/v1/orders'=>Http::response(['id'=>'order_new_price'])]);config(['services.razorpay.key_id'=>'key','services.razorpay.key_secret'=>'secret']);$this->actingAs($this->user('buyer@test.local'))->postJson(route('billing.razorpay.order'),['plan'=>'basic','cycle'=>'quarterly','amount'=>1])->assertOk()->assertJsonPath('base_amount',109900)->assertJsonPath('amount',129682);}
 public function test_existing_snapshot_is_unchanged_and_new_access_uses_database_features():void{$user=$this->user('snapshot@test.local');$plan=SubscriptionPlan::where('code','basic')->first();$sub=$user->subscriptions()->create(['subscription_plan_id'=>$plan->id,'plan'=>'basic','plan_version'=>1,'starts_at'=>now(),'expires_at'=>now()->addYear(),'amount'=>4118.20,'currency'=>'INR','payment_id'=>'pay_snapshot','billing_cycle'=>'yearly','status'=>'active']);$snapshot=$sub->entitlementSnapshot()->create(['subscription_plan_id'=>$plan->id,'plan_code'=>'basic','plan_name'=>'Basic','plan_version'=>1,'billing_interval'=>'yearly','base_amount_paise'=>349000,'gst_amount_paise'=>62820,'total_amount_paise'=>411820,'currency'=>'INR','photo_limit'=>20000,'photo_reuse_limit'=>20000,'video_limit_mb'=>0,'team_seat_limit'=>0,'group_limit'=>10,'guest_limit'=>null,'features'=>['bulk_download'=>true],'addons'=>[],'starts_at'=>$sub->starts_at,'expires_at'=>$sub->expires_at]);$plan->update(['photo_storage_limit'=>999]);$this->assertSame(20000,app(AccountEntitlements::class)->integerLimit($user,'photo_storage'));$this->assertTrue(app(AccountEntitlements::class)->allows($user,'bulk_download'));$this->assertSame(20000,$snapshot->fresh()->photo_limit);}
 public function test_direct_feature_route_is_denied_and_addon_expiry_is_enforced():void{$basic=$this->user('basic-feature@test.local');$this->actingAs($basic)->get(route('analytics'))->assertRedirect(route('settings.subscription',['feature'=>'analytics']));$standard=$this->user('standard-addon@test.local');$standard->update(['plan'=>'standard']);$feature=SubscriptionFeature::where('code','watermark')->first();$this->assertFalse(app(AccountEntitlements::class)->allows($standard,'watermark'));$standard->subscriptionAddons()->create(['subscription_feature_id'=>$feature->id,'status'=>'active','base_amount_paise'=>100000,'gst_amount_paise'=>18000,'total_amount_paise'=>118000,'starts_at'=>now()->subDay(),'expires_at'=>now()->addDay()]);$this->assertTrue(app(AccountEntitlements::class)->allows($standard,'watermark'));$standard->subscriptionAddons()->update(['expires_at'=>now()->subMinute()]);$this->assertFalse(app(AccountEntitlements::class)->allows($standard,'watermark'));}
}
