<?php
namespace Tests\Feature;
use App\Models\{Group,StudioTeamMembership,User};
use App\Services\Branding\{FlipbookBrandingPresenter,FlipbookLogoStorage};
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\{Hash,Storage};
use Illuminate\Support\Str;
use Inertia\Testing\AssertableInertia as Assert;
use Mockery;
use RuntimeException;
use Tests\TestCase;
class FlipbookSettingsTest extends TestCase {
 use RefreshDatabase;
 protected function setUp():void{parent::setUp();config(['media.disk'=>'private_local']);Storage::fake('private_local');}
 private function user(string$email='owner@test.local',string$type='photographer'):User{return User::create(['name'=>'Studio Owner','email'=>$email,'password'=>Hash::make('password'),'status'=>'active','account_type'=>$type,'plan'=>'standard','meta'=>['studio_name'=>'Original Studio']]);}
 private function data(array$x=[]):array{return array_replace(['business_name'=>'Flipbook Studio','apply_to_portfolio'=>true,'remove_logo'=>false],$x);}
 public function test_full_page_loads_fallback_and_saved_authoritative_values():void{$owner=$this->user();$this->actingAs($owner)->get(route('settings.flipbook'))->assertInertia(fn(Assert$p)=>$p->component('Settings/Flipbook')->where('section','flipbook')->where('settings.business_name','Original Studio')->where('settings.apply_to_portfolio',false)->where('settings.has_logo',false));$owner->flipbookSetting()->create(['business_name'=>'Saved Name','apply_to_portfolio'=>true]);$this->get(route('settings.flipbook'))->assertInertia(fn(Assert$p)=>$p->where('settings.business_name','Saved Name')->where('settings.apply_to_portfolio',true));}
 public function test_business_name_is_trimmed_validated_and_isolated_per_studio():void{$owner=$this->user();$other=$this->user('other@test.local');$this->actingAs($owner)->put(route('settings.flipbook.update'),$this->data(['business_name'=>'  Moonlight   & Co.  ']))->assertSessionHas('success');$this->assertSame('Moonlight & Co.',$owner->flipbookSetting()->first()->business_name);$this->put(route('settings.flipbook.update'),$this->data(['business_name'=>str_repeat('a',151)]))->assertSessionHasErrors('business_name');$this->actingAs($other)->put(route('settings.flipbook.update'),$this->data(['business_name'=>'Other Studio']))->assertSessionHasNoErrors();$this->assertSame('Moonlight & Co.',$owner->flipbookSetting()->first()->business_name);}
 public function test_valid_logo_upload_private_delivery_no_change_replace_and_remove():void{$owner=$this->user();$this->actingAs($owner)->put(route('settings.flipbook.update'),$this->data(['logo'=>UploadedFile::fake()->image('logo.png',300,120)]))->assertSessionHasNoErrors();$setting=$owner->flipbookSetting()->firstOrFail();$first=$setting->logo_object_key;Storage::disk('private_local')->assertExists($first);Storage::disk('public')->assertMissing($first);$this->get(route('settings.flipbook.logo'))->assertOk()->assertHeader('Content-Type','image/png');$this->get(route('settings.flipbook'))->assertInertia(fn(Assert$p)=>$p->where('settings.logo_url',route('settings.flipbook.logo'))->missing('settings.logo_object_key'));
  $this->put(route('settings.flipbook.update'),$this->data(['business_name'=>'No Logo Change']))->assertSessionHasNoErrors();$this->assertSame($first,$setting->fresh()->logo_object_key);Storage::disk('private_local')->assertExists($first);
  $this->put(route('settings.flipbook.update'),$this->data(['logo'=>UploadedFile::fake()->image('new.jpg',300,120)]))->assertSessionHasNoErrors();$second=$setting->fresh()->logo_object_key;$this->assertNotSame($first,$second);Storage::disk('private_local')->assertMissing($first);Storage::disk('private_local')->assertExists($second);
  $this->put(route('settings.flipbook.update'),$this->data(['remove_logo'=>true]))->assertSessionHasNoErrors();Storage::disk('private_local')->assertMissing($second);$this->assertNull($setting->fresh()->logo_object_key);
 }
 public function test_oversize_unsupported_and_corrupted_images_are_rejected():void{$owner=$this->user();$this->actingAs($owner)->put(route('settings.flipbook.update'),$this->data(['logo'=>UploadedFile::fake()->create('large.png',2049,'image/png')]))->assertSessionHasErrors('logo');$this->put(route('settings.flipbook.update'),$this->data(['logo'=>UploadedFile::fake()->create('bad.svg',2,'image/svg+xml')]))->assertSessionHasErrors('logo');$path=tempnam(sys_get_temp_dir(),'bad-logo-');file_put_contents($path,'not-an-image');$bad=new UploadedFile($path,'renamed.png','image/png',null,true);$this->put(route('settings.flipbook.update'),$this->data(['logo'=>$bad]))->assertSessionHasErrors('logo');}
 public function test_failed_replacement_preserves_existing_logo():void{$owner=$this->user();$owner->flipbookSetting()->create(['business_name'=>'Existing','logo_disk'=>'private_local','logo_object_key'=>'branding/flipbooks/users/1/old.png','logo_mime_type'=>'image/png','logo_size_bytes'=>3]);Storage::disk('private_local')->put('branding/flipbooks/users/1/old.png','old');$mock=Mockery::mock(FlipbookLogoStorage::class);$mock->shouldReceive('store')->once()->andThrow(new RuntimeException('storage failed'));$this->app->instance(FlipbookLogoStorage::class,$mock);$this->actingAs($owner)->put(route('settings.flipbook.update'),$this->data(['logo'=>UploadedFile::fake()->image('new.png')]))->assertSessionHasErrors('logo');$this->assertSame('branding/flipbooks/users/1/old.png',$owner->flipbookSetting()->first()->logo_object_key);Storage::disk('private_local')->assertExists('branding/flipbooks/users/1/old.png');}
 public function test_portfolio_toggle_uses_effective_values_without_destroying_own_branding():void{$owner=$this->user();$owner->businessBranding()->create(['business_name'=>'Portfolio Name','logo_disk'=>'private_local','logo_object_key'=>'portfolio.png','logo_mime_type'=>'image/png','logo_size_bytes'=>1]);$owner->flipbookSetting()->create(['business_name'=>'Flipbook Name','apply_to_portfolio'=>false]);$presenter=app(FlipbookBrandingPresenter::class);$this->assertSame('Portfolio Name',$presenter->portfolio($owner->load(['businessBranding','flipbookSetting']))['business_name']);$owner->flipbookSetting()->update(['apply_to_portfolio'=>true]);$owner->unsetRelation('flipbookSetting');$this->assertSame('Flipbook Name',$presenter->portfolio($owner->load('flipbookSetting'))['business_name']);$owner->flipbookSetting()->update(['apply_to_portfolio'=>false]);$owner->unsetRelation('flipbookSetting');$this->assertSame('Portfolio Name',$presenter->portfolio($owner->load('flipbookSetting'))['business_name']);$this->assertDatabaseHas('business_brandings',['user_id'=>$owner->id,'business_name'=>'Portfolio Name','logo_object_key'=>'portfolio.png']);}
 public function test_owner_and_branding_admin_are_authorized_but_viewer_and_guests_are_blocked():void{$owner=$this->user();$admin=$this->user('admin@test.local','user');$viewer=$this->user('viewer@test.local','user');foreach([[$admin,'admin'],[$viewer,'viewer']]as[$u,$role])$owner->studioTeamMembers()->create(['uuid'=>(string)Str::uuid(),'user_id'=>$u->id,'role'=>$role,'status'=>'active']);$this->actingAs($admin)->get(route('settings.flipbook'))->assertOk();$this->actingAs($viewer)->get(route('settings.flipbook'))->assertForbidden();$this->actingAs($viewer)->put(route('settings.flipbook.update'),$this->data())->assertForbidden();auth()->logout();$this->get(route('settings.flipbook'))->assertRedirect(route('login'));}
 public function test_public_flipbook_uses_saved_branding_only_for_authorized_public_group():void{$owner=$this->user();$owner->flipbookSetting()->create(['business_name'=>'Public Flipbook','apply_to_portfolio'=>false]);$group=Group::create(['name'=>'Wedding Book','creator_id'=>$owner->id,'is_active'=>true,'anonymous_access_mode'=>'full']);$this->get(route('guest.flipbook',$group))->assertOk()->assertSee('Public Flipbook')->assertSee('Wedding Book');$group->update(['anonymous_access_mode'=>'disabled']);$this->get(route('guest.flipbook',$group))->assertNotFound();}
}
