<?php
namespace Tests\Feature;
use App\Models\{Group,User};use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Support\Facades\{Cache,Hash};use Illuminate\Support\Str;use Inertia\Testing\AssertableInertia as Assert;use Tests\TestCase;
class GroupWorkflowUiTest extends TestCase
{
 use RefreshDatabase;
 protected function setUp():void{parent::setUp();config(['cache.default'=>'array']);}
 private function user(string$email='group-owner@test.local',string$type='photographer'):User{return User::create(['name'=>'Owner','email'=>$email,'password'=>Hash::make('password'),'status'=>'active','account_type'=>$type,'plan'=>'pro']);}
 private function group(User$u,string$name='Wedding Group'):Group{$g=Group::create(['name'=>$name,'creator_id'=>$u->id,'privacy'=>'link_only']);$g->members()->attach($u->id,['role'=>'admin','membership_status'=>'active','access_type'=>'full_access']);return$g;}
 private function payload(array$overrides=[]):array{return array_merge(['name'=>'Aarav and Mira','event_type'=>'wedding','privacy'=>'link_only','location'=>'Mumbai','membership_limit'=>500,'access_options'=>['partial_access','full_access'],'submission_token'=>(string)Str::uuid()],$overrides);}
 public function test_groups_list_and_create_are_full_page_inertia_routes():void{$u=$this->user();$g=$this->group($u);$this->actingAs($u)->get(route('groups.index'))->assertInertia(fn(Assert$p)=>$p->component('Groups/Index')->has('groups',1)->where('groups.0.id',$g->id));$this->get(route('groups.create'))->assertInertia(fn(Assert$p)=>$p->component('Groups/Create'));}
 public function test_group_creation_is_validated_idempotent_and_redirects_to_workspace():void{$u=$this->user();$this->actingAs($u)->post(route('groups.store'),$this->payload(['name'=>'']))->assertSessionHasErrors('name');$payload=$this->payload();$first=$this->post(route('groups.store'),$payload)->assertRedirect();$group=Group::where('name','Aarav and Mira')->firstOrFail();$first->assertRedirect(route('groups.show',$group));$this->post(route('groups.store'),$payload)->assertRedirect(route('groups.show',$group));$this->assertSame(1,Group::where('name','Aarav and Mira')->count());}
 public function test_group_settings_are_full_page_persist_supported_fields_and_reject_other_owner():void{$owner=$this->user();$other=$this->user('other-group-owner@test.local');$group=$this->group($owner);$this->actingAs($owner)->get(route('groups.settings',$group))->assertInertia(fn(Assert$p)=>$p->component('Groups/Settings')->where('group.id',$group->id)->missing('group.share_token')->missing('group.invitation_token'));
  $this->put(route('groups.update',$group),['name'=>'Updated Group','privacy'=>'private','downloads_enabled'=>false,'face_recognition_enabled'=>true,'membership_status'=>'closed'])->assertRedirect();$group->refresh();$this->assertSame('Updated Group',$group->name);$this->assertSame('private',$group->privacy);$this->assertFalse($group->downloads_enabled);$this->assertTrue($group->face_recognition_enabled);$this->assertSame('closed',$group->membership_status);$this->actingAs($other)->put(route('groups.update',$group),['name'=>'Stolen'])->assertForbidden();}
 public function test_workspace_folder_invitation_favorites_and_old_event_aliases_are_group_scoped():void{$owner=$this->user();$other=$this->user('unrelated@test.local');$group=$this->group($owner);$this->actingAs($owner)->get(route('groups.show',$group))->assertInertia(fn(Assert$p)=>$p->component('Groups/Show')->where('group.id',$group->id));$this->get(route('folders.index',$group))->assertInertia(fn(Assert$p)=>$p->component('Groups/Folders')->where('group.id',$group->id));$this->get(route('groups.access-invites.index',$group))->assertInertia(fn(Assert$p)=>$p->component('Groups/Invitations')->where('group.id',$group->id));$this->get(route('groups.favorites',$group))->assertInertia(fn(Assert$p)=>$p->component('Groups/Favorites')->where('group.id',$group->id));$this->get('/events')->assertRedirect(route('groups.index'));$this->get('/events/'.$group->id)->assertRedirect(route('groups.show',$group));$this->actingAs($other)->get(route('groups.show',$group))->assertForbidden();$this->get(route('folders.index',$group))->assertForbidden();$this->get(route('groups.access-invites.index',$group))->assertForbidden();$this->get(route('groups.favorites',$group))->assertForbidden();}
 public function test_participant_cannot_open_group_management_surfaces():void{$owner=$this->user();$participant=$this->user('participant-group@test.local','user');$group=$this->group($owner);$group->members()->attach($participant->id,['role'=>'member','membership_status'=>'active','access_type'=>'full_access']);$this->actingAs($participant)->get(route('groups.settings',$group))->assertForbidden();$this->get(route('groups.operations',$group))->assertForbidden();$this->get(route('groups.face-reviews',$group))->assertForbidden();$this->get(route('groups.favorites',$group))->assertForbidden();}
 public function test_every_group_settings_section_has_a_direct_inertia_url():void{$owner=$this->user();$group=$this->group($owner);foreach(['general','participants','privacy','folders','design','downloads','branding','favourites']as$section)$this->actingAs($owner)->get(route('groups.settings.section',[$group,$section]))->assertOk()->assertInertia(fn(Assert$p)=>$p->component('Groups/Settings')->where('section',$section)->where('group.id',$group->id)->missing('group.share_token')->missing('group.invitation_token'));$this->get("/groups/{$group->id}/settings/not-real")->assertNotFound();}
 public function test_legacy_gallery_and_selfie_pages_redirect_to_connected_inertia_workflows():void{$owner=$this->user();$participant=$this->user('legacy-participant@test.local','user');$group=$this->group($owner);$group->update(['face_recognition_enabled'=>true]);$group->members()->attach($participant->id,['role'=>'member','membership_status'=>'active','access_type'=>'full_access']);$this->actingAs($owner)->get(route('photos.index',$group))->assertInertia(fn(Assert$p)=>$p->component('Groups/Show')->where('group.id',$group->id));$this->actingAs($participant)->get(route('face.show',$group))->assertRedirect(route('biometric.page',$group));$this->get(route('photos.mine',$group))->assertRedirect(route('biometric.page',$group));}
}
