<?php
namespace Tests\Feature;
use App\Models\{Folder,Group,MediaAsset,Photo,User};use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Support\Facades\{Cache,Hash};use Illuminate\Support\Str;use Inertia\Testing\AssertableInertia as Assert;use Tests\TestCase;
class GroupWorkflowUiTest extends TestCase
{
 use RefreshDatabase;
 protected function setUp():void{parent::setUp();config(['cache.default'=>'array']);}
 private function user(string$email='group-owner@test.local',string$type='photographer'):User{return User::create(['name'=>'Owner','email'=>$email,'password'=>Hash::make('password'),'status'=>'active','account_type'=>$type,'plan'=>'pro']);}
 private function group(User$u,string$name='Wedding Group'):Group{$g=Group::create(['name'=>$name,'creator_id'=>$u->id,'privacy'=>'link_only']);$g->members()->attach($u->id,['role'=>'admin','membership_status'=>'active','access_type'=>'full_access']);return$g;}
 private function payload(array$overrides=[]):array{return array_merge(['name'=>'Aarav and Mira','event_type'=>'wedding','privacy'=>'link_only','location'=>'Mumbai','membership_limit'=>500,'access_options'=>['partial_access','full_access'],'submission_token'=>(string)Str::uuid()],$overrides);}
 public function test_guest_cannot_access_group_creation():void{$this->get(route('groups.create'))->assertRedirect(route('login'));$this->post(route('groups.store'),$this->payload())->assertRedirect(route('login'));}
 public function test_photographer_and_studio_roles_can_open_full_page_group_creation():void{foreach(['photographer','studio']as$accountType){$u=$this->user(Str::uuid().'@test.local',$accountType);$this->actingAs($u)->get(route('groups.create'))->assertOk()->assertInertia(fn(Assert$p)=>$p->component('Groups/Create'));}$source=file_get_contents(resource_path('js/Pages/Groups/Create.vue'));$this->assertStringContainsString('<AppShell>',$source);$this->assertStringNotContainsString('UiModal',$source);$this->assertStringNotContainsString('role="dialog"',$source);}
 public function test_unauthorized_user_cannot_open_or_submit_group_creation():void{$u=$this->user('group-viewer@test.local','user');$this->actingAs($u)->get(route('groups.create'))->assertForbidden();$this->post(route('groups.store'),$this->payload())->assertForbidden();$this->assertDatabaseCount('groups',0);}
 public function test_legacy_admin_flag_and_existing_group_ownership_retain_create_permission():void{$legacyAdmin=$this->user('legacy-admin@test.local','user');$legacyAdmin->forceFill(['account_type'=>null,'role'=>'user','is_admin'=>true])->save();$this->actingAs($legacyAdmin)->get(route('groups.create'))->assertInertia(fn(Assert$p)=>$p->component('Groups/Create'));$legacyOwner=$this->user('legacy-owner@test.local','user');$legacyOwner->forceFill(['account_type'=>null,'role'=>'user'])->save();$this->group($legacyOwner);$this->actingAs($legacyOwner)->get(route('groups.create'))->assertInertia(fn(Assert$p)=>$p->component('Groups/Create'));}
 public function test_group_creation_cannot_be_spoofed_into_another_studio():void{$studio=$this->user('studio-owner@test.local');$other=$this->user('other-studio@test.local');$this->actingAs($studio)->post(route('groups.store'),$this->payload(['creator_id'=>$other->id]))->assertRedirect();$group=Group::where('name','Aarav and Mira')->firstOrFail();$this->assertSame($studio->id,$group->creator_id);$this->actingAs($other)->put(route('groups.update',$group),['name'=>'Cross-tenant edit'])->assertForbidden();}
 public function test_group_validation_returns_to_full_create_page_with_inline_errors():void{$u=$this->user();$this->actingAs($u)->from(route('groups.create'))->post(route('groups.store'),$this->payload(['name'=>'']))->assertRedirect(route('groups.create'))->assertSessionHasErrors('name');$this->get(route('groups.create'))->assertInertia(fn(Assert$p)=>$p->component('Groups/Create')->has('errors.name'));}
 public function test_groups_list_and_create_are_full_page_inertia_routes():void{$u=$this->user();$g=$this->group($u);$this->actingAs($u)->get(route('groups.index'))->assertInertia(fn(Assert$p)=>$p->component('Groups/Index')->has('groups',1)->where('groups.0.id',$g->id));$this->get(route('groups.create'))->assertInertia(fn(Assert$p)=>$p->component('Groups/Create'));}
 public function test_group_creation_is_validated_idempotent_and_redirects_to_workspace():void{$u=$this->user();$this->actingAs($u)->post(route('groups.store'),$this->payload(['name'=>'']))->assertSessionHasErrors('name');$payload=$this->payload();$first=$this->post(route('groups.store'),$payload)->assertRedirect();$group=Group::where('name','Aarav and Mira')->firstOrFail();$first->assertRedirect(route('groups.show',$group));$this->post(route('groups.store'),$payload)->assertRedirect(route('groups.show',$group));$this->assertSame(1,Group::where('name','Aarav and Mira')->count());}
 public function test_group_settings_are_full_page_persist_supported_fields_and_reject_other_owner():void{$owner=$this->user();$other=$this->user('other-group-owner@test.local');$group=$this->group($owner);$this->actingAs($owner)->get(route('groups.settings',$group))->assertInertia(fn(Assert$p)=>$p->component('Groups/Settings')->where('group.id',$group->id)->missing('group.share_token')->missing('group.invitation_token'));
  $this->put(route('groups.update',$group),['name'=>'Updated Group','privacy'=>'private','downloads_enabled'=>false,'face_recognition_enabled'=>true,'membership_status'=>'closed'])->assertRedirect();$group->refresh();$this->assertSame('Updated Group',$group->name);$this->assertSame('private',$group->privacy);$this->assertFalse($group->downloads_enabled);$this->assertTrue($group->face_recognition_enabled);$this->assertSame('closed',$group->membership_status);$this->actingAs($other)->put(route('groups.update',$group),['name'=>'Stolen'])->assertForbidden();}
 public function test_workspace_folder_invitation_favorites_and_old_event_aliases_are_group_scoped():void{$owner=$this->user();$other=$this->user('unrelated@test.local');$group=$this->group($owner);$this->actingAs($owner)->get(route('groups.show',$group))->assertInertia(fn(Assert$p)=>$p->component('Groups/Show')->where('group.id',$group->id));$this->get(route('folders.index',$group))->assertInertia(fn(Assert$p)=>$p->component('Groups/Folders')->where('group.id',$group->id));$this->get(route('groups.access-invites.index',$group))->assertInertia(fn(Assert$p)=>$p->component('Groups/Invitations')->where('group.id',$group->id));$this->get(route('groups.favorites',$group))->assertInertia(fn(Assert$p)=>$p->component('Groups/Favorites')->where('group.id',$group->id));$this->get('/events')->assertRedirect(route('groups.index'));$this->get('/events/'.$group->id)->assertRedirect(route('groups.show',$group));$this->actingAs($other)->get(route('groups.show',$group))->assertForbidden();$this->get(route('folders.index',$group))->assertForbidden();$this->get(route('groups.access-invites.index',$group))->assertForbidden();$this->get(route('groups.favorites',$group))->assertForbidden();}
 public function test_participant_cannot_open_group_management_surfaces():void{$owner=$this->user();$participant=$this->user('participant-group@test.local','user');$group=$this->group($owner);$group->members()->attach($participant->id,['role'=>'member','membership_status'=>'active','access_type'=>'full_access']);$this->actingAs($participant)->get(route('groups.settings',$group))->assertForbidden();$this->get(route('groups.operations',$group))->assertForbidden();$this->get(route('groups.face-reviews',$group))->assertForbidden();$this->get(route('groups.favorites',$group))->assertForbidden();}
 public function test_every_group_settings_section_has_a_direct_inertia_url():void{$owner=$this->user();$group=$this->group($owner);foreach(['general','participants','privacy','folders','design','downloads','branding','favourites']as$section)$this->actingAs($owner)->get(route('groups.settings.section',[$group,$section]))->assertOk()->assertInertia(fn(Assert$p)=>$p->component('Groups/Settings')->where('section',$section)->where('group.id',$group->id)->missing('group.share_token')->missing('group.invitation_token'));$this->get("/groups/{$group->id}/settings/not-real")->assertNotFound();}
 public function test_legacy_gallery_and_selfie_pages_redirect_to_connected_inertia_workflows():void{$owner=$this->user();$participant=$this->user('legacy-participant@test.local','user');$group=$this->group($owner);$group->update(['face_recognition_enabled'=>true]);$group->members()->attach($participant->id,['role'=>'member','membership_status'=>'active','access_type'=>'full_access']);$this->actingAs($owner)->get(route('photos.index',$group))->assertInertia(fn(Assert$p)=>$p->component('Groups/Show')->where('group.id',$group->id));$this->actingAs($participant)->get(route('face.show',$group))->assertRedirect(route('biometric.page',$group));$this->get(route('photos.mine',$group))->assertRedirect(route('biometric.page',$group));}
 public function test_gallery_route_preserves_folder_tab_and_returns_private_ratio_metadata():void{$owner=$this->user();$outsider=$this->user('gallery-outsider@test.local');$group=$this->group($owner);$folder=Folder::create(['group_id'=>$group->id,'name'=>'Portrait Studio','created_by'=>$owner->id]);$photo=Photo::create(['group_id'=>$group->id,'uploader_id'=>$owner->id,'folder_id'=>$folder->id,'filename'=>'portrait.jpg','original_filename'=>'portrait.jpg','path'=>'private/original.jpg','thumbnail_path'=>'private/thumb.jpg','file_size'=>100,'mime_type'=>'image/jpeg','width'=>800,'height'=>1200]);$asset=MediaAsset::create(['uuid'=>(string)Str::uuid(),'photo_id'=>$photo->id,'group_id'=>$group->id,'owner_id'=>$owner->id,'uploader_id'=>$owner->id,'storage_disk'=>'private_local','original_object_key'=>'private/original.jpg','original_filename'=>'portrait.jpg','mime_type'=>'image/jpeg','size_bytes'=>100,'checksum_sha256'=>str_repeat('a',64),'width'=>800,'height'=>1200,'state'=>'completed']);$this->actingAs($owner)->get(route('groups.gallery',[$group,'tab'=>'folder-'.$folder->id]))->assertInertia(fn(Assert$p)=>$p->component('Groups/Show')->where('activeTab','folder-'.$folder->id)->where('photos.data.0.width',800)->where('photos.data.0.height',1200)->where('photos.data.0.url',route('media.show',[$asset->uuid,'grid']))->missing('photos.data.0.object_key'));$this->actingAs($outsider)->get(route('groups.gallery',$group))->assertForbidden();}
}
