<?php
namespace Tests\Feature;use App\Models\{StudioTeamMembership,User};use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Support\Facades\{Hash,Storage};use Illuminate\Support\Str;use Inertia\Testing\AssertableInertia as Assert;use Tests\TestCase;
class PortfolioSettingsTest extends TestCase{use RefreshDatabase;protected function setUp():void{parent::setUp();config(['media.disk'=>'private_local','media.delivery_driver'=>'local']);Storage::fake('private_local');}private function user(string$e='owner@portfolio.test',string$t='photographer'):User{return User::create(['name'=>'Moonlight Studio','email'=>$e,'password'=>Hash::make('x'),'status'=>'active','account_type'=>$t,'plan'=>'standard']);}private function payload(array$x=[]):array{return array_replace(['name'=>'Moonlight Weddings','website_url'=>'moonlight.test','about_us'=>'Stories in light.','currency_code'=>'INR','status'=>'published','remove_cover'=>false,'image_ids'=>[],'services'=>[['id'=>null,'name'=>'Wedding Photography','price'=>'12000.00','enabled'=>true]],'show_payment_details'=>false,'upi_id'=>null,'upi_phone'=>null,'bank_name'=>null,'account_holder_name'=>null,'account_number'=>null,'account_type'=>null,'ifsc'=>null],$x);}
public function test_page_is_full_page_and_defaults_are_scoped():void{$u=$this->user();$this->actingAs($u)->get(route('settings.portfolio'))->assertOk()->assertInertia(fn(Assert$p)=>$p->component('Settings/Portfolio')->where('imageLimit',100)->has('settings.services',6)->where('settings.status','draft')->where('canManagePayments',true));$this->assertDatabaseHas('portfolios',['studio_owner_id'=>$u->id,'status'=>'draft']);}
public function test_one_save_persists_and_publication_controls_output():void{$u=$this->user();$this->actingAs($u)->put(route('settings.portfolio.update'),$this->payload(['status'=>'draft']))->assertSessionHas('success');$p=$u->portfolio()->first();$this->get(route('portfolio.show',$p))->assertNotFound();$this->put(route('settings.portfolio.update'),$this->payload())->assertSessionHasNoErrors();$this->get(route('portfolio.show',$p))->assertOk()->assertSee('Moonlight Weddings')->assertSee('Wedding Photography')->assertSee('INR 12,000.00');}
public function test_sensitive_payment_is_encrypted_hidden_and_visibility_is_explicit():void{$u=$this->user();$this->actingAs($u)->put(route('settings.portfolio.update'),$this->payload(['show_payment_details'=>false,'upi_id'=>'moonlight@okaxis','account_number'=>'0012345678','ifsc'=>'hdfc0001234']))->assertSessionHasNoErrors();$p=$u->portfolio()->first();$raw=\DB::table('portfolios')->where('id',$p->id)->first();$this->assertStringNotContainsString('0012345678',$raw->account_number);$this->assertStringNotContainsString('moonlight@okaxis',$raw->upi_id);$this->get(route('portfolio.show',$p))->assertDontSee('0012345678')->assertDontSee('moonlight@okaxis');$this->put(route('settings.portfolio.update'),$this->payload(['show_payment_details'=>true,'upi_id'=>'moonlight@okaxis','account_number'=>'','ifsc'=>'HDFC0001234']))->assertSessionHasNoErrors();$this->assertSame('0012345678',$p->fresh()->account_number);$this->get(route('portfolio.show',$p))->assertSee('0012345678')->assertSee('moonlight@okaxis');}
public function test_validation_and_image_limit_preserve_data():void{$u=$this->user();$this->actingAs($u)->from(route('settings.portfolio'))->put(route('settings.portfolio.update'),$this->payload(['website_url'=>'not a url','image_ids'=>range(1,101),'services'=>[['name'=>'Bad','price'=>-1,'enabled'=>true]],'ifsc'=>'BAD']))->assertRedirect(route('settings.portfolio'))->assertSessionHasErrors(['website_url','image_ids','services.0.price','ifsc'])->assertSessionHasInput('name','Moonlight Weddings');}
public function test_admin_can_manage_content_but_not_payments_and_viewer_is_blocked():void{$o=$this->user();$a=$this->user('admin@portfolio.test','user');$v=$this->user('viewer@portfolio.test','user');foreach([[$a,'admin'],[$v,'viewer']]as[$u,$role])$o->studioTeamMembers()->create(['uuid'=>(string)Str::uuid(),'user_id'=>$u->id,'role'=>$role,'status'=>'active']);$this->actingAs($a)->get(route('settings.portfolio'))->assertInertia(fn(Assert$p)=>$p->where('canManagePayments',false)->where('settings.upi_id',null));$this->actingAs($v)->get(route('settings.portfolio'))->assertForbidden();}
}
