<?php
namespace Tests\Feature;
use App\Models\{Group,MediaAsset,MediaVariant,Photo,User};use App\Services\Media\MediaVariantProcessor;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Support\Facades\{Hash,Storage};use Illuminate\Support\Str;use Tests\TestCase;
class ProfessionalImagePipelineTest extends TestCase{use RefreshDatabase;protected function setUp():void{parent::setUp();Storage::fake('private_local');config(['media.disk'=>'private_local','media.processing.version'=>2,'media.processing.profiles.standard'=>['max_edge'=>1000,'quality'=>92,'min_quality'=>85,'target_bytes'=>3000000],'media.processing.profiles.high_resolution'=>['max_edge'=>1400,'quality'=>95,'min_quality'=>90,'target_bytes'=>4000000]]);}
 private function asset(int$width,int$height,string$mode='standard',int$orientation=1):array{$user=User::create(['name'=>'Owner','email'=>Str::uuid().'@test.local','password'=>Hash::make('x'),'status'=>'active']);$group=Group::create(['name'=>'Gallery','creator_id'=>$user->id]);$photo=Photo::create(['group_id'=>$group->id,'uploader_id'=>$user->id,'filename'=>'source.jpg','original_filename'=>'source.jpg','path'=>'private']);$image=imagecreatetruecolor($width,$height);for($y=0;$y<$height;$y+=10){$colour=imagecolorallocate($image,$y%255,($y*3)%255,($y*7)%255);imagefilledrectangle($image,0,$y,$width-1,min($height-1,$y+9),$colour);}ob_start();imagejpeg($image,null,100);$bytes=(string)ob_get_clean();imagedestroy($image);$key='media/originals/groups/'.$group->id.'/source.jpg';Storage::disk('private_local')->put($key,$bytes);$asset=MediaAsset::create(['uuid'=>(string)Str::uuid(),'photo_id'=>$photo->id,'group_id'=>$group->id,'owner_id'=>$user->id,'uploader_id'=>$user->id,'storage_disk'=>'private_local','original_object_key'=>$key,'original_filename'=>'source.jpg','mime_type'=>'image/jpeg','quality_mode'=>$mode,'size_bytes'=>strlen($bytes),'original_upload_bytes'=>strlen($bytes),'checksum_sha256'=>hash('sha256',$bytes),'width'=>$width,'height'=>$height,'orientation'=>$orientation,'state'=>'queued']);MediaVariant::create(['media_asset_id'=>$asset->id,'variant_type'=>'original','storage_disk'=>'private_local','object_key'=>$key,'mime_type'=>'image/jpeg','size_bytes'=>strlen($bytes),'checksum_sha256'=>hash('sha256',$bytes),'width'=>$width,'height'=>$height,'state'=>'ready']);return[$asset,$bytes];}
 public function test_standard_keeps_private_original_and_generates_purpose_variants():void{[$asset,$source]=$this->asset(1600,800);app(MediaVariantProcessor::class)->process($asset);$this->assertSame($source,Storage::disk('private_local')->get($asset->original_object_key));$asset->refresh();$this->assertSame('standard',$asset->processing_profile);$this->assertSame(2,$asset->processing_version);foreach(['optimized','viewer','grid','thumbnail']as$type)$this->assertNotNull($asset->variant($type));$this->assertSame(1000,$asset->variant('optimized')->width);$this->assertSame(500,$asset->variant('optimized')->height);$this->assertGreaterThanOrEqual(85,$asset->variant('optimized')->encoder_quality);}
 public function test_portrait_long_edge_and_orientation_are_respected_without_upscale():void{[$portrait]=$this->asset(800,1600);app(MediaVariantProcessor::class)->process($portrait);$this->assertSame(500,$portrait->variant('optimized')->width);$this->assertSame(1000,$portrait->variant('optimized')->height);[$small]=$this->asset(600,400);app(MediaVariantProcessor::class)->process($small);$this->assertSame(600,$small->variant('optimized')->width);$this->assertSame(400,$small->variant('optimized')->height);[$rotated]=$this->asset(800,1200,'standard',6);app(MediaVariantProcessor::class)->process($rotated);$this->assertSame(1000,$rotated->variant('optimized')->width);$this->assertSame(667,$rotated->variant('optimized')->height);}
 public function test_high_resolution_profile_and_retry_are_idempotent():void{[$asset]=$this->asset(1800,900,'high_resolution');$processor=app(MediaVariantProcessor::class);$processor->process($asset);$count=$asset->variants()->count();$bytes=(int)$asset->owner_id;$this->assertSame(1400,$asset->variant('optimized')->width);$this->assertGreaterThanOrEqual(90,$asset->variant('optimized')->encoder_quality);$processor->process($asset->fresh());$this->assertSame($count,$asset->variants()->count());$this->assertSame(5,$count);}
 public function test_viewer_and_grid_routes_are_authorized_private_delivery():void{[$asset]=$this->asset(1200,800);app(MediaVariantProcessor::class)->process($asset);$owner=User::findOrFail($asset->owner_id);$this->actingAs($owner)->get(route('media.show',[$asset->uuid,'viewer']))->assertOk()->assertHeader('Cache-Control');$other=User::create(['name'=>'Other','email'=>'other-pipeline@test.local','password'=>Hash::make('x'),'status'=>'active']);$this->actingAs($other)->get(route('media.show',[$asset->uuid,'viewer']))->assertForbidden();}
}
