<?php
namespace Tests\Feature;use App\Models\User;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Support\Facades\Hash;use Illuminate\Support\Str;use Inertia\Testing\AssertableInertia as Assert;use Tests\TestCase;
class SettingsNavigationSyncTest extends TestCase{use RefreshDatabase;private function user(string$e='settings-nav@test.local',string$t='photographer'):User{return User::create(['name'=>'Settings Studio','email'=>$e,'password'=>Hash::make('x'),'status'=>'active','account_type'=>$t,'plan'=>'premium']);}
public function test_landing_and_legacy_get_routes_redirect_to_canonical_pages():void{$u=$this->user();$this->actingAs($u)->get('/settings')->assertRedirect(route('settings.profile'));$this->get('/settings/preferences')->assertRedirect(route('settings.account-preferences'));$this->get('/settings/branding')->assertRedirect(route('settings.business-branding'));$this->get('/settings/team')->assertRedirect(route('settings.team-login'));}
public function test_owner_receives_one_authoritative_sidebar_in_exact_order():void{$u=$this->user();$expected=['Your Profile','Account Preferences','Business Branding','Team Login','Flipbook Settings','Watermark','Portfolio','LensPic Wallet','Transactions'];$this->actingAs($u)->get(route('settings.profile'))->assertInertia(fn(Assert$p)=>$p->where('settingsNavigation',fn($items)=>collect($items)->pluck('label')->all()===$expected)->where('settingsNavigation.0.href',route('settings.profile'))->where('settingsNavigation.8.href',route('settings.transactions')));}
public function test_every_canonical_sidebar_route_is_a_full_inertia_page():void{$u=$this->user();$routes=['settings.profile'=>'Settings/Index','settings.account-preferences'=>'Settings/Index','settings.business-branding'=>'Settings/Index','settings.team-login'=>'Settings/TeamLogin','settings.flipbook'=>'Settings/Flipbook','settings.watermark'=>'Settings/Watermark','settings.portfolio'=>'Settings/Portfolio','settings.wallet'=>'Settings/Wallet','settings.transactions'=>'Settings/Transactions'];foreach($routes as$name=>$component)$this->actingAs($u)->get(route($name))->assertOk()->assertInertia(fn(Assert$p)=>$p->component($component));}
public function test_sidebar_visibility_and_backend_authorization_use_real_roles():void{$owner=$this->user();$viewer=$this->user('settings-viewer@test.local','user');$owner->studioTeamMembers()->create(['uuid'=>(string)Str::uuid(),'user_id'=>$viewer->id,'role'=>'viewer','status'=>'active']);$this->actingAs($viewer)->get(route('settings.profile'))->assertInertia(fn(Assert$p)=>$p->where('settingsNavigation',fn($items)=>collect($items)->pluck('label')->all()===['Your Profile']));foreach(['settings.team-login','settings.watermark','settings.portfolio','settings.wallet','settings.transactions']as$route)$this->actingAs($viewer)->get(route($route))->assertForbidden();}
public function test_transactions_wallet_state_and_wallet_history_link_are_distinct():void{$u=$this->user();$this->actingAs($u)->get(route('settings.transactions'))->assertInertia(fn(Assert$p)=>$p->where('tab','main')->where('section','transactions'));$this->get(route('settings.transactions',['tab'=>'wallet']))->assertInertia(fn(Assert$p)=>$p->where('tab','wallet')->where('section','transactions'));$this->get(route('settings.wallet'))->assertInertia(fn(Assert$p)=>$p->component('Settings/Wallet')->where('section','wallet'));$this->assertStringContainsString('/settings/transactions?tab=wallet',file_get_contents(resource_path('js/Pages/Settings/Wallet.vue')));}
public function test_navigation_has_no_placeholders_and_uses_lenspic_branding():void{$source=file_get_contents(resource_path('js/Components/SettingsNav.vue'));$this->assertStringNotContainsString('href="#"',$source);$this->assertStringNotContainsString('modal-route',$source);}
}
