<?php
namespace Tests\Feature;
use App\Mail\TeamInvitationMail;
use App\Models\{Group,SubscriptionPlan,StudioTeamMembership,TeamInvitation,User};
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\{Hash,Mail};
use Illuminate\Support\Str;
use Inertia\Testing\AssertableInertia as Assert;
use Tests\TestCase;
class TeamLoginTest extends TestCase {
 use RefreshDatabase;
 protected function setUp():void{parent::setUp();config(['cache.default'=>'array']);Mail::fake();}
 private function user(string$email,string$type='photographer'):User{return User::create(['name'=>Str::before($email,'@'),'email'=>$email,'password'=>Hash::make('password'),'status'=>'active','account_type'=>$type,'plan'=>'standard','onboarding_completed_at'=>now()]);}
 private function payload(array$x=[]):array{return array_replace(['name'=>'Team Person','email'=>'member@test.local','role'=>'photographer'],$x);}
 private function invite(User$owner,array$x=[]):array{$this->actingAs($owner)->post(route('settings.team-login.invitations.store'),$this->payload($x))->assertRedirect()->assertSessionHasNoErrors();$invitation=TeamInvitation::latest('id')->firstOrFail();$mail=null;Mail::assertQueued(TeamInvitationMail::class,function($m)use(&$mail){$mail=$m;return true;});$token=basename(parse_url($mail->acceptUrl,PHP_URL_PATH));return[$invitation,$token];}
 public function test_team_login_is_a_refresh_safe_full_page_with_empty_state():void{$owner=$this->user('owner@test.local');$this->actingAs($owner)->get('/settings/team-login')->assertOk()->assertInertia(fn(Assert$p)=>$p->component('Settings/TeamLogin')->where('section','team-login')->where('canManageTeam',true)->where('canInviteTeamMembers',true)->has('members',0)->where('seatUsage.limit',5)->where('seatUsage.reached',false));$page=file_get_contents(resource_path('js/Pages/Settings/TeamLogin.vue'));$this->assertStringContainsString('Add Team Member',$page);$this->assertStringContainsString('No team member added yet',$page);$this->assertStringContainsString('#actions',$page);$this->assertStringContainsString('slot name="actions"',file_get_contents(resource_path('js/Components/PageHeader.vue')));}
 public function test_owner_invites_real_email_and_only_hash_is_stored():void{$owner=$this->user('owner@test.local');[$i,$token]=$this->invite($owner);$this->assertSame('pending',$i->status);$this->assertNotSame($token,$i->token_hash);$this->assertSame(hash('sha256',$token),$i->token_hash);$this->assertDatabaseCount('studio_team_memberships',0);$this->assertDatabaseHas('audit_logs',['action'=>'team.invitation.sent','subject_id'=>$i->id]);}
 public function test_self_duplicate_active_member_and_plan_limit_are_rejected():void{$owner=$this->user('owner@test.local');$this->actingAs($owner)->post(route('settings.team-login.invitations.store'),$this->payload(['email'=>$owner->email]))->assertSessionHasErrors('email');[$i]=$this->invite($owner);$this->actingAs($owner)->post(route('settings.team-login.invitations.store'),$this->payload())->assertSessionHasErrors('email');$i->update(['status'=>'accepted','accepted_at'=>now()]);$member=$this->user('member@test.local','user');$owner->studioTeamMembers()->create(['uuid'=>(string)Str::uuid(),'user_id'=>$member->id,'role'=>'viewer','status'=>'active']);$this->actingAs($owner)->post(route('settings.team-login.invitations.store'),$this->payload())->assertSessionHasErrors('email');SubscriptionPlan::where('code','standard')->update(['team_seat_limit'=>1]);$this->actingAs($owner)->post(route('settings.team-login.invitations.store'),$this->payload(['email'=>'second@test.local']))->assertSessionHasErrors('email');}
 public function test_existing_user_accepts_once_and_email_mismatch_is_blocked():void{$owner=$this->user('owner@test.local');$member=$this->user('member@test.local','user');$wrong=$this->user('wrong@test.local','user');[$i,$token]=$this->invite($owner);$this->actingAs($wrong)->post(route('team-invitations.accept',[$i,$token]))->assertForbidden();$this->assertDatabaseCount('studio_team_memberships',0);$this->actingAs($member)->post(route('team-invitations.accept',[$i,$token]))->assertRedirect(route('groups.index'));$this->assertDatabaseHas('studio_team_memberships',['studio_owner_id'=>$owner->id,'user_id'=>$member->id,'role'=>'photographer','status'=>'active']);$this->post(route('team-invitations.accept',[$i,$token]))->assertStatus(410);}
 public function test_newly_registered_account_can_accept_after_authentication():void{$owner=$this->user('owner@test.local');[$i,$token]=$this->invite($owner,['email'=>'new@test.local']);$this->get(route('team-invitations.show',[$i,$token]))->assertOk()->assertSessionHas('pending_team_invitation');$new=$this->user('new@test.local','user');$this->actingAs($new)->post(route('team-invitations.accept',[$i,$token]))->assertRedirect();$this->assertDatabaseHas('studio_team_memberships',['user_id'=>$new->id,'studio_owner_id'=>$owner->id]);}
 public function test_expired_and_revoked_tokens_cannot_be_accepted_and_resend_rotates_token():void{$owner=$this->user('owner@test.local');$member=$this->user('member@test.local','user');[$i,$token]=$this->invite($owner);$i->update(['expires_at'=>now()->subMinute()]);$this->actingAs($member)->post(route('team-invitations.accept',[$i,$token]))->assertStatus(410);$i->update(['expires_at'=>now()->addDay()]);$old=$i->token_hash;$this->actingAs($owner)->post(route('settings.team-login.invitations.resend',$i))->assertRedirect()->assertSessionHas('success');$this->assertNotSame($old,$i->fresh()->token_hash);$this->actingAs($owner)->post(route('settings.team-login.invitations.revoke',$i))->assertSessionHasNoErrors();$this->actingAs($member)->post(route('team-invitations.accept',[$i,$token]))->assertStatus(410);}
 public function test_admin_can_manage_team_but_viewer_and_cross_studio_actor_cannot():void{$owner=$this->user('owner@test.local');$admin=$this->user('admin@test.local');$viewer=$this->user('viewer@test.local','user');$outsider=$this->user('outside@test.local');foreach([[$admin,'admin'],[$viewer,'viewer']]as[$u,$role])$owner->studioTeamMembers()->create(['uuid'=>(string)Str::uuid(),'user_id'=>$u->id,'role'=>$role,'status'=>'active','permissions'=>null]);$this->actingAs($admin)->get(route('settings.team-login'))->assertOk();$this->actingAs($viewer)->get(route('settings.team-login'))->assertForbidden();$target=$owner->studioTeamMembers()->where('user_id',$viewer->id)->first();$this->actingAs($outsider)->patch(route('settings.team-login.members.role',$target),['role'=>'editor'])->assertNotFound();}
 public function test_role_suspend_activate_and_remove_are_studio_scoped_and_keep_user():void{$owner=$this->user('owner@test.local');$member=$this->user('member@test.local','user');$membership=$owner->studioTeamMembers()->create(['uuid'=>(string)Str::uuid(),'user_id'=>$member->id,'role'=>'viewer','status'=>'active']);$this->actingAs($owner)->patch(route('settings.team-login.members.role',$membership),['role'=>'editor'])->assertSessionHasNoErrors();$this->assertSame('editor',$membership->fresh()->role);$this->patch(route('settings.team-login.members.status',$membership),['status'=>'suspended'])->assertSessionHasNoErrors();$this->assertSame('suspended',$membership->fresh()->status);$this->patch(route('settings.team-login.members.status',$membership),['status'=>'active'])->assertSessionHasNoErrors();$this->delete(route('settings.team-login.members.destroy',$membership))->assertSessionHasNoErrors();$this->assertDatabaseHas('users',['id'=>$member->id]);$this->assertDatabaseMissing('studio_team_memberships',['id'=>$membership->id]);}
 public function test_viewer_can_view_owner_gallery_but_cannot_upload_and_suspension_revokes_access():void{$owner=$this->user('owner@test.local');$viewer=$this->user('viewer@test.local','user');$m=$owner->studioTeamMembers()->create(['uuid'=>(string)Str::uuid(),'user_id'=>$viewer->id,'role'=>'viewer','status'=>'active']);$group=Group::create(['name'=>'Studio Gallery','creator_id'=>$owner->id,'is_active'=>true]);$this->actingAs($viewer)->get(route('groups.gallery',$group))->assertOk();$this->postJson(route('photos.store',$group),['photos'=>[]])->assertForbidden();$m->update(['status'=>'suspended','suspended_at'=>now()]);$this->get(route('groups.gallery',$group))->assertForbidden();}
}
