<?php
namespace Tests\Feature;use App\Models\{FinancialTransaction,User,WalletLedgerEntry};use App\Services\Wallet\WalletService;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Support\Facades\Hash;use Illuminate\Support\Str;use Inertia\Testing\AssertableInertia as Assert;use Tests\TestCase;
class TransactionsTest extends TestCase{use RefreshDatabase;private function user(string$e='transactions@test.local',string$t='photographer'):User{return User::create(['name'=>'Transaction Studio','email'=>$e,'password'=>Hash::make('x'),'status'=>'active','account_type'=>$t]);}private function subscription(User$u,string$payment='pay_main'):void{$u->subscriptions()->create(['plan'=>'standard','amount'=>'8838.20','currency'=>'INR','payment_id'=>$payment,'provider_order_id'=>'order_main','billing_cycle'=>'yearly','status'=>'active','starts_at'=>now(),'expires_at'=>now()->addYear()]);}
public function test_full_page_defaults_to_main_and_projects_real_subscription():void{$u=$this->user();$this->subscription($u);$this->actingAs($u)->get(route('settings.transactions'))->assertInertia(fn(Assert$p)=>$p->component('Settings/Transactions')->where('section','transactions')->where('tab','main')->has('transactions.data',1)->where('transactions.data.0.description','Standard Plan Purchase')->where('transactions.data.0.total_minor',883820)->where('transactions.data.0.currency','INR'));}
public function test_wallet_tab_uses_same_topup_and_ledger_sources():void{$u=$this->user();$s=app(WalletService::class);$t=$s->pending($u,10000,(string)Str::uuid());$s->credit($t,'pay_wallet_tx');$this->actingAs($u)->get(route('settings.transactions',['tab'=>'wallet']))->assertInertia(fn(Assert$p)=>$p->where('tab','wallet')->has('transactions.data',1)->where('transactions.data.0.type','wallet_top_up')->where('transactions.data.0.credits','100')->where('transactions.data.0.tax_minor',1800));}
public function test_backend_filters_and_refresh_state_are_preserved():void{$u=$this->user();$this->subscription($u);$this->actingAs($u)->get(route('settings.transactions',['tab'=>'main','status'=>'paid','currency'=>'INR','search'=>'Standard']))->assertInertia(fn(Assert$p)=>$p->where('tab','main')->where('filters.status','paid')->where('filters.currency','INR')->has('transactions.data',1));$this->get(route('settings.transactions',['tab'=>'main','status'=>'failed']))->assertInertia(fn(Assert$p)=>$p->has('transactions.data',0));}
public function test_csv_export_is_scoped_filtered_and_formula_safe():void{$u=$this->user();$other=$this->user('other-transactions@test.local');$this->subscription($u,'pay_owned');$this->subscription($other,'pay_other');$response=$this->actingAs($u)->get(route('settings.transactions.export',['tab'=>'main','search'=>'Standard']));$response->assertOk()->assertDownload();$csv=$response->streamedContent();$this->assertStringContainsString('pay_owned',$csv);$this->assertStringNotContainsString('pay_other',$csv);FinancialTransaction::where('studio_owner_id',$u->id)->update(['description'=>'=HYPERLINK("bad")']);$csv=$this->get(route('settings.transactions.export',['tab'=>'main']))->streamedContent();$this->assertStringContainsString("'=HYPERLINK",$csv);}
public function test_detail_and_exports_are_tenant_authorized():void{$o=$this->user();$this->subscription($o);$this->actingAs($o)->get(route('settings.transactions'));$tx=FinancialTransaction::firstOrFail();$other=$this->user('blocked-transactions@test.local');$this->actingAs($other)->get(route('settings.transactions.show',$tx))->assertNotFound();$viewer=$this->user('viewer-transactions@test.local','user');$o->studioTeamMembers()->create(['uuid'=>(string)Str::uuid(),'user_id'=>$viewer->id,'role'=>'viewer','status'=>'active']);$this->actingAs($viewer)->get(route('settings.transactions'))->assertForbidden();}
}
