<?php
namespace Tests\Feature;use App\Models\{User,WalletLedgerEntry};use App\Services\Wallet\WalletService;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Support\Facades\{Hash,Http};use Illuminate\Support\Str;use Inertia\Testing\AssertableInertia as Assert;use Tests\TestCase;
class WalletTest extends TestCase{use RefreshDatabase;protected function setUp():void{parent::setUp();config(['services.razorpay.key_id'=>'key','services.razorpay.key_secret'=>'secret','services.razorpay.webhook_secret'=>'hook']);Http::fake(['api.razorpay.com/*'=>Http::response(['id'=>'order_wallet','amount'=>11800,'currency'=>'INR','status'=>'paid'])]);}private function user(string$e='wallet@test.local',string$t='photographer'):User{return User::create(['name'=>'Wallet Studio','email'=>$e,'password'=>Hash::make('x'),'status'=>'active','account_type'=>$t]);}
public function test_page_uses_real_balance_and_authoritative_rates():void{$u=$this->user();$this->actingAs($u)->get(route('settings.wallet'))->assertInertia(fn(Assert$p)=>$p->component('Settings/Wallet')->where('section','wallet')->where('balance','0')->where('suggestions',[100,300,500,1000])->where('rates.mail_notification_units',2)->where('rates.whatsapp_notification_units',10)->where('rates.liveness_check_units',20));$this->assertDatabaseHas('wallets',['studio_owner_id'=>$u->id,'available_credit_units'=>0]);}
public function test_exact_quote_rules_use_minor_and_subcredit_units():void{$s=app(WalletService::class);$this->assertSame(['base_amount_minor'=>10000,'tax_amount_minor'=>1800,'total_amount_minor'=>11800,'credit_units'=>1000,'currency'=>'INR'],$s->quote(10000));foreach([0,-500,600,10000001]as$v)try{$s->quote($v);$this->fail('Invalid quote accepted');}catch(\Illuminate\Validation\ValidationException){} }
public function test_pending_order_does_not_credit_and_signed_webhook_credits_exactly_once():void{$u=$this->user();Http::fake(['api.razorpay.com/v1/orders'=>Http::response(['id'=>'order_wallet','amount'=>11800,'currency'=>'INR','status'=>'paid'])]);$key=(string)Str::uuid();$this->actingAs($u)->postJson(route('settings.wallet.top-ups.store'),['amount_rupees'=>100,'idempotency_key'=>$key])->assertOk()->assertJsonPath('amount',11800);$t=$u->wallet()->first()->topUps()->first();$this->assertSame(0,$u->wallet->available_credit_units);$payload=['event'=>'payment.captured','payload'=>['payment'=>['entity'=>['id'=>'pay_wallet','order_id'=>'order_wallet','amount'=>11800,'currency'=>'INR','status'=>'captured']]]];$raw=json_encode($payload);$sig=hash_hmac('sha256',$raw,'hook');for($i=0;$i<2;$i++)$this->call('POST',route('billing.razorpay.wallet-webhook'),[],[],[],['CONTENT_TYPE'=>'application/json','HTTP_X_RAZORPAY_SIGNATURE'=>$sig],$raw)->assertOk();$this->assertSame(1000,$u->wallet()->first()->available_credit_units);$this->assertSame(1,WalletLedgerEntry::count());$this->assertSame('paid',$t->fresh()->status);}
public function test_invalid_signature_or_amount_never_credits():void{$u=$this->user();$s=app(WalletService::class);$t=$s->pending($u,10000,(string)Str::uuid());$t->update(['provider_order_id'=>'order_bad']);$payload=['event'=>'payment.captured','payload'=>['payment'=>['entity'=>['id'=>'pay_bad','order_id'=>'order_bad','amount'=>999,'currency'=>'INR','status'=>'captured']]]];$raw=json_encode($payload);$this->call('POST',route('billing.razorpay.wallet-webhook'),[],[],[],['CONTENT_TYPE'=>'application/json','HTTP_X_RAZORPAY_SIGNATURE'=>'bad'],$raw)->assertUnauthorized();Http::fake(['api.razorpay.com/*'=>Http::response(['id'=>'order_bad','amount'=>11800,'currency'=>'INR','status'=>'paid'])]);$sig=hash_hmac('sha256',$raw,'hook');$this->call('POST',route('billing.razorpay.wallet-webhook'),[],[],[],['CONTENT_TYPE'=>'application/json','HTTP_X_RAZORPAY_SIGNATURE'=>$sig],$raw)->assertUnprocessable();$this->assertSame(0,$u->wallet()->first()->available_credit_units);}
public function test_reservation_prevents_overspend_and_capture_is_idempotent():void{$u=$this->user();$s=app(WalletService::class);$t=$s->pending($u,10000,(string)Str::uuid());$s->credit($t,'manual-test-payment');$w=$u->wallet()->first();$r=$s->reserve($w,800,'notification','batch','one','reserve-one');try{$s->reserve($w,300,'notification','batch','two','reserve-two');$this->fail('Overspend allowed');}catch(\Illuminate\Validation\ValidationException){}$s->capture($r);$s->capture($r);$this->assertSame(200,$w->fresh()->available_credit_units);$this->assertSame(0,$w->fresh()->reserved_credit_units);$this->assertSame(2,WalletLedgerEntry::count());}
public function test_authorization_is_studio_scoped():void{$o=$this->user();$admin=$this->user('admin-wallet@test.local','user');$viewer=$this->user('viewer-wallet@test.local','user');foreach([[$admin,'admin'],[$viewer,'viewer']]as[$u,$role])$o->studioTeamMembers()->create(['uuid'=>(string)Str::uuid(),'user_id'=>$u->id,'role'=>$role,'status'=>'active']);$this->actingAs($admin)->get(route('settings.wallet'))->assertOk();$this->actingAs($viewer)->get(route('settings.wallet'))->assertForbidden();}
}
