@extends('layouts.marketing')
@push('head')<script type="application/ld+json">{!! json_encode(['@context'=>'https://schema.org','@type'=>'SoftwareApplication','name'=>'LensPic','applicationCategory'=>'PhotographyApplication','operatingSystem'=>'Web','url'=>route('home')], JSON_UNESCAPED_SLASHES) !!}</script>@endpush
@section('content')
@if(request()->routeIs('home'))@include('marketing.partials.hero-slider',['slider'=>'home'])@endif
<section class="marketing-section"><div class="marketing-container"><div class="section-heading"><span class="eyebrow">How LensPic works</span><h2>From group upload to personal delivery</h2><p>Face matching is optional and always requires the group member’s explicit consent.</p></div><div class="steps-grid">@foreach([['Create a group','Configure the group and its access controls.'],['Upload photos','Private originals enter the optimized media pipeline.'],['Invite members','Share a revocable group link, code or QR.'],['Request consent','Members consent before providing a matching selfie.'],['Deliver matches','Authorized members reach their relevant photos.']] as $step)<div class="step-card"><span class="step-number">{{ $loop->iteration }}</span><h3>{{ $step[0] }}</h3><p class="mt-2 text-sm leading-6 text-slate-600">{{ $step[1] }}</p></div>@endforeach</div></div></section>
<section class="marketing-section section-muted"><div class="marketing-container"><div class="section-heading"><span class="eyebrow">Built for delivery</span><h2>Professional controls without manual hand-offs</h2></div><div class="card-grid">@foreach([['Private galleries','Control invitations, visibility and downloads.'],['High-quality media','Keep originals private while delivering responsive variants.'],['Studio branding','Configure business identity, watermarks and portfolio presentation.'],['Client favourites','Keep selection feedback attached to the gallery.'],['Team access','Invite studio colleagues within role and plan limits.'],['Analytics and notifications','Follow relevant activity from the workspace.']] as $item)<article class="marketing-card"><span class="icon-box">{{ $loop->iteration }}</span><h3>{{ $item[0] }}</h3><p>{{ $item[1] }}</p><a class="card-link" href="{{ route('marketing.features') }}">Explore features</a></article>@endforeach</div></div></section>
<section class="marketing-section"><div class="marketing-container"><div class="section-heading"><span class="eyebrow">Solutions</span><h2>One platform, different group workflows</h2></div><div class="card-grid">@foreach(config('marketing.solutions') as $solution)<article class="marketing-card"><h3>{{ $solution['nav'] }}</h3><p>{{ $solution['intro'] }}</p><a class="card-link" href="{{ route($solution['route']) }}">View solution</a></article>@endforeach</div></div></section>
<section class="marketing-section section-muted"><div class="marketing-container section-heading"><h2>Start sharing group photos with LensPic</h2><p>Create a photographer account, join an existing group, or book a product walkthrough.</p><div class="cta-row justify-center"><a class="button button-primary" href="{{ auth()->check()?route('dashboard'):route('register') }}">{{ auth()->check()?'Go to workspace':'Get started' }}</a><a class="button button-secondary" href="{{ route('marketing.join') }}">Join a group</a><a class="button button-text" href="{{ route('marketing.contact',['type'=>'book_demo']) }}">Book a demo</a></div></div></section>
@endsection
