@extends('layouts.marketing') @section('content')
@php
$content = match($journey) {
'how-it-works' => ['How LensPic works','Separate, connected workflows for group owners and members.',[
 ['For photographers',['Create an account and group','Configure group-gallery privacy and access','Organize folders and upload photographs','Monitor background processing','Share a controlled group link, QR or code','Manage favourites, downloads and engagement']],
 ['For group members',['Open an authorized group invitation or enter a code','Review group access and consent information','Browse permitted photographs or select Find My Photos','Provide a temporary selfie only after consenting','Review potential matches','Favourite or download permitted media','Withdraw consent or request biometric deletion']],]],
'guests' => ['A private group-member journey','Reach the photographs your group owner has made available without installing an app.',[
 ['Join safely',[['Authorized invitations','Use the group link, QR code or six-character code supplied by the group owner. Invalid and expired invitations fail without exposing another group.']]],['Browse and select',[['Gallery controls','View permitted group folders, favourite photographs and download only when the group owner has enabled it.']]],['Choose photo discovery',[['Optional matching','Face matching is optional. LensPic requests explicit consent before comparing your selfie with photographs inside that group.']]],]],
'discovery' => ['Consent-based photo discovery','Find My Photos narrows an authorized group gallery to potential matches.',[
 ['Group-specific matching',[['Scoped comparison','LensPic compares your consented facial reference only with indexed photographs in the authorized group. It does not search the public internet or identify unknown people.']]],['Review the result',[['Accuracy limitations','Similarity systems can return false matches or miss photographs. Review results before downloading and use supported reject or review controls.']]],['Stay in control',[['Consent and deletion','Withdraw consent or submit a tracked biometric deletion request from the authenticated workflow.']]],]],
'galleries' => ['Group galleries with professional controls','A structured delivery experience for each group.',[
 ['Organize',[['Groups and folders','Create groups, folders and cover images while queued processing prepares controlled media variants.']]],['Invite',[['Controlled sharing','Use revocable group links, access codes and QR-ready invitations appropriate to the group.']]],['Deliver',[['Member experience','Configure favourites, individual or bulk downloads, branding, watermark and slideshow behavior where supported.']]],]],
default => ['Help and support','Choose the path that matches what you need.',[
 ['Joining a group',[['Group access','Use the Join a Group page with the group owner’s current code or invitation.']]],['Account and billing',[['Workspace help','Sign in for subscription, wallet, transaction and profile controls.']]],['Technical or privacy support',[['Contact support','Submit the contact form so the request is stored and routed through the configured support workflow.']]],]],
};
@endphp
@php
$journeyHeader = match($journey) {
    'how-it-works' => ['How LensPic Works','Separate Photographer and Group Member flows connect private setup, uploads, invitations, optional consent-based matching and controlled delivery.','How It Works','How It Works','✦',['desktop'=>'lenspic-photographer-workflow.png','mobile'=>'lenspic-photographer-workflow-mobile.png','width'=>1400,'height'=>933,'alt'=>'A professional photographer moving from photo upload to an organized private LensPic gallery.']],
    'guests' => [$title,$content[1],'Group Members','Group Members','◎',['desktop'=>'lenspic-group-member-workflow.png','mobile'=>'lenspic-group-member-workflow-mobile.png','width'=>1400,'height'=>933,'alt'=>'A Group Member viewing private celebration photographs, optional discovery results, favourites and downloads.']],
    'discovery' => [$title,$content[1],'Find My Photos','Find My Photos','⌕',['desktop'=>'lenspic-group-member-workflow.png','mobile'=>'lenspic-group-member-workflow-mobile.png','width'=>1400,'height'=>933,'alt'=>'A member voluntarily using Find My Photos inside an authorized private LensPic Group.']],
    'galleries' => [$title,$content[1],'Group Galleries','Group Galleries','▦',['desktop'=>'lenspic-features-multi-device.png','mobile'=>'lenspic-features-multi-device-mobile.png','width'=>1200,'height'=>800,'alt'=>'Private LensPic Group Gallery displayed across laptop and mobile devices.']],
    default => [$title,$description,'LensPic','LensPic','✦',null],
};
@endphp
@include('marketing.partials.inner-header',['eyebrow'=>$journeyHeader[2],'heading'=>$journeyHeader[0],'intro'=>$journeyHeader[1],'breadcrumb'=>$journeyHeader[3],'theme'=>'soft','icon'=>$journeyHeader[4],'visual'=>$journeyHeader[5]])
@if($journey === 'how-it-works')<section class="marketing-section workflow-visual-section"><div class="marketing-container"><div class="section-heading left"><span class="eyebrow">Group Member workflow</span><h2>Authorized access, choice and personal delivery</h2><p>Members can browse first, choose optional consent-based discovery, review potential matches, and favourite or download only when permitted.</p></div><picture class="workflow-visual"><source media="(max-width: 767px)" srcset="{{ asset('images/marketing/lenspic-group-member-workflow-mobile.png') }}"><img src="{{ asset('images/marketing/lenspic-group-member-workflow.png') }}" width="1400" height="933" loading="lazy" alt="A member viewing an authorized private gallery, optional photo-discovery results, favourites and permitted downloads."></picture></div></section>@endif
@foreach($content[2] as $group)<section class="marketing-section {{ $loop->even?'section-muted':'' }}"><div class="marketing-container"><div class="section-heading left"><h2>{{ $group[0] }}</h2></div><div class="card-grid">@foreach($group[1] as $item)<article class="marketing-card"><span class="icon-box">{{ $loop->iteration }}</span>@if(is_array($item))<h3>{{ $item[0] }}</h3><p>{{ $item[1] }}</p>@else<h3>{{ $item }}</h3>@endif</article>@endforeach</div></div></section>@endforeach
@endsection
