<script setup>
import AppShell from '../Layouts/AppShell.vue';import PageHeader from '../Components/PageHeader.vue';import UiButton from '../Components/UiButton.vue';import{Head,Link,router}from'@inertiajs/vue3'
const p=defineProps({notifications:Object,filters:Object,categories:Array}),labels={groups:'Groups',uploads:'Uploads',face_recognition:'Face Recognition',team:'Team',billing:'Billing',storage:'Storage',system:'System'},icons={groups:'▦',uploads:'↑',face_recognition:'◎',team:'♙',billing:'₹',storage:'◫',system:'ⓘ'}
const visit=x=>router.get('/notifications',{...p.filters,...x,page:undefined},{preserveState:true,preserveScroll:true,replace:true}),patch=(url,o={})=>router.patch(url,{},{preserveScroll:true,...o}),exact=v=>v?new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'',relative=v=>{const s=Math.round((new Date(v)-Date.now())/1000),a=Math.abs(s),u=a<60?'second':a<3600?'minute':a<86400?'hour':'day',d=u==='second'?1:u==='minute'?60:u==='hour'?3600:86400;return new Intl.RelativeTimeFormat(undefined,{numeric:'auto'}).format(Math.round(s/d),u)},openAction=i=>i.read_at?router.visit(i.action_url):patch(`/notifications/${i.id}/read`,{onSuccess:()=>router.visit(i.action_url)})
</script>
<template><AppShell><Head title="Notifications"/><div class="lp-page"><PageHeader eyebrow="Account activity" title="Notifications" description="Account-owned LensPic notifications appear here."><div class="flex flex-wrap gap-2"><UiButton variant="secondary" href="/settings/account-preferences">Notification Settings</UiButton><UiButton v-if="notifications.data.some(n=>!n.read_at)" variant="secondary" @click="patch('/notifications/read-all')">Mark all as read</UiButton></div></PageHeader>
<div class="mt-8 flex flex-wrap items-center justify-between gap-4"><div role="tablist" aria-label="Notification status" class="flex rounded-xl border bg-white p-1"><button v-for="tab in ['all','unread']" :key="tab" role="tab" :aria-selected="filters.status===tab" :class="['rounded-lg px-4 py-2 text-sm font-semibold capitalize',filters.status===tab?'bg-indigo text-white':'text-slate-600']" @click="visit({status:tab})">{{tab}}</button></div><label class="text-sm font-semibold">Type <select class="field ml-2 w-auto" :value="filters.category||''" @change="visit({category:$event.target.value||undefined})"><option value="">All types</option><option v-for="c in categories" :key="c" :value="c">{{labels[c]}}</option></select></label></div>
<section v-if="!notifications.data.length" class="lp-card mt-6 p-10 text-center" aria-live="polite"><h2 class="text-xl font-bold">{{filters.status==='unread'?'You’re all caught up.':'You have no notifications yet.'}}</h2><p v-if="filters.status!=='unread'" class="mt-2 text-slate-600">Important LensPic updates will appear here.</p></section>
<section v-else class="mt-6 space-y-3" aria-label="Notification list"><article v-for="i in notifications.data" :key="i.id" :class="['lp-card p-5',!i.read_at?'border-l-4 border-l-indigo':'']"><div class="flex items-start gap-4"><span class="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-indigo/10 font-bold text-indigo" aria-hidden="true">{{icons[i.category]||'ⓘ'}}</span><div class="min-w-0 flex-1"><div class="flex flex-wrap items-start justify-between gap-2"><div><p v-if="!i.read_at" class="text-xs font-bold uppercase tracking-wide text-indigo">Unread</p><h2 class="font-bold">{{i.title}}</h2></div><time class="text-xs text-slate-500" :datetime="i.created_at" :title="exact(i.created_at)">{{relative(i.created_at)}}<span class="sr-only">, {{exact(i.created_at)}}</span></time></div><p class="mt-2 text-sm text-slate-700">{{i.message}}</p><p v-if="i.context" class="mt-1 text-xs text-slate-500">{{i.context}}</p><div class="mt-4 flex flex-wrap gap-3"><button v-if="i.action_url" class="text-sm font-bold text-indigo" @click="openAction(i)">{{i.action_label}}</button><button class="text-sm font-semibold text-slate-600" @click="patch(`/notifications/${i.id}/${i.read_at?'unread':'read'}`)">Mark as {{i.read_at?'unread':'read'}}</button><button class="text-sm font-semibold text-rose-700" @click="router.delete(`/notifications/${i.id}`,{preserveScroll:true})">Dismiss</button></div></div></div></article></section>
<nav v-if="notifications.links.length>3" class="mt-6 flex flex-wrap justify-center gap-2" aria-label="Notifications pagination"><Link v-for="l in notifications.links" :key="l.label" :href="l.url||''" preserve-scroll :class="['rounded-lg border px-3 py-2 text-sm',l.active?'bg-indigo text-white':l.url?'bg-white':'pointer-events-none opacity-50']" v-html="l.label"/></nav></div></AppShell></template>
