<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ $p->name }}</title><style>body{margin:0;font-family:system-ui;color:#172033;background:#fafafa}.notice{text-align:center;background:#f59e0b;color:white;padding:8px}header{text-align:center;padding:28px}.logo{max-height:72px;max-width:220px}.cover{width:100%;max-height:68vh;object-fit:cover}.wrap{max-width:1120px;margin:auto;padding:32px 20px}.grid,.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:12px}.grid img{width:100%;height:280px;object-fit:cover;border-radius:14px}.card{background:white;padding:18px;border:1px solid #e5e7eb;border-radius:14px}</style></head><body>
@if($preview)<div class="notice">Authorized Portfolio Preview</div>@endif
<header>@if($branding['logo_url'])<img class="logo" src="{{ $preview ? $branding['logo_url'] : route('portfolio.logo',$p) }}" alt="Business logo">@endif<h1>{{ $p->name }}</h1>@if($p->website_url)<a href="{{ $p->website_url }}">{{ $p->website_url }}</a>@endif</header>
@if($p->cover_object_key)<img class="cover" src="{{ $preview ? route('settings.portfolio.cover') : route('portfolio.cover',$p) }}" alt="Cover">@endif
<main class="wrap">
@if(!empty($contacts['whatsapp_url']))<a href="{{ $contacts['whatsapp_url'] }}" target="_blank" rel="noopener noreferrer" style="display:inline-flex;align-items:center;gap:10px;min-height:44px;padding:4px 20px;background:#166534;color:white;border-radius:12px;text-decoration:none;font-weight:600"><svg aria-hidden="true" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 11.5a8.5 8.5 0 0 1-8.5 8.5H5l-3 2 1.5-6A8.5 8.5 0 1 1 21 11.5Z"/><path d="M8 9h8M8 13h5"/></svg>Chat on WhatsApp</a>@endif
@if($p->about_us)<h2>About Us</h2><p>{!! nl2br(e($p->about_us)) !!}</p>@endif
@if($images->count())<h2>Portfolio</h2><div class="grid">@foreach($images as $image)<img loading="lazy" src="{{ $image['url'] }}" alt="{{ $image['alt'] }}">@endforeach</div>@endif
@if($services->count())<h2>Services</h2><div class="cards">@foreach($services as $service)<div class="card"><strong>{{ $service['name'] }}</strong>@if($service['price'] !== null)<p>{{ $p->currency_code }} {{ number_format((float)$service['price'],2) }}</p>@endif</div>@endforeach</div>@endif
@if(count($payment))<h2>Payment Details</h2><div class="card">@foreach($payment as $label => $value)<p><strong>{{ ucwords(str_replace('_',' ',$label)) }}:</strong> {{ $value }}</p>@endforeach</div>@endif
</main></body></html>
