<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
return new class extends Migration{
 public function up():void
 {
  foreach(DB::table('razorpay_orders')->whereNull('entitlement_snapshot')->get()as$order){$plan=DB::table('subscription_plans')->where('code',$order->plan)->first();if(!$plan)continue;$price=DB::table('subscription_plan_prices')->where('subscription_plan_id',$plan->id)->where('billing_interval',$order->billing_cycle)->where('is_active',true)->latest('effective_from')->first();if(!$price)continue;$features=$this->features($plan->id);$total=(int)$order->amount;$base=min((int)$price->base_amount_paise,$total);$snapshot=$this->snapshot($plan,$order->billing_cycle,$base,$total-$base,$total,$features);DB::table('razorpay_orders')->where('id',$order->id)->update(['subscription_plan_id'=>$plan->id,'subscription_plan_price_id'=>$price->id,'base_amount_paise'=>$base,'gst_amount_paise'=>$total-$base,'entitlement_snapshot'=>json_encode($snapshot),'expires_at'=>$order->status==='created'?now()->addMinutes(30):null]);}
  foreach(DB::table('subscriptions')->whereNotNull('payment_id')->get()as$subscription){if(DB::table('subscription_entitlement_snapshots')->where('subscription_id',$subscription->id)->exists())continue;$plan=DB::table('subscription_plans')->where('code',$subscription->plan)->first();if(!$plan)continue;$order=DB::table('razorpay_orders')->where('payment_id',$subscription->payment_id)->first();$total=$order?(int)$order->amount:(int)round((float)$subscription->amount*100);$base=$order?($order->base_amount_paise??$total):$total;$gst=$order?($order->gst_amount_paise??0):0;$snapshot=$order&&$order->entitlement_snapshot?json_decode($order->entitlement_snapshot,true):$this->snapshot($plan,$subscription->billing_cycle,$base,$gst,$total,$this->features($plan->id));DB::table('subscriptions')->where('id',$subscription->id)->update(['subscription_plan_id'=>$plan->id,'plan_version'=>$plan->version]);DB::table('subscription_entitlement_snapshots')->insert(['subscription_id'=>$subscription->id,'subscription_plan_id'=>$plan->id,'plan_code'=>$snapshot['plan_code'],'plan_name'=>$snapshot['plan_name'],'plan_version'=>$snapshot['plan_version'],'billing_interval'=>$subscription->billing_cycle,'base_amount_paise'=>$base,'gst_amount_paise'=>$gst,'total_amount_paise'=>$total,'currency'=>$subscription->currency,'photo_limit'=>$snapshot['photo_limit'],'photo_reuse_limit'=>$snapshot['photo_reuse_limit'],'video_limit_mb'=>$snapshot['video_limit_mb'],'team_seat_limit'=>$snapshot['team_seat_limit'],'group_limit'=>$snapshot['group_limit'],'guest_limit'=>$snapshot['guest_limit'],'features'=>json_encode($snapshot['features']),'addons'=>json_encode([]),'starts_at'=>$subscription->starts_at,'expires_at'=>$subscription->expires_at,'created_at'=>now(),'updated_at'=>now()]);}
 }
 private function features(int$id):array{return DB::table('subscription_plan_features as pf')->join('subscription_features as f','f.id','=','pf.subscription_feature_id')->where('pf.subscription_plan_id',$id)->where('pf.is_included',true)->pluck('pf.is_included','f.code')->map(fn()=>true)->all();}
 private function snapshot(object$p,string$i,int$b,int$g,int$t,array$f):array{return['subscription_plan_id'=>$p->id,'plan_code'=>$p->code,'plan_name'=>$p->name,'plan_version'=>$p->version,'billing_interval'=>$i,'base_amount_paise'=>$b,'gst_amount_paise'=>$g,'total_amount_paise'=>$t,'currency'=>'INR','photo_limit'=>$p->photo_storage_limit,'photo_reuse_limit'=>$p->photo_reuse_limit,'video_limit_mb'=>$p->video_storage_mb,'team_seat_limit'=>$p->team_seat_limit,'group_limit'=>$p->group_limit,'guest_limit'=>$p->guest_limit,'features'=>$f,'addons'=>[],'validity_months'=>$i==='yearly'?12:3];}
 public function down():void{}
};
