<script setup>
import AppShell from '../../Layouts/AppShell.vue';import PageHeader from '../../Components/PageHeader.vue';import SettingsNav from '../../Components/SettingsNav.vue';import UiButton from '../../Components/UiButton.vue';import UiAlert from '../../Components/UiAlert.vue';import{Head,useForm}from'@inertiajs/vue3';import{onBeforeUnmount,onMounted,ref}from'vue'
const props=defineProps({section:String,settings:Object}),input=ref(null),preview=ref(props.settings.logo_url||null),form=useForm({business_name:props.settings.business_name||'',apply_to_portfolio:!!props.settings.apply_to_portfolio,logo:null,remove_logo:false})
function choose(e){const file=e.target.files?.[0];form.clearErrors('logo');if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)){form.setError('logo','The selected logo format is not supported.');e.target.value='';return}if(file.size>2*1024*1024){form.setError('logo','Please select an image smaller than 2 MB.');e.target.value='';return}if(String(preview.value||'').startsWith('blob:'))URL.revokeObjectURL(preview.value);form.logo=file;form.remove_logo=false;preview.value=URL.createObjectURL(file)}
function remove(){if(String(preview.value||'').startsWith('blob:'))URL.revokeObjectURL(preview.value);preview.value=null;form.logo=null;form.remove_logo=true;if(input.value)input.value.value=''}
function save(){form.transform(data=>({...data,_method:'put'})).post('/settings/flipbook',{forceFormData:true,preserveScroll:true})}
function leaving(e){if(form.isDirty){e.preventDefault();e.returnValue=''}}
onMounted(()=>addEventListener('beforeunload',leaving));onBeforeUnmount(()=>{removeEventListener('beforeunload',leaving);if(String(preview.value||'').startsWith('blob:'))URL.revokeObjectURL(preview.value)})
</script>
<template><AppShell><Head title="Flipbook Settings"/><div class="lp-page"><PageHeader eyebrow="Settings" title="Flipbook Settings" description="Set the business identity displayed in your Digital Flipbooks."/><div class="mt-8 grid gap-6 lg:grid-cols-[240px_1fr]"><SettingsNav :section="section"/><form class="lp-card space-y-7 p-5 sm:p-7" @submit.prevent="save"><label class="lp-label" for="flipbook-name">Business Name<input id="flipbook-name" v-model="form.business_name" class="field mt-2" maxlength="150" :aria-invalid="!!form.errors.business_name" aria-describedby="flipbook-name-error"><small id="flipbook-name-error" class="text-rose-600">{{form.errors.business_name}}</small></label><section><h2 class="lp-label">Logo</h2><div class="mt-3 flex min-h-44 flex-col items-center justify-center gap-4 rounded-xl border border-dashed border-slate-300 bg-slate-50 p-5 text-center"><img v-if="preview" :src="preview" alt="Digital Flipbook business logo preview" class="max-h-24 max-w-full object-contain"><div v-else class="text-sm text-slate-500">Upload Logo for Digital Flipbook</div><p v-if="form.logo" class="text-sm font-semibold">{{form.logo.name}}</p><div class="flex flex-wrap justify-center gap-3"><label class="btn-secondary cursor-pointer">Browse<input ref="input" type="file" accept="image/png,image/jpeg,image/webp" class="sr-only" aria-label="Browse for Digital Flipbook logo" @change="choose"></label><button v-if="preview" type="button" class="btn-secondary text-rose-700" aria-label="Remove Digital Flipbook logo" @click="remove">Remove Logo</button></div><p class="text-xs text-slate-500">We recommend using PNG format<br>Maximum size allowed is 2 MB</p><small class="text-rose-600" role="alert">{{form.errors.logo}}</small></div></section><label class="flex items-start justify-between gap-5 rounded-xl border border-slate-200 p-5"><span><strong class="block">Apply same settings for Portfolio</strong><span class="mt-1 block text-sm text-slate-600">Properties set for Digital Flipbook will also be applied to Portfolio</span><span v-if="form.apply_to_portfolio" class="mt-2 block text-xs font-semibold text-indigo">Portfolio will use this Business Name and Logo.</span></span><input v-model="form.apply_to_portfolio" type="checkbox" class="mt-1 h-5 w-5" role="switch" :aria-checked="form.apply_to_portfolio"></label><UiAlert v-if="Object.keys(form.errors).length" tone="error">Review the highlighted Flipbook settings. Your changes have been preserved.</UiAlert><UiButton type="submit" :loading="form.processing" :disabled="!form.isDirty">Save</UiButton></form></div></div></AppShell></template>
