<script setup>
import AppShell from '../../Layouts/AppShell.vue'
import PageHeader from '../../Components/PageHeader.vue'
import SettingsNav from '../../Components/SettingsNav.vue'
import UiButton from '../../Components/UiButton.vue'
import UiModal from '../../Components/UiModal.vue'
import { Head, router, useForm } from '@inertiajs/vue3'
import { nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue'
const props=defineProps({section:String,owner:Object,members:Array,seatUsage:Object,canManageTeam:Boolean,canInviteTeamMembers:Boolean,roles:Array,permissions:Object})
const addOpen=ref(false),edit=ref(null),confirming=ref(null),trigger=ref(null),dialog=ref(null)
const invite=useForm({name:'',email:'',role:'photographer',permissions:[]}),roleForm=useForm({role:'viewer',permissions:[]})
const labels={admin:'Admin',photographer:'Photographer',editor:'Editor',viewer:'Viewer'}
function openAdd(e){trigger.value=e?.currentTarget;addOpen.value=true;nextTick(()=>dialog.value?.querySelector('input')?.focus())}
function closeAdd(){if(invite.processing)return;addOpen.value=false;invite.clearErrors();nextTick(()=>trigger.value?.focus())}
function submitInvite(){invite.post('/settings/team-login/invitations',{preserveScroll:true,onSuccess:()=>{invite.reset();addOpen.value=false}})}
function openEdit(member){edit.value=member;roleForm.role=member.role;roleForm.permissions=[...(props.permissions[member.role]||[])];nextTick(()=>dialog.value?.querySelector('select')?.focus())}
function saveRole(){roleForm.patch(`/settings/team-login/members/${edit.value.uuid}/role`,{preserveScroll:true,onSuccess:()=>edit.value=null})}
function action(){const item=confirming.value;if(!item)return;const done=()=>confirming.value=null;if(item.kind==='remove')router.delete(`/settings/team-login/members/${item.member.uuid}`,{preserveScroll:true,onFinish:done});else if(item.kind==='status')router.patch(`/settings/team-login/members/${item.member.uuid}/status`,{status:item.member.status==='active'?'suspended':'active'},{preserveScroll:true,onFinish:done});else router.post(`/settings/team-login/invitations/${item.member.uuid}/${item.kind}`,{},{preserveScroll:true,onFinish:done})}
function resend(member){router.post(`/settings/team-login/invitations/${member.uuid}/resend`,{},{preserveScroll:true})}
function keydown(e){if(e.key==='Escape'){if(addOpen.value)closeAdd();else if(edit.value)edit.value=null}if((addOpen.value||edit.value)&&e.key==='Tab'){const nodes=[...dialog.value.querySelectorAll('button,input,select')].filter(x=>!x.disabled);if(!nodes.length)return;const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}
watch(()=>roleForm.role,role=>roleForm.permissions=[...(props.permissions[role]||[])])
watch([addOpen,edit],([a,e])=>document.body.style.overflow=a||e?'hidden':'')
onMounted(()=>document.addEventListener('keydown',keydown));onBeforeUnmount(()=>{document.removeEventListener('keydown',keydown);document.body.style.overflow=''})
const last=value=>value?new Date(value).toLocaleString('en-IN'):'Never'
</script>
<template><AppShell><Head title="Team Login"/><div class="lp-page"><PageHeader eyebrow="Settings" title="Team Login" description="Give each team member secure access through their own LensPic account."><template #actions><UiButton v-if="canInviteTeamMembers" :disabled="seatUsage.reached" aria-label="Add Team Member" @click="openAdd">Add Team Member</UiButton></template></PageHeader><div class="mt-8 grid gap-6 lg:grid-cols-[240px_1fr]"><SettingsNav :section="section"/><main class="space-y-5"><section class="lp-card p-5 sm:p-6"><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-xl font-bold">Team members</h2><p class="lp-subtitle">{{seatUsage.used}} of {{seatUsage.unlimited?'Unlimited':seatUsage.limit}} team seats used. Pending invitations reserve a seat.</p></div><div v-if="seatUsage.reached" class="text-right"><p class="text-sm font-semibold text-amber-700">Your current plan’s team-member limit has been reached.</p><a href="/pricing" class="mt-2 inline-block text-sm font-semibold text-indigo">Upgrade plan</a></div></div><div v-if="!members.length" class="mt-8 rounded-xl border border-dashed border-slate-300 px-5 py-14 text-center"><div class="text-3xl" aria-hidden="true">👥</div><h3 class="mt-3 text-lg font-bold">No team member added yet</h3><p class="mt-2 text-sm text-slate-500">Invite a member without sharing your account password.</p></div><div v-else class="lp-table-wrap mt-6"><table class="lp-table"><thead><tr><th>Member Name</th><th>Email</th><th>Role</th><th>Status</th><th>Invitation Status</th><th>Last Active</th><th>Actions</th></tr></thead><tbody><tr v-for="member in members" :key="member.uuid"><td class="font-semibold">{{member.name}}</td><td>{{member.email}}</td><td class="capitalize">{{member.role}}</td><td class="capitalize">{{member.status}}</td><td class="capitalize">{{member.invitation_status}}</td><td>{{last(member.last_active_at)}}</td><td><div class="flex min-w-44 flex-wrap gap-2"><template v-if="member.invitation_status==='pending'"><button class="text-sm font-semibold text-indigo" @click="resend(member)">Resend Invitation</button><button class="text-sm font-semibold text-rose-700" @click="confirming={kind:'revoke',member}">Revoke Invitation</button></template><template v-else-if="member.invitation_status==='accepted'"><button class="text-sm font-semibold text-indigo" @click="openEdit(member)">View/Edit Permissions</button><button class="text-sm font-semibold text-indigo" @click="openEdit(member)">Change Role</button><button class="text-sm font-semibold" @click="confirming={kind:'status',member}">{{member.status==='active'?'Suspend':'Activate'}}</button><button class="text-sm font-semibold text-rose-700" @click="confirming={kind:'remove',member}">Remove Member</button></template></div></td></tr></tbody></table></div></section></main></div></div>
<Teleport to="body"><div v-if="addOpen" class="fixed inset-0 z-[100] grid place-items-center bg-ink/60 p-4" role="dialog" aria-modal="true" aria-labelledby="add-team-title" @click.self="closeAdd"><form ref="dialog" class="lp-card w-full max-w-lg space-y-5 p-6" @submit.prevent="submitInvite"><div class="flex justify-between gap-3"><div><h2 id="add-team-title" class="text-xl font-bold">Add New Member</h2><p class="lp-subtitle">A secure invitation will be emailed to this person.</p></div><button type="button" aria-label="Close" class="text-2xl" @click="closeAdd">×</button></div><label class="lp-label" for="member-name">Full Name<input id="member-name" v-model.trim="invite.name" class="field mt-2" required :aria-invalid="!!invite.errors.name"><small class="text-rose-600">{{invite.errors.name}}</small></label><label class="lp-label" for="member-email">Email Address<input id="member-email" v-model.trim="invite.email" type="email" class="field mt-2" required :aria-invalid="!!invite.errors.email"><small class="text-rose-600">{{invite.errors.email}}</small></label><label class="lp-label" for="member-role">Role<select id="member-role" v-model="invite.role" class="field mt-2"><option v-for="role in roles" :key="role" :value="role">{{labels[role]}}</option></select><small class="text-rose-600">{{invite.errors.role}}</small></label><div><p class="lp-label">Permissions</p><p class="mt-1 text-sm text-slate-500">The selected role’s enforced permissions are applied automatically.</p><div class="mt-3 flex flex-wrap gap-2"><span v-for="permission in permissions[invite.role]" :key="permission" class="rounded-full bg-slate-100 px-3 py-1 text-xs">{{permission.replaceAll('_',' ')}}</span></div></div><div class="flex justify-end gap-3"><UiButton variant="secondary" @click="closeAdd">Cancel</UiButton><UiButton type="submit" :loading="invite.processing">Send Invitation</UiButton></div></form></div>
<div v-if="edit" class="fixed inset-0 z-[100] grid place-items-center bg-ink/60 p-4" role="dialog" aria-modal="true" aria-labelledby="edit-team-title" @click.self="edit=null"><form ref="dialog" class="lp-card w-full max-w-lg space-y-5 p-6" @submit.prevent="saveRole"><h2 id="edit-team-title" class="text-xl font-bold">Permissions for {{edit.name}}</h2><label class="lp-label">Role<select v-model="roleForm.role" class="field mt-2"><option v-for="role in roles" :key="role" :value="role">{{labels[role]}}</option></select></label><div><p class="lp-label">Effective permissions</p><div class="mt-3 grid gap-2 sm:grid-cols-2"><label v-for="permission in permissions[roleForm.role]" :key="permission" class="flex items-center gap-2 text-sm"><input v-model="roleForm.permissions" type="checkbox" :value="permission"> {{permission.replaceAll('_',' ')}}</label></div></div><div class="flex justify-end gap-3"><UiButton variant="secondary" @click="edit=null">Cancel</UiButton><UiButton type="submit" :loading="roleForm.processing">Save Changes</UiButton></div></form></div></Teleport>
<UiModal :open="!!confirming" :busy="false" :title="confirming?.kind==='remove'?`Remove ${confirming.member.name}?`:confirming?.kind==='revoke'?'Revoke invitation?':`${confirming?.member.status==='active'?'Suspend':'Activate'} ${confirming?.member.name}?`" :description="confirming?.kind==='remove'?'Their LensPic account and activity records will remain; only this studio membership is removed.':confirming?.kind==='revoke'?'The secure invitation link will stop working immediately.':'This changes access to this studio immediately.'" @close="confirming=null" @confirm="action"/></AppShell></template>
