<script setup>
import AppShell from '../../Layouts/AppShell.vue'
import PageHeader from '../../Components/PageHeader.vue'
import SettingsNav from '../../Components/SettingsNav.vue'
import StateCard from '../../Components/StateCard.vue'
import UiAlert from '../../Components/UiAlert.vue'
import UiBadge from '../../Components/UiBadge.vue'
import { Head } from '@inertiajs/vue3'
const props = defineProps({ section: String, user: Object, transactions: Array, portfolioBranding: Object })
const titles = { portfolio: 'Portfolio', wallet: 'Wallet', transactions: 'Billing history', privacy: 'Privacy & biometrics' }
const date = value => value ? new Date(value).toLocaleDateString('en-IN') : '—'
</script>
<template><AppShell><Head :title="titles[section]"/><div class="lp-page"><PageHeader eyebrow="Settings" :title="titles[section]" description="This route is a complete, refresh-safe LensPic dashboard page."/><div class="mt-8 grid gap-6 lg:grid-cols-[240px_1fr]"><SettingsNav :section="section"/><section class="lp-card p-6"><template v-if="section==='portfolio'"><h2 class="text-xl font-bold">Photography portfolio</h2><p class="lp-subtitle">Portfolio setup is available for supported plans and is currently coordinated by the LensPic team.</p><a v-if="['essential','premium','pro','business','enterprise'].includes(user.plan)" href="mailto:hello@lenspic.in?subject=Portfolio Website Setup" class="btn-primary mt-6">Request setup</a><a v-else href="/pricing" class="btn-primary mt-6">View eligible plans</a></template><template v-else-if="section==='wallet'"><StateCard title="Wallet is not available" message="The current backend has no wallet ledger or balance service. No synthetic balance or transaction controls are displayed."/></template><template v-else-if="section==='privacy'"><h2 class="text-xl font-bold">Biometric privacy controls</h2><p class="lp-subtitle">Biometric consent, selfie retention and deletion are scoped to each Group so access can be re-authorized for that event.</p><UiAlert class="mt-5">Open an authorized Group and choose Find My Photos to review consent or request event-specific deletion.</UiAlert><a href="/groups" class="btn-primary mt-6">Open Groups</a></template><template v-else><StateCard v-if="!transactions.length" title="No transactions" message="Account-owned subscription records will appear here."/><div v-else class="lp-table-wrap"><table class="lp-table"><thead><tr><th>Date</th><th>Plan</th><th>Amount</th><th>Status</th></tr></thead><tbody><tr v-for="item in transactions" :key="item.id"><td>{{date(item.created_at)}}</td><td class="capitalize">{{item.plan}}</td><td>{{item.currency}} {{item.amount}}</td><td><UiBadge :tone="item.status==='active'?'success':'warning'">{{item.status}}</UiBadge></td></tr></tbody></table></div></template></section></div></div></AppShell></template>
