<?php
namespace App\Services\Billing;
use App\Models\{SubscriptionPlan,SubscriptionPlanPrice};
class PlanCatalog
{
 public function all(bool$publicOnly=true):array{return SubscriptionPlan::query()->where('is_active',true)->when($publicOnly,fn($q)=>$q->where('is_public',true))->orderBy('display_order')->get()->map(fn($p)=>$this->present($p))->all();}
 public function find(string$code,string$cycle,bool$purchasable=true):array{abort_unless(in_array($cycle,['quarterly','yearly'],true),422,'The selected billing period is unavailable.');$plan=SubscriptionPlan::where('code',$code)->first();abort_unless($plan&&(!$purchasable||($plan->is_active&&$plan->is_public)),422,'The selected plan is unavailable.');$presented=$this->present($plan);$selected=collect($presented['cycles'])->firstWhere('cycle',$cycle);abort_unless($selected,422,'The selected billing period is unavailable.');return[...$presented,'selected_cycle'=>$cycle,'selected_price'=>$selected];}
 public function present(SubscriptionPlan$plan):array{$plan->loadMissing(['prices','features']);$cycles=collect(['quarterly','yearly'])->map(function($cycle)use($plan){$price=$this->effectivePrice($plan,$cycle);if(!$price)return null;return['id'=>$price->id,'cycle'=>$cycle,'base_amount'=>$price->base_amount_paise,'gst_basis_points'=>$price->gst_rate_basis_points,'gst_amount'=>$price->gstAmount(),'total_amount'=>$price->totalAmount(),'currency'=>$price->currency,'validity_months'=>$cycle==='yearly'?12:3,'comparison_amount'=>$price->comparison_amount_paise,'razorpay_plan_id'=>$price->razorpay_plan_id];})->filter()->values();$included=$plan->features->filter(fn($f)=>$f->pivot->is_included)->sortBy('pivot.display_order')->map(fn($f)=>['code'=>$f->code,'label'=>$f->pivot->display_label?:$f->name,'icon'=>$f->icon])->values();$addons=$plan->features->filter(fn($f)=>$f->pivot->is_addon)->sortBy('pivot.display_order')->map(fn($f)=>['feature_code'=>$f->code,'name'=>$f->pivot->display_label?:$f->name,'icon'=>'plus-circle','base_amount'=>(int)$f->pivot->addon_price_paise,'gst_basis_points'=>$cycles->first()['gst_basis_points']??1800])->values();return['id'=>$plan->id,'code'=>$plan->code,'name'=>$plan->name,'rank'=>$plan->rank,'description'=>$plan->short_description,'display_order'=>$plan->display_order,'active'=>$plan->is_active,'recommended'=>$plan->is_recommended,'badge_text'=>$plan->badge_text,'badge_style'=>$plan->badge_style,'version'=>$plan->version,'features'=>$included->all(),'optional_addons'=>$addons->all(),'entitlements'=>['photo_limit'=>$plan->photo_storage_limit,'photo_delete_reupload_limit'=>$plan->photo_reuse_limit,'video_storage_limit_mb'=>$plan->video_storage_mb,'team_member_limit'=>$plan->team_seat_limit,'group_limit'=>$plan->group_limit,'guest_limit'=>$plan->guest_limit,'deleted_media_usage_release_hours'=>24,'video_delete_reupload_limit_mb'=>$plan->video_storage_mb*2,'usage_reset_period'=>'billing_cycle'],'cycles'=>$cycles->all()];}
 public function purchaseSnapshot(array$plan):array{$price=$plan['selected_price'];return['subscription_plan_id'=>$plan['id'],'plan_code'=>$plan['code'],'plan_name'=>$plan['name'],'plan_version'=>$plan['version'],'billing_interval'=>$plan['selected_cycle'],'base_amount_paise'=>$price['base_amount'],'gst_amount_paise'=>$price['gst_amount'],'total_amount_paise'=>$price['total_amount'],'currency'=>$price['currency'],'photo_limit'=>$plan['entitlements']['photo_limit'],'photo_reuse_limit'=>$plan['entitlements']['photo_delete_reupload_limit'],'video_limit_mb'=>$plan['entitlements']['video_storage_limit_mb'],'team_seat_limit'=>$plan['entitlements']['team_member_limit'],'group_limit'=>$plan['entitlements']['group_limit'],'guest_limit'=>$plan['entitlements']['guest_limit'],'features'=>collect($plan['features'])->mapWithKeys(fn($f)=>[$f['code']=>true])->all(),'addons'=>[],'validity_months'=>$price['validity_months']];}
 private function effectivePrice(SubscriptionPlan$plan,string$cycle):?SubscriptionPlanPrice{return$plan->prices->where('billing_interval',$cycle)->where('is_active',true)->filter(fn($p)=>$p->effective_from->lte(now())&&(!$p->effective_until||$p->effective_until->isFuture()))->sortByDesc('effective_from')->first();}
}
