<script setup>
import AppShell from '../../Layouts/AppShell.vue'
import PageHeader from '../../Components/PageHeader.vue'
import UiAlert from '../../Components/UiAlert.vue'
import UiButton from '../../Components/UiButton.vue'
import UiCard from '../../Components/UiCard.vue'
import { Head, useForm } from '@inertiajs/vue3'
import { onBeforeUnmount, ref } from 'vue'

const token=()=>`${crypto.getRandomValues(new Uint32Array(1))[0].toString(16).padStart(8,'0')}-${crypto.getRandomValues(new Uint16Array(1))[0].toString(16).padStart(4,'0')}-4${crypto.getRandomValues(new Uint16Array(1))[0].toString(16).slice(1).padStart(3,'0')}-a${crypto.getRandomValues(new Uint16Array(1))[0].toString(16).slice(1).padStart(3,'0')}-${[...crypto.getRandomValues(new Uint8Array(6))].map(v=>v.toString(16).padStart(2,'0')).join('')}`
const form=useForm({submission_token:token(),name:'',event_type:'wedding',privacy:'link_only',location:'',membership_limit:500,access_options:['partial_access','full_access'],face_recognition_enabled:true,allow_guest_upload:false,watermark_enabled:false,cover_photo:null})
const preview=ref(null),input=ref(null),dragging=ref(false)
function clearCover(){if(preview.value)URL.revokeObjectURL(preview.value);preview.value=null;form.cover_photo=null;if(input.value)input.value.value=''}
function select(file){clearCover();if(!file)return;form.cover_photo=file;preview.value=URL.createObjectURL(file)}
function choose(event){select(event.target.files?.[0])}
function drop(event){dragging.value=false;select(event.dataTransfer.files?.[0])}
function submit(){form.post('/groups',{forceFormData:true,onSuccess:clearCover})}
onBeforeUnmount(clearCover)
</script>

<template><AppShell><Head title="Create Group"/><div class="lp-page-narrow"><PageHeader eyebrow="New Group" title="Create a photo-sharing Group" description="One Group contains the gallery, participants, folders, processing and privacy controls for a wedding, function or photoshoot."/><UiCard class="mt-8"><form class="space-y-5" @submit.prevent="submit"><label class="lp-label">Group name<input v-model="form.name" class="field mt-2" placeholder="Aarav & Mira — Mumbai" required><span v-if="form.errors.name" class="lp-error">{{form.errors.name}}</span></label><div class="grid gap-5 md:grid-cols-2"><label class="lp-label">Project type<select v-model="form.event_type" class="field mt-2"><option value="wedding">Wedding</option><option value="birthday">Birthday</option><option value="corporate">Corporate function</option><option value="conference">Conference</option><option value="school">School function</option><option value="festival">Festival</option><option value="family">Family event</option><option value="photoshoot">Photoshoot</option><option value="other">Other</option></select></label><label class="lp-label">Visibility<select v-model="form.privacy" class="field mt-2"><option value="private">Private</option><option value="link_only">Invitation only</option><option value="public">Public</option></select></label></div><label class="lp-label">Location<input v-model="form.location" class="field mt-2" placeholder="Mumbai, Maharashtra"><span v-if="form.errors.location" class="lp-error">{{form.errors.location}}</span></label>
<fieldset><legend class="lp-label">Group cover photo <span class="font-normal text-slate-500">(optional)</span></legend><div class="mt-2 aspect-video overflow-hidden border-2 border-dashed bg-slate-100" :class="dragging?'border-indigo bg-indigo/5':'border-slate-300'" @dragenter.prevent="dragging=true" @dragover.prevent @dragleave.prevent="dragging=false" @drop.prevent="drop"><img v-if="preview" :src="preview" alt="Selected Group cover preview" class="h-full w-full object-cover"><label v-else class="flex h-full cursor-pointer flex-col items-center justify-center p-6 text-center"><span class="font-semibold text-ink">Drop a cover here or choose a file</span><span class="mt-2 text-xs text-slate-500">JPG, PNG or WebP · maximum 10 MB · minimum 800×400</span><input ref="input" type="file" accept="image/jpeg,image/png,image/webp" class="sr-only" @change="choose"></label></div><div v-if="preview" class="mt-3 flex gap-3"><label class="btn-secondary cursor-pointer">Replace<input ref="input" type="file" accept="image/jpeg,image/png,image/webp" class="sr-only" @change="choose"></label><button type="button" class="btn-ghost" @click="clearCover">Remove</button></div><span v-if="form.errors.cover_photo" class="lp-error">{{form.errors.cover_photo}}</span></fieldset>
<fieldset class="space-y-3 rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm"><legend class="px-1 font-semibold">Group features</legend><label class="flex gap-3"><input v-model="form.face_recognition_enabled" type="checkbox" class="accent-indigo">Enable consent-led My Photos discovery</label><label class="flex gap-3"><input v-model="form.allow_guest_upload" type="checkbox" class="accent-indigo">Allow participant uploads</label><label class="flex gap-3"><input v-model="form.watermark_enabled" type="checkbox" class="accent-indigo">Apply studio watermark</label></fieldset><UiAlert v-if="Object.keys(form.errors).length" tone="error">Review the highlighted Group details.</UiAlert><div v-if="form.progress" class="h-2 overflow-hidden rounded-full bg-slate-200" aria-label="Upload progress"><div class="h-full bg-indigo transition-all" :style="{width:`${form.progress.percentage}%`}"></div></div><div class="flex flex-wrap gap-3"><UiButton type="submit" :loading="form.processing" :disabled="form.processing">Create Group</UiButton><UiButton href="/groups" variant="secondary">Cancel</UiButton></div></form></UiCard></div></AppShell></template>
