<script setup>
import AppShell from '../../Layouts/AppShell.vue';import GroupNav from '../../Components/GroupNav.vue';import PageHeader from '../../Components/PageHeader.vue';import StateCard from '../../Components/StateCard.vue';import UiBadge from '../../Components/UiBadge.vue';import UiButton from '../../Components/UiButton.vue';import {Head,Link,router} from '@inertiajs/vue3';import {computed,onBeforeUnmount,onMounted,ref} from 'vue'
const props=defineProps({group:Object,batches:Array,exports:Array,indexRun:Object}),timer=ref(),busy=ref(null)
const active=computed(()=>props.batches.some(x=>['pending','queued','processing'].includes(x.state))||props.exports.some(x=>['queued','processing'].includes(x.state)))
const tone=s=>s==='completed'?'success':['failed','completed_with_errors'].includes(s)?'error':['queued','processing','pending'].includes(s)?'warning':'info'
const label=s=>({pending:'Preparing',queued:'Preparing',processing:'Processing',completed:'Ready',failed:"Couldn't process",completed_with_errors:'Needs attention',cancelled:'Cancelled',not_started:'Not started'}[s]||'Preparing')
const progress=x=>x.total_files?Math.round(((x.completed_files+x.failed_files+x.cancelled_files)/x.total_files)*100):0
function action(url){busy.value=url;router.post(url,{},{preserveScroll:true,onFinish:()=>busy.value=null})}
function poll(){if(active.value)router.reload({only:['batches','exports','indexRun'],preserveScroll:true,onFinish:schedule})}
function schedule(){clearTimeout(timer.value);if(active.value)timer.value=setTimeout(poll,3000)}
onMounted(schedule);onBeforeUnmount(()=>clearTimeout(timer.value))
</script>
<template><AppShell><Head title="Photo progress"/><GroupNav :group="group"/><div class="lp-page mt-6"><PageHeader eyebrow="Group photos" :title="`Photo progress · ${group.name}`" description="You can leave this page. Your photos will continue processing safely."><Link :href="`/groups/${group.id}/gallery`" class="btn-primary">View gallery</Link></PageHeader>
<div class="mt-8 grid gap-6 xl:grid-cols-2"><section><h2 class="text-xl font-bold">Recent uploads</h2><StateCard v-if="!batches.length" class="mt-4" title="No recent uploads" message="Photos uploaded from the Group Gallery will appear here."/><div v-else class="mt-4 space-y-3"><UiCard v-for="upload in batches" :key="upload.uuid"><div class="flex justify-between gap-3"><div><p class="font-semibold">{{upload.display_message}}</p><p class="text-xs text-slate-500">{{upload.completed_files}} ready · {{upload.processing_files}} processing · {{upload.pending_files}} remaining<span v-if="upload.failed_files"> · {{upload.failed_files}} need attention</span><span v-if="upload.cancelled_files"> · {{upload.cancelled_files}} cancelled</span></p></div><UiBadge :tone="tone(upload.state)">{{upload.display_status}}</UiBadge></div><div class="mt-4 h-2 overflow-hidden rounded-full bg-slate-100"><div class="h-full bg-indigo transition-all" :style="{width:`${progress(upload)}%`}"></div></div><p class="mt-1 text-right text-xs text-slate-500">{{progress(upload)}}%</p><ul class="mt-3 divide-y divide-slate-100 text-xs"><li v-for="file in upload.files" :key="file.id" class="flex justify-between gap-3 py-2"><span class="truncate">{{file.client_filename}}</span><span :class="file.state==='failed'?'text-red-700':''">{{file.display_status}}{{file.error?` · ${file.error}`:''}}</span></li></ul><div class="mt-4 flex flex-wrap gap-2"><UiButton v-if="['pending','queued','processing'].includes(upload.state)" variant="danger" :loading="busy===`/processing/batches/${upload.uuid}/cancel`" @click="action(`/processing/batches/${upload.uuid}/cancel`)">Cancel remaining photos</UiButton><UiButton v-if="upload.failed_files&&!upload.cancelled_at" variant="secondary" :loading="busy===`/processing/batches/${upload.uuid}/retry`" @click="action(`/processing/batches/${upload.uuid}/retry`)">Try again</UiButton><UiButton v-if="['completed','completed_with_errors'].includes(upload.state)" :href="`/groups/${group.id}/gallery`">View photos</UiButton></div></UiCard></div></section>
<section><h2 class="text-xl font-bold">Downloads</h2><StateCard v-if="!exports.length" class="mt-4" title="No downloads prepared" message="Select authorized photographs in the Group Gallery."/><UiCard v-for="item in exports" v-else :key="item.uuid" class="mt-4"><div class="flex justify-between"><b>{{item.photo_ids.length}} photos</b><UiBadge :tone="tone(item.state)">{{label(item.state)}}</UiBadge></div><div class="mt-4 flex gap-2"><UiButton v-if="item.state==='completed'" :href="`/exports/${item.uuid}/download`">Download ZIP</UiButton><UiButton v-if="['queued','processing'].includes(item.state)" variant="danger" @click="action(`/exports/${item.uuid}/cancel`)">Cancel</UiButton></div></UiCard></section></div>
<UiCard class="mt-6"><div class="flex flex-wrap justify-between gap-4"><div><h2 class="text-lg font-bold">Find My Photos preparation</h2><p class="text-sm text-slate-500">{{indexRun?.completed||0}} of {{indexRun?.total||0}} prepared</p></div><div class="flex items-center gap-3"><UiBadge :tone="tone(indexRun?.state||'not_started')">{{label(indexRun?.state||'not_started')}}</UiBadge><UiButton v-if="!indexRun||['failed','completed','cancelled'].includes(indexRun.state)" @click="action(`/groups/${group.id}/face-index-runs`)">{{indexRun?.state==='failed'?'Try again':'Prepare photos'}}</UiButton></div></div></UiCard></div></AppShell></template>
