<?php
namespace App\Http\Controllers;

use App\Models\Group;
use App\Models\GroupAccessAudit;
use App\Models\GroupAccessInvite;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;
use App\Services\AuditLogger;
use Inertia\Inertia;

class GroupAccessInviteController extends Controller {
    private function authorizeOwner(Group $group): void { \Illuminate\Support\Facades\Gate::authorize("manageInvitations", $group); }
    private function child(Group $group,GroupAccessInvite $invite): void { abort_unless($invite->group_id===$group->id,404); }
    public function index(Group $group) { $this->authorizeOwner($group); $invites=$group->accessInvites()->orderBy('access_type')->get(); return Inertia::render('Groups/Invitations',['group'=>$group->only('id','name'),'invites'=>$invites->map(fn($i)=>['id'=>$i->id,'label'=>$i->label,'access_type'=>$i->access_type,'code'=>$i->access_code,'url'=>$i->url,'active'=>$i->isUsable(),'expires_at'=>$i->expires_at,'max_uses'=>$i->max_uses,'used_count'=>$i->used_count])]); }
    public function store(Request $request,Group $group) { $this->authorizeOwner($group); $data=$request->validate(['access_type'=>['required',Rule::in([GroupAccessInvite::PARTIAL,GroupAccessInvite::FULL])]]); $invite=GroupAccessInvite::firstOrCreate(['group_id'=>$group->id,'access_type'=>$data['access_type']],['access_code'=>GroupAccessInvite::generateCode(),'invitation_token'=>Str::random(48),'created_by'=>auth()->id()]); return back()->with('success',$invite->label.' invitation enabled.'); }
    public function shareLink(Group $group) { $this->authorizeOwner($group);abort_unless($group->is_active,409,'Group sharing is currently disabled.');[$invite,$status]=DB::transaction(function()use($group){$invite=GroupAccessInvite::where('group_id',$group->id)->where('access_type',GroupAccessInvite::FULL)->lockForUpdate()->first();if(!$invite){$invite=GroupAccessInvite::makeFor($group,GroupAccessInvite::FULL,auth()->id())->refresh();return[$invite,'created'];}if(!$invite->isUsable()){$invite->update(['access_code'=>GroupAccessInvite::generateCode(),'invitation_token'=>Str::random(48),'is_active'=>true,'expires_at'=>null,'revoked_at'=>null,'used_count'=>0]);$invite->refresh();$this->audit($group,$invite,'regenerated',['reason'=>'share_request']);return[$invite,'regenerated'];}return[$invite,'reused'];});
        $permissions=['find_my_photos'=>(bool)$group->face_recognition_enabled,'view_highlights'=>$group->folders()->where('highlighted',true)->exists(),'view_all_photos'=>true,'favourite'=>(bool)$group->favourites_enabled,'download'=>(bool)$group->downloads_enabled];
        return response()->json(['success'=>true,'invitation'=>['code'=>$invite->access_code,'share_url'=>$invite->url,'print_url'=>route('groups.access-invites.print',[$group,$invite]),'access_type'=>$invite->access_type,'expires_at'=>$invite->expires_at?->toIso8601String(),'permissions'=>$permissions],'share_url'=>$invite->url,'url'=>$invite->url,'access_code'=>$invite->access_code,'expires_at'=>$invite->expires_at?->toIso8601String(),'invitation_status'=>$status]); }
    public function update(Request $request,Group $group,GroupAccessInvite $invite) { $this->authorizeOwner($group);$this->child($group,$invite);$data=$request->validate(['expires_at'=>'nullable|date|after:now','max_uses'=>'nullable|integer|min:1|max:1000000']);$invite->update($data);return back()->with('success','Invitation limits updated.'); }
    public function regenerate(Request $request,Group $group,GroupAccessInvite $invite) { $this->authorizeOwner($group);$this->child($group,$invite);$what=$request->validate(['regenerate'=>['required',Rule::in(['code','link','both'])]])['regenerate'];$old=['code'=>$invite->access_code];$invite->update(['access_code'=>in_array($what,['code','both'])?GroupAccessInvite::generateCode():$invite->access_code,'invitation_token'=>in_array($what,['link','both'])?Str::random(48):$invite->invitation_token,'is_active'=>true,'revoked_at'=>null]);$this->audit($group,$invite,'regenerated',['parts'=>$what,'previous_code'=>$old['code']]);if($request->expectsJson())return response()->json(['message'=>$invite->label.' invitation regenerated.','code'=>$invite->access_code,'url'=>$invite->url]);return back()->with('success',$invite->label.' invitation regenerated.'); }
    public function revoke(Group $group,GroupAccessInvite $invite) { $this->authorizeOwner($group);$this->child($group,$invite);$invite->update(['is_active'=>false,'revoked_at'=>now()]);$this->audit($group,$invite,'revoked');return back()->with('success','Invitation revoked. Existing members keep their access.'); }
    public function reactivate(Group $group,GroupAccessInvite $invite) { $this->authorizeOwner($group);$this->child($group,$invite);$invite->update(['is_active'=>true,'revoked_at'=>null]);$this->audit($group,$invite,'reactivated');return back()->with('success','Invitation reactivated.'); }
    public function print(Group $group,GroupAccessInvite $invite) { $this->authorizeOwner($group);$this->child($group,$invite);abort_unless($invite->isUsable(),410,'This invitation is no longer active.');return Inertia::render('Groups/InvitationPrint',['group'=>$group->only('name'),'invitation'=>['code'=>$invite->access_code,'share_url'=>$invite->url]]); }
    private function audit(Group $g,GroupAccessInvite $i,string $action,array $meta=[]): void { GroupAccessAudit::create(["group_id"=>$g->id,"access_invite_id"=>$i->id,"user_id"=>auth()->id(),"action"=>$action,"metadata"=>$meta,"created_at"=>now()]); app(AuditLogger::class)->log("invitation.".$action,$i,$g,[],[],$meta); }
}
