<?php
namespace App\Http\Controllers;
use App\Models\{BiometricConsent,BiometricDeletionRequest,EventFaceIndexRun,FaceSearchSubject,Group,MediaAsset};use Illuminate\Http\Request;use Illuminate\Support\Facades\Gate;use Inertia\Inertia;
class LensPicUiController extends Controller
{
    public function dashboard(Request$r){$owned=$r->user()->createdGroups()->withCount(['photos','members'])->latest()->limit(6)->get();return Inertia::render('Dashboard',['stats'=>['events'=>$r->user()->createdGroups()->count(),'photos'=>$r->user()->photos()->count(),'participants'=>$owned->sum('members_count'),'processing'=>MediaAsset::whereIn('group_id',$owned->pluck('id'))->whereIn('state',['queued','processing'])->count()],'events'=>$owned,'recent'=>[]]);}
    public function events(Request$r){$events=$r->user()->createdGroups()->withCount(['photos','members'])->latest()->get()->merge($r->user()->groups()->withCount(['photos','members'])->latest()->get())->unique('id')->values();return Inertia::render('Events/Index',['events'=>$events]);}
    public function create(Request$r){abort_unless($r->user()->account_type==='photographer'||$r->user()->isAdmin(),403);return Inertia::render('Events/Create');}
    public function show(Request$r,Group$group){Gate::authorize('view',$group);$admin=$group->isAdmin($r->user());if($admin)foreach([\App\Models\GroupAccessInvite::PARTIAL,\App\Models\GroupAccessInvite::FULL]as$type)\App\Models\GroupAccessInvite::firstOrCreate(['group_id'=>$group->id,'access_type'=>$type],['access_code'=>\App\Models\GroupAccessInvite::generateCode(),'invitation_token'=>\Illuminate\Support\Str::random(48),'created_by'=>$r->user()->id]);$photos=$group->photos()->with('mediaAsset')->latest()->limit(60)->get()->filter(fn($p)=>Gate::forUser($r->user())->allows('view',$p))->map(fn($p)=>['id'=>$p->id,'original_filename'=>$p->original_filename,'url'=>$p->mediaAsset?route('media.show',[$p->mediaAsset->uuid,'thumbnail']):$p->thumbnail_url])->values();return Inertia::render('Events/Show',['event'=>$group,'photos'=>$photos,'members'=>$admin?$group->members()->limit(20)->get(['users.id','name']):[],'invites'=>$admin?$group->accessInvites()->get()->map(fn($i)=>['id'=>$i->id,'label'=>$i->label,'access_code'=>$i->access_code]):[],'indexRun'=>$admin?EventFaceIndexRun::where('group_id',$group->id)->latest()->first():null]);}
    public function biometric(Request$r,Group$group){abort_unless($group->isMember($r->user())&&$group->face_recognition_enabled,403);$consent=BiometricConsent::where('group_id',$group->id)->where('user_id',$r->user()->id)->latest()->first();$subject=$consent?->subjects()->latest()->first();$deletion=BiometricDeletionRequest::where('group_id',$group->id)->where('user_id',$r->user()->id)->latest()->first();return Inertia::render('Biometric/ConsentSelfie',['event'=>$group->only('id','name'),'purpose'=>config('face.consent_purpose'),'consentVersion'=>config('face.consent_version'),'minorEnabled'=>(bool)config('face.minor_processing_enabled'),'consent'=>$consent?->only('uuid','state','privacy_notice_version','granted_at','withdrawn_at'),'subject'=>$subject?->only('uuid','state','outcome','deletion_state','expires_at'),'deletion'=>$deletion?->only('uuid','state','requested_at','completed_at')]);}
    public function myPhotos(Request$r,FaceSearchSubject$s){abort_unless($s->user_id===$r->user()->id,403);abort_unless($s->consent->state==='granted'&&$s->consent->group->isMember($r->user()),403);$rows=$s->results()->whereIn('review_state',['accepted','confirmed','unreviewed'])->with('asset.photo.group')->get();$authorizedMatchIds=$rows->whereIn('review_state',['accepted','confirmed'])->pluck('asset.photo_id')->filter()->map(fn($id)=>(int)$id)->values()->all();$r->session()->put('face_matches.'.$s->group_id,$authorizedMatchIds);$photos=$rows->filter(function($m)use($r){$p=$m->asset?->photo;return$p&&$m->asset->state==='completed'&&Gate::forUser($r->user())->allows('view',$p);})->map(fn($m)=>['match_id'=>$m->id,'photo_id'=>$m->asset->photo_id,'url'=>route('media.show',[$m->asset->uuid,'thumbnail']),'download_url'=>Gate::forUser($r->user())->allows('download',$m->asset)?route('media.show',[$m->asset->uuid,'original','download'=>1]):null,'similarity'=>(float)$m->similarity,'review_state'=>$m->review_state])->values();return Inertia::render('MyPhotos',['subject'=>$s->only('uuid','state','outcome','deletion_state','expires_at'),'photos'=>$photos,'event'=>$s->consent->group->only('id','name'),'partialError'=>$rows->count()>$photos->count(),'consent'=>$s->consent->only('uuid','state'),'deletion'=>BiometricDeletionRequest::where('group_id',$s->group_id)->where('user_id',$r->user()->id)->latest()->first()?->only('uuid','state')]);}
}
