<?php
namespace App\Http\Controllers;
use App\Models\{BiometricConsent,BiometricDeletionRequest,EventFaceIndexRun,FaceMatchResult,FaceSearchSubject,Group,MediaAsset,MediaExport,Photo,UploadBatch};use Illuminate\Http\Request;use Illuminate\Support\Facades\Gate;use Inertia\Inertia;
class LensPicUiController extends Controller
{
    public function dashboard(Request$r){$owned=$r->user()->createdGroups()->withCount(['photos','members'])->latest()->limit(6)->get();return Inertia::render('Dashboard',['stats'=>['groups'=>$r->user()->createdGroups()->count(),'photos'=>$r->user()->photos()->count(),'participants'=>$owned->sum('members_count'),'processing'=>MediaAsset::whereIn('group_id',$owned->pluck('id'))->whereIn('state',['queued','processing'])->count()],'groups'=>$owned,'recent'=>[]]);}
    public function events(Request$r){$groups=$r->user()->createdGroups()->withCount(['photos','members'])->latest()->get()->merge($r->user()->groups()->withCount(['photos','members'])->latest()->get())->unique('id')->values()->map(fn($g)=>['id'=>$g->id,'name'=>$g->name,'event_type'=>$g->event_type,'cover_url'=>$g->cover_photo_url,'is_active'=>$g->is_active,'photos_count'=>$g->photos_count,'members_count'=>$g->members_count,'created_at'=>$g->created_at,'updated_at'=>$g->updated_at]);return Inertia::render('Groups/Index',['groups'=>$groups]);}
    public function create(Request$r){Gate::authorize('create',Group::class);return Inertia::render('Groups/Create');}
    public function show(Request$r,Group$group){Gate::authorize('view',$group);$admin=$group->isAdmin($r->user());if($admin)foreach([\App\Models\GroupAccessInvite::PARTIAL,\App\Models\GroupAccessInvite::FULL]as$type)\App\Models\GroupAccessInvite::firstOrCreate(['group_id'=>$group->id,'access_type'=>$type],['access_code'=>\App\Models\GroupAccessInvite::generateCode(),'invitation_token'=>\Illuminate\Support\Str::random(48),'created_by'=>$r->user()->id]);$photos=$group->photos()->with('mediaAsset')->latest()->limit(60)->get()->filter(fn($p)=>Gate::forUser($r->user())->allows('view',$p))->map(fn($p)=>['id'=>$p->id,'original_filename'=>$p->original_filename,'url'=>$p->mediaAsset?route('media.show',[$p->mediaAsset->uuid,'thumbnail']):$p->thumbnail_url])->values();return Inertia::render('Groups/Show',['group'=>$group->only('id','name','location','privacy','is_active'),'canManage'=>$admin,'photos'=>$photos,'members'=>$admin?$group->members()->limit(20)->get(['users.id','name']):[],'invites'=>$admin?$group->accessInvites()->get()->map(fn($i)=>['id'=>$i->id,'label'=>$i->label,'access_code'=>$i->access_code]):[],'indexRun'=>$admin?EventFaceIndexRun::where('group_id',$group->id)->latest()->first():null]);}
    public function biometric(Request$r,Group$group){abort_unless($group->isMember($r->user())&&$group->face_recognition_enabled,403);$consent=BiometricConsent::where('group_id',$group->id)->where('user_id',$r->user()->id)->latest()->first();$subject=$consent?->subjects()->latest()->first();$deletion=BiometricDeletionRequest::where('group_id',$group->id)->where('user_id',$r->user()->id)->latest()->first();return Inertia::render('Biometric/ConsentSelfie',['event'=>$group->only('id','name'),'purpose'=>config('face.consent_purpose'),'consentVersion'=>config('face.consent_version'),'minorEnabled'=>(bool)config('face.minor_processing_enabled'),'consent'=>$consent?->only('uuid','state','privacy_notice_version','granted_at','withdrawn_at'),'subject'=>$subject?->only('uuid','state','outcome','deletion_state','expires_at'),'deletion'=>$deletion?->only('uuid','state','requested_at','completed_at')]);}
    public function myPhotos(Request$r,FaceSearchSubject$s){abort_unless($s->user_id===$r->user()->id,403);abort_unless($s->consent->state==='granted'&&$s->consent->group->isMember($r->user()),403);$rows=$s->results()->whereIn('review_state',['accepted','confirmed','unreviewed'])->with('asset.photo.group')->get();$authorizedMatchIds=$rows->whereIn('review_state',['accepted','confirmed'])->pluck('asset.photo_id')->filter()->map(fn($id)=>(int)$id)->values()->all();$r->session()->put('face_matches.'.$s->group_id,$authorizedMatchIds);$photos=$rows->filter(function($m)use($r){$p=$m->asset?->photo;return$p&&$m->asset->state==='completed'&&Gate::forUser($r->user())->allows('view',$p);})->map(fn($m)=>['match_id'=>$m->id,'photo_id'=>$m->asset->photo_id,'url'=>route('media.show',[$m->asset->uuid,'thumbnail']),'download_url'=>Gate::forUser($r->user())->allows('download',$m->asset)?route('media.show',[$m->asset->uuid,'original','download'=>1]):null,'similarity'=>(float)$m->similarity,'review_state'=>$m->review_state])->values();return Inertia::render('MyPhotos',['subject'=>$s->only('uuid','state','outcome','deletion_state','expires_at'),'photos'=>$photos,'event'=>$s->consent->group->only('id','name'),'partialError'=>$rows->count()>$photos->count(),'consent'=>$s->consent->only('uuid','state'),'deletion'=>BiometricDeletionRequest::where('group_id',$s->group_id)->where('user_id',$r->user()->id)->latest()->first()?->only('uuid','state')]);}
    public function photo(Request$r,Group$group,Photo$photo){abort_unless($photo->group_id===$group->id,404);Gate::authorize('view',$photo);$photo->load('mediaAsset','uploader','comments.user');return Inertia::render('Photos/Show',['event'=>$group->only('id','name','downloads_enabled'),'photo'=>['id'=>$photo->id,'url'=>$photo->mediaAsset?route('media.show',[$photo->mediaAsset->uuid,'optimized']):$photo->url,'download_url'=>Gate::allows('download',$photo)?route('photos.download',[$group,$photo]):null,'caption'=>$photo->caption,'original_filename'=>$photo->original_filename,'uploader'=>$photo->uploader?->name,'likes_count'=>$photo->likes()->count(),'liked'=>$photo->isLikedBy($r->user()),'comments'=>$photo->comments->map(fn($c)=>['id'=>$c->id,'body'=>$c->body,'author'=>$c->user?->name])]]);}
    public function operations(Request$r,Group$group){Gate::authorize('update',$group);$batches=UploadBatch::where('group_id',$group->id)->where('user_id',$r->user()->id)->with('files:id,upload_batch_id,client_filename,state,error,attempts')->latest()->limit(20)->get();$exports=MediaExport::where('group_id',$group->id)->where('user_id',$r->user()->id)->latest()->limit(20)->get();return Inertia::render('Groups/Operations',['group'=>$group->only('id','name'),'batches'=>$batches,'exports'=>$exports,'indexRun'=>EventFaceIndexRun::where('group_id',$group->id)->latest()->first()]);}
    public function reviews(Request$r,Group$group){Gate::authorize('manageMembers',$group);$reviews=FaceMatchResult::whereHas('asset',fn($q)=>$q->where('group_id',$group->id))->where('review_state','unreviewed')->with(['asset.photo','faceSearchSubject'])->latest()->get()->filter(fn($m)=>$m->asset?->state==='completed')->map(fn($m)=>['id'=>$m->id,'similarity'=>(float)$m->similarity,'photo_url'=>route('media.show',[$m->asset->uuid,'thumbnail']),'subject_uuid'=>$m->faceSearchSubject->uuid]);return Inertia::render('Groups/Reviews',['group'=>$group->only('id','name'),'reviews'=>$reviews]);}
    public function edit(Request$r,Group$group){return $this->renderSettings($group,'general');}
    public function settingsSection(Request$r,Group$group,string$section){return $this->renderSettings($group,$section);}
    private function renderSettings(Group$group,string$section){Gate::authorize('update',$group);return Inertia::render('Groups/Settings',['group'=>$group->only('id','name','description','event_type','event_date','location','privacy','is_active','membership_status','membership_limit','anyone_with_link_can_join','anonymous_access_mode','downloads_enabled','participants_can_edit_identity','allow_guest_upload','face_recognition_enabled','watermark_enabled','watermark_text'),'section'=>$section,'counts'=>['participants'=>$group->members()->count(),'folders'=>$group->folders()->count(),'favorites'=>$group->photos()->whereHas('likes')->count()]]);}
    public function members(Request$r,Group$group){Gate::authorize('manageMembers',$group);$members=$group->members()->get()->map(fn($u)=>['id'=>$u->id,'name'=>$u->name,'email'=>$u->email,'role'=>$u->pivot->role,'access_type'=>$u->pivot->access_type,'status'=>$u->pivot->membership_status]);return Inertia::render('Groups/Members',['group'=>$group->only('id','name'),'members'=>$members,'invites'=>$group->accessInvites()->get()->map(fn($i)=>['id'=>$i->id,'label'=>$i->label,'code'=>$i->access_code,'active'=>$i->isUsable(),'expires_at'=>$i->expires_at])]);}
    public function favorites(Request$r,Group$group){Gate::authorize('update',$group);$photos=$group->photos()->whereHas('likes')->withCount('likes')->with('mediaAsset')->get()->filter(fn($p)=>$p->mediaAsset?->state==='completed'&&Gate::forUser($r->user())->allows('view',$p))->map(fn($p)=>['id'=>$p->id,'filename'=>$p->original_filename,'favorites_count'=>$p->likes_count,'url'=>route('media.show',[$p->mediaAsset->uuid,'thumbnail'])])->values();return Inertia::render('Groups/Favorites',['group'=>$group->only('id','name'),'photos'=>$photos]);}
}
