<?php
namespace App\Http\Controllers;
use App\Http\Requests\UpdateSubscriptionPlanRequest;
use App\Models\{RazorpayOrder,SubscriptionFeature,SubscriptionPlan,SubscriptionPlanAudit,SubscriptionPlanPrice};
use App\Services\Billing\PlanCatalog;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;
class SuperAdminSubscriptionPlanController extends Controller
{
 public function index(){return view('super-admin.plans.index',['plans'=>SubscriptionPlan::with(['prices','features'])->withCount(['subscriptions as current_subscribers_count'=>fn($q)=>$q->where('status','active')->where(fn($active)=>$active->whereNull('expires_at')->orWhere('expires_at','>',now()))])->orderBy('display_order')->get()]);}
 public function edit(SubscriptionPlan$plan){$plan->load(['prices','features']);return view('super-admin.plans.edit',['plan'=>$plan,'features'=>SubscriptionFeature::where('is_active',true)->orderBy('display_order')->get(),'presented'=>app(PlanCatalog::class)->present($plan)]);}
 public function update(UpdateSubscriptionPlanRequest$r,SubscriptionPlan$plan){$data=$r->validated();$before=app(PlanCatalog::class)->present($plan);DB::transaction(function()use($r,$plan,$data,$before){$plan->lockForUpdate();$plan->update(collect($data)->only(['name','short_description','rank','display_order','is_active','is_public','is_recommended','badge_text','badge_style','photo_storage_limit','photo_reuse_limit','video_storage_mb','team_seat_limit','group_limit','guest_limit'])->all()+['version'=>$plan->version+1]);foreach(['quarterly','yearly']as$interval){$paise=$this->paise(data_get($data,"prices.$interval"));$comparison=$this->paise(data_get($data,"comparison_prices.$interval"),true);$current=$plan->currentPrice($interval);$changed=!$current||$current->base_amount_paise!==$paise||$current->gst_rate_basis_points!==(int)$data['gst_basis_points']||$current->comparison_amount_paise!==$comparison||$current->razorpay_plan_id!==data_get($data,"razorpay_plan_ids.$interval");if($changed){$current?->update(['is_active'=>false,'effective_until'=>now()]);$plan->prices()->create(['billing_interval'=>$interval,'currency'=>'INR','base_amount_paise'=>$paise,'gst_rate_basis_points'=>$data['gst_basis_points'],'comparison_amount_paise'=>$comparison,'is_active'=>true,'razorpay_plan_id'=>data_get($data,"razorpay_plan_ids.$interval"),'effective_from'=>now()]);}}foreach(SubscriptionFeature::where('category','!=','limits')->get()as$f){$values=$data['features'][$f->id]??[];$plan->features()->syncWithoutDetaching([$f->id=>['is_included'=>(bool)($values['included']??false),'value_boolean'=>(bool)($values['included']??false),'is_addon'=>(bool)($values['is_addon']??false),'addon_price_paise'=>$this->paise($values['addon_price']??null,true),'display_label'=>$values['display_label']??$f->name,'display_order'=>$values['display_order']??$f->display_order]]);}SubscriptionPlanAudit::create(['subscription_plan_id'=>$plan->id,'actor_id'=>$r->user()->id,'action'=>'plan_published','request_id'=>(string)Str::uuid(),'previous_values'=>$before,'new_values'=>app(PlanCatalog::class)->present($plan->fresh())]);});return redirect()->route('super-admin.plans.edit',$plan)->with('success','Plan published. New checkouts now use this version.');}
 public function toggle(Request$r,SubscriptionPlan$plan){$old=$plan->is_active;$plan->update(['is_active'=>!$old,'version'=>$plan->version+1]);SubscriptionPlanAudit::create(['subscription_plan_id'=>$plan->id,'actor_id'=>$r->user()->id,'action'=>$plan->is_active?'plan_activated':'plan_deactivated','request_id'=>(string)Str::uuid(),'previous_values'=>['is_active'=>$old],'new_values'=>['is_active'=>$plan->is_active]]);return back()->with('success','Plan status updated.');}
 public function preview(SubscriptionPlan$plan){return view('marketing.pricing',['title'=>'Plan card preview','description'=>'Production pricing-card preview using published database records.','plans'=>[app(PlanCatalog::class)->present($plan)]]);}
 public function audits(SubscriptionPlan$plan){return view('super-admin.plans.audits',['plan'=>$plan,'audits'=>$plan->audits()->with('actor')->latest()->paginate(50)]);}
 public function features(){return view('super-admin.plans.features',['features'=>SubscriptionFeature::orderBy('display_order')->get(),'icons'=>$this->icons()]);}
 public function updateFeature(Request$r,SubscriptionFeature$feature){$data=$r->validate(['name'=>['required','string','max:120'],'description'=>['nullable','string','max:500'],'icon'=>['required',Rule::in($this->icons())],'category'=>['required','string','max:50'],'display_order'=>['required','integer','between:0,65535'],'is_active'=>['required','boolean']]);$old=$feature->toArray();$feature->update($data);SubscriptionPlanAudit::create(['actor_id'=>$r->user()->id,'action'=>'feature_updated','request_id'=>(string)Str::uuid(),'previous_values'=>$old,'new_values'=>$feature->fresh()->toArray()]);return back()->with('success','Feature updated.');}
 public function payments(){return view('super-admin.plans.payments',['orders'=>RazorpayOrder::with('user')->latest()->paginate(50)]);}
 private function paise($value,bool$nullable=false):?int{if(($value===null||$value==='')&&$nullable)return null;[$whole,$decimal]=array_pad(explode('.',(string)$value,2),2,'');return((int)$whole*100)+(int)str_pad($decimal,2,'0');}
 private function icons():array{return['images','refresh','video','palette','heart','download','sliders','layout-grid','chart-users','users','stamp','globe','shield-users','lock','share','scan-face','headphones'];}
}
