<?php
namespace App\Http\Controllers;
use App\Mail\TeamInvitationMail;
use App\Models\{StudioTeamMembership,TeamInvitation,User};
use App\Services\{AuditLogger};
use App\Services\Team\{TeamAuthorization,TeamSeatUsage};
use Illuminate\Http\Request;
use Illuminate\Support\Facades\{DB,Mail,RateLimiter};
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;
use Illuminate\Validation\ValidationException;
use Inertia\Inertia;

class TeamLoginController extends Controller
{
 public function __construct(private TeamAuthorization$authz,private TeamSeatUsage$seats,private AuditLogger$audit){}
 private function owner(Request$r):User{$owner=$this->authz->ownerFor($r->user());abort_unless($owner&&$this->authz->canManageTeam($r->user(),$owner),403);return$owner;}
 private function member(User$owner,StudioTeamMembership$m):void{abort_unless($m->studio_owner_id===$owner->id,404);}
 private function invite(User$owner,TeamInvitation$i):void{abort_unless($i->studio_owner_id===$owner->id,404);}
 public function index(Request$r){$owner=$this->owner($r);StudioTeamMembership::where('user_id',$r->user()->id)->where('status','active')->update(['last_active_at'=>now()]);$members=$owner->studioTeamMembers()->with('user:id,name,email')->latest()->get()->map(fn($m)=>['uuid'=>$m->uuid,'name'=>$m->user->name,'email'=>$m->user->email,'role'=>$m->role,'status'=>$m->status,'invitation_status'=>'accepted','last_active_at'=>$m->last_active_at]);$invites=$owner->teamInvitations()->whereIn('status',['pending','revoked'])->latest()->get()->map(fn($i)=>['uuid'=>$i->uuid,'name'=>$i->name,'email'=>$i->email,'role'=>$i->role,'status'=>$i->effectiveStatus()==='pending'?'invited':$i->effectiveStatus(),'invitation_status'=>$i->effectiveStatus(),'last_active_at'=>null]);return Inertia::render('Settings/TeamLogin',['section'=>'team-login','owner'=>['name'=>$owner->name,'studio_name'=>$owner->studio_name],'canManageTeam'=>true,'canInviteTeamMembers'=>true,'members'=>$members->concat($invites)->values(),'seatUsage'=>$this->seats->summary($owner),'roles'=>TeamAuthorization::ROLES,'permissions'=>TeamAuthorization::MATRIX]);}
 public function store(Request$r){$owner=$this->owner($r);$r->merge(['email'=>Str::lower(trim((string)$r->input('email')))]);$data=$r->validate(['name'=>['required','string','max:100'],'email'=>['required','email:rfc','max:255'],'role'=>['required',Rule::in(TeamAuthorization::ROLES)],'permissions'=>['nullable','array'],'permissions.*'=>['string']]);if($data['email']===$owner->email)throw ValidationException::withMessages(['email'=>'You cannot invite your own email address.']);if($this->seats->summary($owner)['reached'])throw ValidationException::withMessages(['email'=>"Your current plan's team-member limit has been reached."]);if($owner->studioTeamMembers()->whereHas('user',fn($q)=>$q->where('email',$data['email']))->whereIn('status',['active','suspended'])->exists())throw ValidationException::withMessages(['email'=>'This person is already a team member.']);if($owner->teamInvitations()->where('email',$data['email'])->where('status','pending')->where('expires_at','>',now())->exists())throw ValidationException::withMessages(['email'=>'An active invitation already exists for this email.']);$raw=Str::random(64);$invitation=$owner->teamInvitations()->create(['uuid'=>(string)Str::uuid(),'name'=>trim($data['name']),'email'=>$data['email'],'role'=>$data['role'],'permissions'=>$this->authz->permissionsFor($data['role'],$data['permissions']??null),'token_hash'=>hash('sha256',$raw),'status'=>'pending','invited_by'=>$r->user()->id,'expires_at'=>now()->addDays(7),'last_sent_at'=>now()]);$this->send($invitation,$raw);$this->audit->log('team.invitation.sent',$invitation,null,[],[],['studio_owner_id'=>$owner->id,'email'=>$invitation->email,'role'=>$invitation->role]);return back()->with('success','Team member invitation sent successfully.');}
 public function resend(Request$r,TeamInvitation$invitation){$owner=$this->owner($r);$this->invite($owner,$invitation);abort_unless($invitation->effectiveStatus()==='pending',422);$key='team-resend:'.$owner->id.':'.$invitation->uuid;if(RateLimiter::tooManyAttempts($key,3))throw ValidationException::withMessages(['invitation'=>'Please wait before resending this invitation.']);RateLimiter::hit($key,3600);$raw=Str::random(64);$invitation->update(['token_hash'=>hash('sha256',$raw),'expires_at'=>now()->addDays(7),'last_sent_at'=>now()]);$this->send($invitation,$raw);$this->audit->log('team.invitation.resent',$invitation,null,[],[],['studio_owner_id'=>$owner->id]);return back()->with('success','Invitation resent successfully.');}
 public function revoke(Request$r,TeamInvitation$invitation){$owner=$this->owner($r);$this->invite($owner,$invitation);abort_unless($invitation->effectiveStatus()==='pending',422);$invitation->update(['status'=>'revoked','revoked_at'=>now()]);$this->audit->log('team.invitation.revoked',$invitation,null,[],[],['studio_owner_id'=>$owner->id]);return back()->with('success','Invitation revoked.');}
 public function role(Request$r,StudioTeamMembership$membership){$owner=$this->owner($r);$this->member($owner,$membership);abort_if($membership->user_id===$r->user()->id,422);$data=$r->validate(['role'=>['required',Rule::in(TeamAuthorization::ROLES)],'permissions'=>['nullable','array'],'permissions.*'=>['string']]);$before=['role'=>$membership->role,'permissions'=>$membership->permissions];$membership->update(['role'=>$data['role'],'permissions'=>$this->authz->permissionsFor($data['role'],$data['permissions']??null)]);$this->audit->log('team.member.role_changed',$membership,null,$before,['role'=>$membership->role,'permissions'=>$membership->permissions],['studio_owner_id'=>$owner->id]);return back()->with('success','Team member role updated.');}
 public function status(Request$r,StudioTeamMembership$membership){$owner=$this->owner($r);$this->member($owner,$membership);abort_if($membership->user_id===$r->user()->id,422);$data=$r->validate(['status'=>['required',Rule::in(['active','suspended'])]]);$before=$membership->status;$membership->update(['status'=>$data['status'],'suspended_at'=>$data['status']==='suspended'?now():null]);$this->audit->log('team.member.'.$data['status'],$membership,null,['status'=>$before],['status'=>$data['status']],['studio_owner_id'=>$owner->id]);return back()->with('success',$data['status']==='active'?'Team member activated.':'Team member suspended.');}
 public function destroy(Request$r,StudioTeamMembership$membership){$owner=$this->owner($r);$this->member($owner,$membership);abort_if($membership->user_id===$r->user()->id,422);$target=$membership->user;$this->audit->log('team.member.removed',$membership,null,['role'=>$membership->role,'status'=>$membership->status],[],['studio_owner_id'=>$owner->id,'target_user_id'=>$target->id]);$membership->delete();return back()->with('success','Team member removed.');}
 private function send(TeamInvitation$i,string$raw):void{try{Mail::to($i->email)->queue(new TeamInvitationMail($i->load(['owner','inviter']),route('team-invitations.show',[$i,$raw])));}catch(\Throwable$e){report($e);throw ValidationException::withMessages(['email'=>'The invitation could not be queued. Please try again.']);}}
}
