@extends('super-admin.layout') @section('title','Edit '.$plan->name) @section('content')
<div class="page-header"><div><div class="admin-breadcrumb">Super Admin / Plans / {{$plan->name}}</div><h1 class="page-title">Edit {{$plan->name}}</h1><p>Stable code: <code>{{$plan->code}}</code> · Version {{$plan->version}}</p></div><a class="btn btn-outline" href="{{route('super-admin.plans.index')}}">Back to Plans</a></div>
<nav style="display:flex;gap:.5rem;flex-wrap:wrap;margin-bottom:1rem" aria-label="Plan sections"><a class="btn btn-outline btn-sm" href="#details">Plan</a><a class="btn btn-outline btn-sm" href="#prices">Prices</a><a class="btn btn-outline btn-sm" href="#features">Features</a><a class="btn btn-outline btn-sm" href="#features">Add-ons</a><a class="btn btn-outline btn-sm" href="{{route('super-admin.plans.preview',$plan)}}">Preview</a><a class="btn btn-outline btn-sm" href="{{route('super-admin.plans.audits',$plan)}}">Change History</a></nav>
@if(session('success'))<div class="alert alert-success">{{session('success')}}</div>@endif
@if($errors->any())<div class="alert alert-danger"><strong>Plan was not saved.</strong><ul>@foreach($errors->all() as $e)<li>{{$e}}</li>@endforeach</ul></div>@endif
@php($quarterly=$plan->currentPrice('quarterly')) @php($yearly=$plan->currentPrice('yearly'))
<form method="POST" action="{{route('super-admin.plans.update',$plan)}}" id="plan-form">@csrf @method('PUT')
<div class="card" id="details"><div class="card-header"><strong>Plan information</strong></div><div class="card-body grid grid-2">
@foreach([['name','Display name',$plan->name],['short_description','Short description',$plan->short_description],['rank','Rank',$plan->rank],['display_order','Display order',$plan->display_order],['badge_text','Badge text',$plan->badge_text]] as [$key,$label,$value])<div class="form-group"><label for="{{$key}}">{{$label}}</label><input id="{{$key}}" name="{{$key}}" value="{{old($key,$value)}}">@error($key)<span class="text-danger">{{$message}}</span>@enderror</div>@endforeach
<div class="form-group"><label>Badge style</label><select name="badge_style"><option value="">None</option>@foreach(['primary','success','warning'] as $v)<option @selected(old('badge_style',$plan->badge_style)===$v)>{{$v}}</option>@endforeach</select></div>
@foreach(['is_active'=>'Active','is_public'=>'Public','is_recommended'=>'Recommended'] as $key=>$label)<label><input type="hidden" name="{{$key}}" value="0"><input type="checkbox" name="{{$key}}" value="1" @checked(old($key,$plan->$key))> {{$label}}</label>@endforeach
</div></div>
<div class="card" id="prices" style="margin-top:1rem"><div class="card-header"><strong>Prices and GST</strong></div><div class="card-body grid grid-2">
@foreach(['quarterly'=>$quarterly,'yearly'=>$yearly] as $interval=>$record)<div><div class="form-group"><label>{{ucfirst($interval)}} base price (₹)</label><input class="money-input" data-preview="{{$interval}}" name="prices[{{$interval}}]" value="{{old("prices.$interval",$record?number_format($record->base_amount_paise/100,2,'.',''):'')}}">@error("prices.$interval")<span class="text-danger">{{$message}}</span>@enderror</div><div class="form-group"><label>Comparison price (₹)</label><input name="comparison_prices[{{$interval}}]" value="{{old("comparison_prices.$interval",$record?->comparison_amount_paise?number_format($record->comparison_amount_paise/100,2,'.',''):'')}}"></div><div class="form-group"><label>Razorpay Plan ID (optional)</label><input name="razorpay_plan_ids[{{$interval}}]" value="{{old("razorpay_plan_ids.$interval",$record?->razorpay_plan_id)}}"></div><div class="price-preview" id="preview-{{$interval}}"></div></div>@endforeach
<div class="form-group"><label>GST rate (basis points)</label><input id="gst" name="gst_basis_points" value="{{old('gst_basis_points',$quarterly?->gst_rate_basis_points??1800)}}"><small>1800 = 18%</small>@error('gst_basis_points')<span class="text-danger">{{$message}}</span>@enderror</div>
</div></div>
<div class="card" style="margin-top:1rem"><div class="card-header"><strong>Limits</strong></div><div class="card-body grid grid-3">@foreach(['photo_storage_limit'=>'Photo storage','photo_reuse_limit'=>'Photo reuse','video_storage_mb'=>'Video storage MB','team_seat_limit'=>'Team seats','group_limit'=>'Group limit','guest_limit'=>'Guest limit'] as $key=>$label)<div class="form-group"><label>{{$label}}</label><input name="{{$key}}" value="{{old($key,$plan->$key)}}"><small>Blank means unlimited only for nullable limits.</small>@error($key)<span class="text-danger">{{$message}}</span>@enderror</div>@endforeach</div></div>
<div class="card" id="features" style="margin-top:1rem"><div class="card-header"><strong>Feature assignments and add-ons</strong></div><div class="card-body" style="overflow:auto"><table class="table"><thead><tr><th>Feature</th><th>Icon</th><th>Included</th><th>Add-on</th><th>Add-on ₹</th><th>Display label</th><th>Order</th></tr></thead><tbody>@foreach($features as $feature) @php($pivot=$plan->features->firstWhere('id',$feature->id)?->pivot)<tr><td><code>{{$feature->code}}</code><br>{{$feature->name}}</td><td>{{$feature->icon}}</td><td><input type="hidden" name="features[{{$feature->id}}][included]" value="0"><input type="checkbox" name="features[{{$feature->id}}][included]" value="1" @checked(old("features.$feature->id.included",$pivot?->is_included))></td><td><input type="hidden" name="features[{{$feature->id}}][is_addon]" value="0"><input type="checkbox" name="features[{{$feature->id}}][is_addon]" value="1" @checked(old("features.$feature->id.is_addon",$pivot?->is_addon))></td><td><input name="features[{{$feature->id}}][addon_price]" value="{{old("features.$feature->id.addon_price",$pivot?->addon_price_paise?number_format($pivot->addon_price_paise/100,2,'.',''):'')}}"></td><td><input name="features[{{$feature->id}}][display_label]" value="{{old("features.$feature->id.display_label",$pivot?->display_label?:$feature->name)}}"></td><td><input name="features[{{$feature->id}}][display_order]" value="{{old("features.$feature->id.display_order",$pivot?->display_order??$feature->display_order)}}" style="width:70px"></td></tr>@endforeach</tbody></table></div></div>
<div style="position:sticky;bottom:0;background:white;padding:1rem;margin-top:1rem;border-top:1px solid #ddd"><button class="btn btn-primary" type="submit">Publish Plan Changes</button> <a class="btn btn-outline" href="{{route('super-admin.plans.preview',$plan)}}">Preview Published Card</a></div></form>
<script>function preview(i){const el=document.querySelector(`[data-preview="${i}"]`),b=Math.round(Number(el.value||0)*100),rate=Number(document.getElementById('gst').value||0),g=Math.round(b*rate/10000);document.getElementById('preview-'+i).textContent=`Base: ₹${(b/100).toLocaleString('en-IN',{minimumFractionDigits:2})} · GST: ₹${(g/100).toLocaleString('en-IN',{minimumFractionDigits:2})} · Customer pays: ₹${((b+g)/100).toLocaleString('en-IN',{minimumFractionDigits:2})}`;}document.querySelectorAll('.money-input').forEach(e=>e.addEventListener('input',()=>preview(e.dataset.preview)));document.getElementById('gst').addEventListener('input',()=>document.querySelectorAll('.money-input').forEach(e=>preview(e.dataset.preview)));preview('quarterly');preview('yearly');document.getElementById('plan-form').addEventListener('submit',event=>{if(!confirm('Publish these live plan changes? Price, GST, quota, Razorpay ID and feature changes affect new purchases.'))event.preventDefault()});</script>
@endsection
