<!doctype html><html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{{ $title }} · LensPic</title><meta name="description" content="{{ $description }}"><link rel="canonical" href="{{ url()->current() }}">
<meta property="og:type" content="website"><meta property="og:site_name" content="LensPic"><meta property="og:title" content="{{ $title }}"><meta property="og:description" content="{{ $description }}"><meta property="og:url" content="{{ url()->current() }}"><meta name="twitter:card" content="summary_large_image">
@if(app()->environment() !== 'production')<meta name="robots" content="noindex,nofollow">@endif
@vite(['resources/css/app.css','resources/js/marketing.js']) @stack('head')</head>
<body class="marketing-body"><a class="skip-link" href="#main-content">Skip to main content</a>
<header class="marketing-header" data-public-menu><div class="marketing-container header-inner">
<a class="brand" href="{{ route('home') }}" aria-label="LensPic home"><span class="brand-mark" aria-hidden="true">L</span><span>LensPic</span></a>
<button class="menu-toggle" type="button" aria-expanded="false" aria-controls="public-navigation"><span class="sr-only">Open navigation</span><span aria-hidden="true">☰</span></button>
<nav id="public-navigation" class="public-nav" aria-label="Main navigation">
<a @class(['active'=>request()->routeIs('home')]) href="{{ route('home') }}">Home</a>@include('marketing.partials.solutions-menu')<a @class(['active'=>request()->routeIs('marketing.features')]) href="{{ route('marketing.features') }}">Features</a><a @class(['active'=>request()->routeIs('marketing.how-it-works')]) href="{{ route('marketing.how-it-works') }}">How It Works</a><a @class(['active'=>request()->routeIs('pricing')]) href="{{ route('pricing') }}">Pricing</a><a @class(['active'=>request()->routeIs('marketing.about')]) href="{{ route('marketing.about') }}">About Us</a><a @class(['active'=>request()->routeIs('marketing.contact')]) href="{{ route('marketing.contact') }}">Contact Us</a>
<div class="mobile-nav-actions">@auth<a class="button button-primary" href="{{ route('dashboard') }}">Go to workspace</a>@else<a class="button button-text" href="{{ route('login') }}">Login</a><a class="button button-primary" href="{{ route('register') }}">Get Started</a>@endauth</div>
</nav><div class="header-actions">@auth<a class="button button-primary" href="{{ route('dashboard') }}">Go to workspace</a>@else<a class="button button-text join-group-action" href="{{ route('marketing.join') }}">Join a group</a><a class="button button-text" href="{{ route('login') }}">Login</a><a class="button button-primary" href="{{ route('register') }}">Get started</a>@endauth</div>
</div></header><main id="main-content">@yield('content')</main>
<footer class="marketing-footer"><div class="marketing-container footer-grid">
<div><a class="brand" href="{{ route('home') }}"><span class="brand-mark">L</span><span>LensPic</span></a><p>Private, organized group-photo delivery for photographers, studios and group owners.</p></div>
<div><h2>Product</h2><a href="{{ route('marketing.features') }}">Features</a><a href="{{ route('marketing.how-it-works') }}">How it works</a><a href="{{ route('solutions.photographers') }}">For Photographers</a><a href="{{ route('marketing.guests') }}">Group members</a><a href="{{ route('pricing') }}">Pricing</a></div>
<div><h2>Company</h2><a href="{{ route('marketing.about') }}">About us</a><a href="{{ route('marketing.contact') }}">Contact us</a><a href="{{ route('marketing.blog') }}">Blog</a><a href="{{ route('marketing.faqs') }}">FAQs</a><a href="{{ route('marketing.help') }}">Help and support</a></div>
<div><h2>Legal</h2><a href="{{ route('marketing.privacy') }}">Privacy policy</a><a href="{{ route('marketing.terms') }}">Terms</a><a href="{{ route('marketing.cookies') }}">Cookie policy</a><a href="{{ route('marketing.refunds') }}">Refund policy</a><a href="{{ route('marketing.biometric-consent') }}">Biometric consent</a><a href="{{ route('marketing.deletion') }}">Data deletion</a></div>
<div><h2>Account</h2>@guest<a href="{{ route('login') }}">Login</a><a href="{{ route('register') }}">Register</a>@endguest<a href="{{ route('dashboard') }}">Workspace</a>@if(config('marketing.contact.support_email'))<a href="mailto:{{ config('marketing.contact.support_email') }}">{{ config('marketing.contact.support_email') }}</a>@endif</div>
</div><div class="marketing-container footer-bottom"><span>© {{ now()->year }} LensPic. All rights reserved.</span><span>Responsive web experience—no separate member app required.</span></div></footer>@stack('scripts')</body></html>
