@extends('super-admin.layout')
@section('title', 'Dashboard')
@section('content')
<div class="page-header"><div><div class="admin-breadcrumb">Super Admin / Dashboard</div><h1 class="page-title">Administrative Overview</h1><p>Live platform, billing and processing totals.</p></div><div style="display:flex;gap:.5rem;flex-wrap:wrap"><a class="btn btn-primary" href="{{ route('super-admin.plans.index') }}"><i class="fa-solid fa-layer-group"></i> Manage Plans</a><a class="btn btn-outline" href="{{ route('super-admin.subscriptions') }}">View Subscriptions</a></div></div>
@php($cards=[['Total Users',$stats['total_users'],'fa-users'],['Photographers',$stats['photographers'],'fa-camera'],['Active Photographers',$stats['active_photographers'],'fa-user-check'],['Groups',$stats['total_groups'],'fa-images'],['Media Assets',$stats['total_media'],'fa-photo-film'],['Storage Used',\Illuminate\Support\Number::fileSize($stats['storage_bytes']),'fa-hard-drive'],['Active Subscriptions',$stats['active_subscriptions'],'fa-credit-card'],['Expiring in 30 Days',$stats['expiring_subscriptions'],'fa-clock'],['Successful Payments This Month',$stats['monthly_payments'],'fa-circle-check'],['Failed Payments',$stats['failed_payments'],'fa-circle-xmark'],['Pending Payments',$stats['pending_payments'],'fa-hourglass-half'],['Queue Backlog',$stats['queue_backlog'],'fa-list-check'],['Failed Processing Jobs',$stats['failed_jobs'],'fa-triangle-exclamation']])
<div class="grid grid-4">@foreach($cards as [$label,$value,$icon])<div class="stat-card"><div class="stat-icon" style="background:rgba(99,102,241,.15);color:#a5b4fc"><i class="fa-solid {{ $icon }}"></i></div><div><div class="stat-num">{{ is_numeric($value)?number_format($value):$value }}</div><div class="stat-label">{{ $label }}</div></div></div>@endforeach</div>
<div class="card" style="margin-top:1.5rem"><div class="card-header"><i class="fa-solid fa-layer-group"></i> Plans Health <a href="{{ route('super-admin.plans.index') }}" class="btn btn-primary btn-sm" style="margin-left:auto">Manage Plans</a></div><div class="card-body"><div class="grid grid-3"><div><div class="stat-num">{{ $stats['active_public_plans'] }}</div><div class="stat-label">Active public plans</div></div><div><div class="stat-num">{{ $stats['inactive_plans'] }}</div><div class="stat-label">Inactive plans</div></div><div><div class="stat-num">{{ $stats['configured_prices'] }}</div><div class="stat-label">Active quarterly/yearly prices</div></div><div><div class="stat-num">{{ $stats['plans_missing_prices'] }}</div><div class="stat-label">Plans missing prices</div></div><div><div class="stat-num">{{ $stats['plans_missing_features'] }}</div><div class="stat-label">Plans missing feature assignments</div></div><div><div class="stat-num" style="font-size:1rem">{{ $stats['last_plan_update'] ? \Illuminate\Support\Carbon::parse($stats['last_plan_update'])->format('d M Y, H:i') : 'No updates' }}</div><div class="stat-label">Last plan update</div></div></div></div></div>
<div class="grid grid-2" style="margin-top:1.5rem"><div class="card"><div class="card-header">Recent Users <a href="{{ route('super-admin.users') }}" class="btn btn-outline btn-sm" style="margin-left:auto">View All</a></div><div class="table-wrap"><table><thead><tr><th>User</th><th>Role</th><th>Joined</th></tr></thead><tbody>@forelse($recentUsers as $user)<tr><td>{{ $user->name }}<br><span style="color:var(--muted);font-size:11px">{{ $user->email }}</span></td><td>{{ str($user->role ?: $user->account_type ?: 'user')->replace('_',' ')->title() }}</td><td>{{ $user->created_at->format('d M Y') }}</td></tr>@empty<tr><td colspan="3">No users yet.</td></tr>@endforelse</tbody></table></div></div><div class="card"><div class="card-header">Recent Administrative Activity</div><div class="table-wrap"><table><thead><tr><th>Action</th><th>Administrator</th><th>Time</th></tr></thead><tbody>@forelse($recentActivity as $audit)<tr><td>{{ str($audit->action)->replace('_',' ')->title() }}</td><td>{{ $audit->actor?->name ?? 'System' }}</td><td>{{ $audit->created_at->diffForHumans() }}</td></tr>@empty<tr><td colspan="3">No administrative plan activity yet.</td></tr>@endforelse</tbody></table></div></div></div>
@endsection
