<script setup>
import { Link, usePage } from '@inertiajs/vue3'
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import UiAlert from '../Components/UiAlert.vue'
const page=usePage(),open=ref(false),user=computed(()=>page.props.auth?.user),unread=ref(Number(page.props.notificationUnreadCount||0)),canCreateGroups=computed(()=>page.props.permissions?.createGroups===true),isSuperAdmin=computed(()=>user.value?.role==='super_admin'),path=computed(()=>page.url.split('?')[0]);let poll
watch(()=>page.props.notificationUnreadCount,value=>unread.value=Number(value||0));const refreshUnread=async()=>{if(document.hidden)return;try{const response=await fetch('/notifications/unread-count',{headers:{Accept:'application/json'},credentials:'same-origin'});if(response.ok)unread.value=Number((await response.json()).count||0)}catch{}}
onMounted(()=>poll=window.setInterval(refreshUnread,60000));onBeforeUnmount(()=>window.clearInterval(poll))
const analytics=computed(()=>page.props.analyticsAccess),nav=computed(()=>[{label:'Dashboard',href:'/dashboard'},{label:'Groups',href:'/groups'},...(analytics.value?.eligible?[{label:'Analytics',href:analytics.value.href,badge:analytics.value.label,locked:!analytics.value.enabled}]:[]),{label:'Notifications',href:'/notifications'},{label:'Account Settings',href:'/settings'}])
const active=href=>href==='/groups'?path.value.startsWith('/groups')&&path.value!=='/groups/create':path.value===href
</script>
<template><div class="min-h-screen bg-canvas"><a href="#main-content" class="fixed left-3 top-3 z-[110] -translate-y-20 rounded-lg bg-white px-4 py-2 font-semibold shadow focus:translate-y-0">Skip to content</a>
<aside class="fixed inset-y-0 left-0 z-40 hidden w-64 border-r border-white/10 bg-ink px-5 py-6 text-white lg:block"><Link href="/dashboard" class="font-display text-2xl font-bold">Lens<span class="text-indigo-300">Pic</span></Link><p class="mt-2 text-xs text-white/50">Creative control room</p><nav class="mt-10 space-y-1" aria-label="Primary navigation"><Link v-for="n in nav" :key="n.label" :href="n.href" :class="['flex items-center justify-between rounded-xl px-4 py-3 text-sm font-medium transition',active(n.href)?'bg-indigo text-white':'text-white/70 hover:bg-white/10 hover:text-white']"><span>{{n.locked?'Lock · ':''}}{{n.label}}</span><span v-if="n.badge" class="rounded-full bg-white/10 px-2 py-0.5 text-[10px]">{{n.badge}}</span></Link></nav><div class="absolute bottom-6 left-5 right-5 rounded-xl border border-white/10 bg-white/5 p-4"><p class="truncate text-sm font-semibold">{{user?.name}}</p><p class="mt-1 text-xs capitalize text-white/50">{{user?.account_type||user?.role}}</p><Link v-if="isSuperAdmin" href="/super-admin/dashboard" class="mt-3 block rounded-lg border border-indigo-300/30 px-3 py-2 text-center text-xs font-semibold text-indigo-200 hover:bg-white/10">Admin Console</Link><form method="POST" action="/logout"><input type="hidden" name="_token" :value="page.props.csrfToken"><button type="submit" class="mt-3 flex w-full items-center justify-center gap-2 rounded-lg border border-red-400/30 bg-red-500/10 px-3 py-2 text-xs font-semibold text-red-300 hover:bg-red-500 hover:text-white focus:outline-none focus:ring-2 focus:ring-red-300"><span aria-hidden="true">↪</span> Logout</button></form></div></aside>
<header class="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-slate-200 bg-white/90 px-4 backdrop-blur lg:ml-64 lg:px-8"><button class="btn-ghost lg:hidden" :aria-expanded="open" aria-controls="mobile-navigation" @click="open=!open"><span class="sr-only">Toggle navigation</span>{{open?'Close':'Menu'}}</button><Link href="/dashboard" class="font-display font-bold lg:hidden">Lens<span class="text-indigo">Pic</span></Link><p class="hidden text-xs font-medium uppercase tracking-wider text-slate-500 lg:block">LensPic workspace</p><div class="flex items-center gap-3"><Link href="/notifications" class="relative grid h-10 w-10 place-items-center rounded-full border border-slate-200 text-xl hover:bg-slate-50" aria-label="Notifications" :aria-description="`${unread} unread notifications`"><span aria-hidden="true">🔔</span><span v-if="unread" class="absolute -right-1 -top-1 min-w-5 rounded-full bg-indigo px-1 text-center text-xs font-bold leading-5 text-white" aria-hidden="true">{{unread>99?'99+':unread}}</span></Link><a v-if="canCreateGroups" href="/groups/create" class="btn-primary">New Group</a></div></header>
<nav v-if="open" id="mobile-navigation" class="sticky top-16 z-20 border-b border-slate-200 bg-white p-3 shadow-lg lg:hidden" aria-label="Mobile navigation"><Link v-for="n in nav" :key="n.label" :href="n.href" :class="['flex items-center justify-between rounded-xl px-4 py-3 text-sm font-semibold',active(n.href)?'bg-indigo/10 text-indigo':'text-slate-600']" @click="open=false"><span>{{n.locked?'Lock · ':''}}{{n.label}}</span><span v-if="n.badge" class="text-xs">{{n.badge}}</span></Link><Link v-if="isSuperAdmin" href="/super-admin/dashboard" class="block rounded-xl px-4 py-3 text-sm font-semibold text-indigo" @click="open=false">Admin Console</Link><form method="POST" action="/logout"><input type="hidden" name="_token" :value="page.props.csrfToken"><button type="submit" class="mt-2 w-full rounded-xl bg-red-50 px-4 py-3 text-left text-sm font-semibold text-red-600">Logout</button></form></nav><main id="main-content" class="p-4 sm:p-6 lg:ml-64 lg:p-8"><UiAlert v-if="page.props.flash?.success" tone="success" class="mb-6">{{page.props.flash.success}}</UiAlert><UiAlert v-if="page.props.flash?.error" tone="error" class="mb-6">{{page.props.flash.error}}</UiAlert><slot/></main></div></template>
