@extends('super-admin.layout') @section('title','Assign Role') @section('content')
<div class="page-header"><div><div class="admin-breadcrumb">Super Admin / Governance / Roles &amp; Permissions / User Assignments / {{$target->name}}</div><h1 class="page-title">Manage Access</h1><p>{{$target->name}} · {{$target->email}} · {{$target->mobile_e164?:$target->phone?:'No phone'}}</p></div><a class="btn btn-outline" href="{{route('super-admin.role-assignments.index')}}">Back to Assignments</a></div>
@include('super-admin.roles._tabs',['activeTab'=>'assignments'])
@if($errors->any())<div class="alert alert-error"><ul>@foreach($errors->all() as $error)<li>{{$error}}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{route('super-admin.role-assignments.update',$target)}}" id="role-form">@csrf @method('PUT')
<div class="grid grid-2"><div class="card"><div class="card-header">Role Assignment</div><div class="card-body"><div class="form-group"><label>Current role</label><input value="{{str($currentRole)->replace('_',' ')->title()}}" disabled></div><div class="form-group"><label for="assignment_role">New role</label><select id="assignment_role" name="assignment_role" required>@foreach(['photographer'=>'Photographer','team_member'=>'Team Member','group_member'=>'Group Member','super_admin'=>'Super Admin'] as $code=>$label)<option value="{{$code}}" @selected(old('assignment_role',$currentRole)===$code)>{{$label}}</option>@endforeach</select></div><div class="form-group"><label for="status">Effective status</label><select id="status" name="status"><option value="active">Active</option><option value="suspended" @selected(old('status',$target->status)==='suspended')>Suspended</option></select></div><div class="form-group"><label for="reason">Reason for change</label><textarea id="reason" name="reason" required minlength="8">{{old('reason')}}</textarea></div></div></div>
<div class="card"><div class="card-header">Account and Group Scope</div><div class="card-body"><div data-role-section="team_member"><div class="form-group"><label for="studio_owner_id">Parent Photographer account</label><select id="studio_owner_id" name="studio_owner_id"><option value="">Select Photographer</option>@foreach($photographers as $owner)<option value="{{$owner->id}}" @selected(old('studio_owner_id',data_get($currentScope,'team.0.studio_owner_id'))==$owner->id)>{{$owner->name}} — {{$owner->email}}</option>@endforeach</select></div><fieldset><legend>Safe team permissions</legend>@foreach($permissions as $permission)<label style="margin:.5rem 0"><input type="checkbox" name="permissions[]" value="{{$permission}}" @checked(in_array($permission,old('permissions',data_get($currentScope,'team.0.permissions',[]))?:[]))> {{str($permission)->replace('_',' ')->title()}}</label>@endforeach</fieldset></div><div data-role-section="group_member"><fieldset><legend>Assigned Groups</legend>@foreach($groups as $group)<label style="margin:.5rem 0"><input type="checkbox" name="group_ids[]" value="{{$group->id}}" @checked(in_array($group->id,old('group_ids',$currentScope['groups'])))> {{$group->name}} — {{$group->creator?->name}}</label>@endforeach</fieldset><div class="form-group"><label for="group_access_type">Gallery access</label><select id="group_access_type" name="group_access_type"><option value="full_access">Full gallery</option><option value="partial_access">Face matches and highlights only</option></select></div></div><div data-role-section="super_admin" class="alert alert-error"><div><strong>Super Admin can access and manage platform-wide administrative data and settings.</strong><label style="margin-top:.75rem"><input type="checkbox" name="confirm_super_admin" value="1"> I understand and explicitly authorize this access</label><label for="password" style="margin-top:.75rem">Your current password</label><input id="password" type="password" name="password" autocomplete="current-password"></div></div><div data-role-section="photographer"><p>This grants a dedicated Photographer dashboard, Group ownership capability and subscription controls. Existing owned data is preserved.</p></div></div></div></div>
<div class="card" style="margin-top:1rem"><div class="card-body"><h2 style="font-size:1rem">Role change impact</h2><p id="impact" style="color:var(--muted);margin:.5rem 0">Review the selected role and scope before confirming.</p><label><input type="checkbox" name="confirm_role_change" value="1" required> I reviewed the user, existing role, new role, scope and permission impact.</label><button class="btn btn-primary" style="margin-top:1rem" type="submit">Confirm Role Change</button></div></div></form>
<script>const role=document.getElementById('assignment_role'),sections=[...document.querySelectorAll('[data-role-section]')],impact=document.getElementById('impact');function sync(){sections.forEach(s=>s.hidden=!(s.dataset.roleSection===role.value||(role.value==='team_member'&&s.dataset.roleSection==='group_member')));impact.textContent=`{{$target->name}} will change from {{str($currentRole)->replace('_',' ')->title()}} to ${role.options[role.selectedIndex].text}. Incompatible global/account permissions will be removed and active sessions revoked.`}role.addEventListener('change',sync);sync();document.getElementById('role-form').addEventListener('submit',e=>{if(!confirm('Confirm this role and access change? The user will be signed out of active sessions.'))e.preventDefault()});</script>
@endsection
